### ISSUE TITLE
Windows still become transparent

### ISSUE THREAD

**Issue by mgrewe** [home-sweet-gnome/dash-to-panel#1284] opened 2021-02-24 08:55 UTC
Hi all,

unfortunately, I'm again experiencing these transparent windows as previously reported in #1260.
I think the bug is triggered differently, but again, I cannot clearly say it is triggered. I experienced that many different windows are now becoming transparent and not only those of a specific application. Maybe, it has again something to do with the highlighting?

I'm currently using latest master branch (e4a71fa) .

**Comment by Srijan1214** [comment] 2021-02-24 19:28
Hi,

I too am having this issue. Below is how I can reproduce this. In this example, I will use firefox.

- Press super and activate gnome overview.
- Open three windows of firefox. Put two windows on one workspace and the last window on another workspace.
- Using the dash to panel window's firefox logo, preview any of the windows in the first workspace to make the other windows transparent. Then preview the window in the second workspace.
- Press super to go out of overview.
- If you go to overview again, you will see that the windows are transparent.

**Comment by apirogov** [comment] 2021-04-28 08:45
I also suffer from windows becoming transparent. Dash-to-panel 40 from GNOME extensions site, Gnome-shell 3.36.7, Ubuntu 20.4 LTS

**Comment by mbarta** [comment] 2021-10-30 16:07
Hi! Could we re-open this ticket please as it's still a present issue in the latest `master` branch.

**Comment by VanCoding** [comment] 2021-11-26 09:27
I have this issue as well

**Comment by emragins** [comment] 2022-01-03 04:41
Pretty please.

**Comment by aiste4** [comment] 2022-01-09 21:35
Hello, I have this issue.
Dash To Panel 41, Fedora 35, GNOME Shell 41.2.
Can reproduce the issue with @Srijan1214 description.

**Comment by antcodd** [comment] 2022-01-09 22:12
I have also been having this issue for a while, I worked around it by setting hover preview peaking opacity to 255 but it would be nice to see this fixed.

**Comment by lmcjoma** [comment] 2022-01-11 20:23
This one should not have been closed. This is a very annoying problem for me, happening at least once a week. I typically have many windows oven across several workspaces, ant this forces me to close them, with all their logs and contents, and start over.
If this is so easily reporiducable, why is there no interest in fixing it?\
PLEASE RE-OPEN!

**Comment by hemebond** [comment] 2022-01-12 01:24
> this problem forces me to close them all

Restarting gnome-shell (run 'r') resolves the issue without having to close any applications.

**Comment by lmcjoma** [comment] 2022-01-12 15:03
> > this problem forces me to close them all
> 
> Restarting gnome-shell (run 'r') resolves the issue without having to close any applications.

That would be a work around for now. But I don't understand what you mean with "run 'r'". There is of course no such bash command, and when trying Alt-F2 and Alt-F4 as suggested elsewhere it has no visible effect. Running "Reset" from the shell window menu should work (I didn't succeed in reproducing the condition when I tried now) , but I would have to do it window by window. We still need a proper fix for this.

**Comment by hemebond** [comment] 2022-01-12 15:06
> when trying Alt-F2
This is what I meant. ALT+F2, then just type `r` into the text box. That will restart gnome-shell.

**Comment by lmcjoma** [comment] 2022-01-12 15:29
> > when trying Alt-F2
> 
> This is what I meant. ALT+F2, then just type `r` into the text box. That will restart gnome-shell.

Thank you. That will be a help.

**Comment by realitix** [comment] 2022-02-02 08:53
Hello,
I'm having this very annoying bug too. It happens each day. I work with lot of windows and multi-screen.
I can't use the workaround ALT+F2 and `r` because I'm on Wayland and Gnome shell can't restart on Wayland.

Waiting for the fix, thanks.

**Comment by mgrewe** [comment] 2022-02-02 09:44
I'm also still experiencing the issue. However, this issue was closed. It might thus be wise to open a new issue to get attention of the devs.

**Comment by charlesg99** [comment] 2022-04-02 22:24
Thanks! Should now be fixed on the master branch.

**Closed by charlesg99** 2022-04-02 22:24 UTC
Labels: bug
