### ISSUE TITLE
[Feature request] Hotkeys to switch between windows

### ISSUE THREAD

**Issue by amezin** [home-sweet-gnome/dash-to-panel#603] opened 2019-03-17 04:54 UTC
I'd like to use Super+Num hotkeys to switch between open windows, not applications.

I'll try to implement this myself. Any suggestions on how to do it/where to look in the code?

**Comment by charlesg99** [comment] 2019-03-17 17:55
Hello amezin, you can have a look at the [_activateApp function of the overview.js file](https://github.com/home-sweet-gnome/dash-to-panel/blob/f2248010dd4eac88a14ac90634bb1870b55f0423/overview.js#L166). 

We already have an option to select windows using the hotkeys, maybe this would suit your need? 

![image](https://user-images.githubusercontent.com/33044886/54495634-c011ff80-48bb-11e9-9f56-3c221e53f9d4.png)

Thanks!

**Comment by amezin** [comment] 2019-03-17 18:51
Hm... I have that option enabled. But when I have multiple windows of the same application, I can't switch between them using Super+#. And window previews don't appear. Maybe its because I have "Ungroup applications" enabled?

Even if it somehow worked, I want 1 shortcut=1 window. Like Super+1 = Chrome window 1, Super+2 = Chrome window 2.
Also I don't think I need shortcuts that launch applications. I switch between windows a lot more frequently, and there easily could be 10 open windows or more. In this case I need shortcuts for windows and not application launchers.

So it looks more like another dedicated mode.
Though maybe it's a good idea to use different shortcuts for different windows when grouping is disabled.

**Comment by charlesg99** [comment] 2019-03-17 19:25
I just did some modifications for the hotkeys on 3.32, could you pull the latest master?

> Maybe its because I have "Ungroup applications" enabled?

Should work correctly even with ungrouped applications... You're not seeing this (in this I'm pressing Super+4) ?

![Peek 2019-03-17 15-15](https://user-images.githubusercontent.com/33044886/54496613-c1e1c000-48c7-11e9-813d-d6da57bcf561.gif)


> I want 1 shortcut=1 window

This seems a bit confusing to me, unless you always have the same windows opened in the same order. It should definitely be a dedicated mode/option.

Thanks!

**Comment by amezin** [comment] 2019-03-17 19:59
> I just did some modifications for the hotkeys on 3.32, could you pull the latest master?
> 
> > Maybe its because I have "Ungroup applications" enabled?
> 
> Should work correctly even with ungrouped applications... You're not seeing this (in this I'm pressing Super+4) ?

Now it works, thank you

> 
> > I want 1 shortcut=1 window
> 
> This seems a bit confusing to me, unless you always have the same windows opened in the same order. It should definitely be a dedicated mode/option.

No, I don't have the same windows always in the same order. But I have number overlays always enabled.

**Comment by charlesg99** [comment] 2019-03-17 23:02
I just realized that what you're asking for was the previous hotkey behavior... It was "fixed" (or broken from your perspective) following issue #471. You can have a look at what was done on b94535478802339c139614dc9b8a9abbe2fb6458. Thanks!

**Comment by anirudhnihalani** [comment] 2019-04-25 18:28
@charlesg99 On ubuntu 19.04 I am not able switch between multiple instances of same application with it's hotkey, this used to work fine on ubuntu 18.04. Is this an intended behaviour on the latest version?

**Comment by charlesg99** [comment] 2019-04-25 21:07
Hello @anirudhnihalani, I just tried on ubuntu 19.04 and it works just fine when the click action is set to "cycle windows", could you try the latest development version? Thanks!

**Comment by anirudhnihalani** [comment] 2019-04-25 21:38
It's working fine in the latest development version!!
However, in both versions (gnome extensions website version and development version) I am able to switch applications using hotkeys even with the hotkeys toggle off, only between applications though not between instances of same application.

**Comment by charlesg99** [comment] 2019-04-25 22:08
Yes, this is because gnome-shell introduced their [own hotkeys in 3.32](https://gitlab.gnome.org/GNOME/gnome-shell/commit/4590094605774dab4c76d67953cf032616dee089) and we only disable those when enabling the dash to panel ones. So in short, when you don't enable dash to panel hotkeys, the gnome-shell ones are used. Hope it makes sense! Thanks!

**Comment by charlesg99** [comment] 2019-05-12 02:25
Gonna close this for now. As previously discussed, we decided that the current hotkeys behavior is the desired one. If you end up reverting the changes, feel free to submit a pull request that would offer both options. Thanks!

**Closed by charlesg99** 2019-05-12 02:25 UTC
