### ISSUE TITLE
Notification badge/counts causes app icons to have grown width

### ISSUE THREAD

**Issue by hrdwrrsk** [home-sweet-gnome/dash-to-panel#896] opened 2020-03-12 23:42 UTC
dash-to-panel in GNOME 3.36 seems to have annoying issue when notification badge/dot/counts is appearing. App icon width will grow up and glitched, but only affects to app that have notification badge support e.g Telegram

**Comment by hrdwrrsk** [comment] 2020-03-13 06:33
some gif recording
![Peek 2020-03-13 13-31](https://user-images.githubusercontent.com/9630564/76595790-2bbe9500-652f-11ea-82ad-b18843154d77.gif)

**Comment by chrisjbillington** [comment] 2020-03-13 15:46
Other people are having a similar issue without using dash to panel:

https://www.reddit.com/r/archlinux/comments/fhvo9w/gnome_336_top_bar_icons_misaligned/

Bugs are being reported against extensions, but it sounds like an issue in gnome-shell itself

**Comment by charlesg99** [comment] 2020-03-16 02:41
Hello hrdwrrsk and thank you for the report. A fix for the badges on 3.36 was added to the master branch, could you install it and see if that solves the issue on your end? I still need to test for regression on older gnome-shell versions, but it's working fine for me so far. Thanks!

**Comment by kleinHeiti** [comment] 2020-03-20 14:01
Hello,

I don't know if my clue is directly related to this bug. But I noticed that the counter on icons is round in the "normal" view, but square in the application view. 
I have installed the last master. Gnome version is 3.36 on Ubuntu 20.04 (pre)

By the way: I have no problem with increased width when hovering over the icons.

![Bild_1](https://user-images.githubusercontent.com/54942072/77170357-39d65d80-6abb-11ea-8b04-bbd921e760cc.png)
![Bild_2](https://user-images.githubusercontent.com/54942072/77170370-3f33a800-6abb-11ea-8426-76e922b7837f.png)

**Comment by charlesg99** [comment] 2020-03-20 18:35
Hello @kleinHeiti, could you elaborate how you're getting the squared badge? I can't reproduce this as it always is rounded for me on 3.36. Thanks!

**Comment by kleinHeiti** [comment] 2020-03-21 08:57
Hi Charles,
ich habe gerade den Rechner neu gestartet und versucht das problem zu 
reproduzieren.

Leider muss ich dir mitteilen, dass auch bei mir das Verhalten der 
Zähler wie gewünscht ist. Auch bei mir ist die Darstellung jetzt in 
beiden Fällen rund.

Ich muss mich für die unnötige Arbeit, die ich dir beschafft habe, 
entschuldigen.

kleinHeiti

Am Fr, 20. Mär, 2020 um 11:35 A. M. schrieb Charles Gagnon 
<notifications@github.com>:

**Comment by kleinHeiti** [comment] 2020-03-21 09:18
Hi, Charles,
i just rebooted the computer and tried to reproduce the problem.

Unfortunately I have to tell you that the behaviour of the counters is 
as desired. Also with me the display is now round in both cases.

I have to apologize for the unnecessary work I have given you.

kleinHeiti

Am Fr, 20. Mär, 2020 um 11:35 A. M. schrieb Charles Gagnon 
<notifications@github.com>:

**Comment by charlesg99** [comment] 2020-03-21 12:28
Hello kleinHeiti, no problem! When upgrading an extension, it is always best to restart gnome-shell afterwards to make sure the changes are properly reloaded. Thank you for reporting back, I'm going to close this for now.

**Closed by charlesg99** 2020-03-21 12:28 UTC
