### ISSUE TITLE
Active application indicator clipping

### ISSUE THREAD

**Issue by sibaar** [home-sweet-gnome/dash-to-panel#647] opened 2019-05-16 22:53 UTC
Orange dots indicating open applications are missing. Entire bar is clipped.
Only clipped when "runnning indicator position" is set to bottom while the task bar position in on the bottom. Works fine when bar is moved to the top.

https://imgur.com/a/71SSCe4

**Comment by sibaar** [comment] 2019-05-16 23:03
Just noticed that the issue is caused by the bar being too thin. Please consider adding a vertical bar padding slider.

**Comment by jderose9** [comment] 2019-05-17 19:19
Hmmm.. I haven't seen this. Which theme are you using? I'm wondering if some sort of negative padding is being applied.

**Comment by cesarizu** [comment] 2019-05-17 21:14
This happens to me on gnome 3.32 with the default adwaita dark, no custom shell theme.

**Comment by charlesg99** [comment] 2019-05-18 03:48
Hello, are you using a scale larger than 100% for your display? My guess is that it is a duplicate of #595 #628 #637. If so, please install the latest development version to resolve the issue until a new version is released to e.g.o. Thanks!

**Comment by cesarizu** [comment] 2019-06-12 16:53
Sorry for the late reply. I switched to running from this repo instead of the gnome extensions website version and it is not happening for me anymore.

**Comment by sibaar** [comment] 2019-06-13 03:00
Yes. Using a HiDPI screen. 3k. 

@cesarizu how do you install the software from the repo?

**Comment by charlesg99** [comment] 2019-06-23 00:05
@sibaar Hopefully you got it working already, but if not please see [the wiki](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github). Thanks!

**Closed by charlesg99** 2019-06-23 00:05 UTC
