### ISSUE TITLE
Mouse clicks and scroll don't work in windows preview area after exiting "fullscreen mode" of any application

### ISSUE THREAD

**Issue by vlaarx** [home-sweet-gnome/dash-to-panel#715] opened 2019-08-21 16:54 UTC
Example: https://youtu.be/U6DBxpbRQlk
Fedora 30. Gnome 3.32.2

**Comment by charlesg99** [comment] 2019-08-21 19:21
Hello vlaarx, thank you for reporting this. I can't reproduce the issue so far (g-s 3.32.2, xorg and wayland), but I would really like to! Is there anything else special with your installation? Any other extensions? Which version of dash to panel is that? Could you share your settings (from the dash to panel settings, "About" tab)? Thanks!

**Comment by vlaarx** [comment] 2019-08-21 22:06
I had that issue in dash to panel version 20. Today morning I updated it to v.21 but the problem hadn't gone. However I reinstalled all extensions recently and this made difference (I tried the same unsuccessfully while using v.20). So I can't reproduce that bug now.
my settings: [settings.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/3527350/settings.txt)
extensions I use:
![image](https://user-images.githubusercontent.com/53967046/63469202-56051400-c472-11e9-9f8b-0ba76b6799d2.png)

**Comment by charlesg99** [comment] 2019-08-21 22:56
Glad to hear it! I looked back at the new window previews history and any version before commit 3f6361a110ec3c92570ecfc7bf368ea18d81ae82 indeed had this problem (I just tried  045350db8207b5fe023b082c6acdc2c2f9b80eba and I could reproduce the issue you demonstrated). We can close the issue since it was due to an old version, Great!

**Closed** 2019-08-21 23:48 UTC
