### ISSUE TITLE
"Quit N Windows" does not close all gnome-terminal windows

### ISSUE THREAD

**Issue by GriffinLeclerc** [home-sweet-gnome/dash-to-panel#1796] opened 2022-11-12 22:05 UTC
**Describe the bug**
Selecting "Quit N Windows" (where N > 1 is the number of open windows for the application) does not quit all gnome-terminal windows. Any other application functions as intended; all N windows are quit.

**Linux distribution and version**
Ubuntu 22.04.1 LTS

**GNOME Shell version**
GNOME Shell 42.4

**Dash-to-Panel version**
version: 52

**Where was Dash-to-Panel installed from?**
https://github.com/mjakeman/extension-manager

**Screenshots / Video captures**
This video showcases three applications: Firefox, Nautilus and GNOME Terminal, with five windows of each. 
"Quit 5 Windows" closes all Firefox and Nautilus windows as expected, but does not do so with Terminal.

[Screencast from 11-12-2022 04:48:10 PM.webm](https://user-images.githubusercontent.com/57186877/201496274-138a750e-1141-4ba9-9b19-87a747e35b3f.webm)

**Comment by charlesg99** [comment] 2022-11-13 13:50
Duplicate of #1513 and the issue is fixed on the master branch. Thanks!

**Closed by charlesg99** 2022-11-13 13:50 UTC
Labels: bug
