### ISSUE TITLE
Dash-to-Panel blinks when firefox/web browser is maximized and mouse is moving on the panel

### ISSUE THREAD

**Issue by pyway** [home-sweet-gnome/dash-to-panel#1764] opened 2022-10-02 06:05 UTC
Dash-to-Panel blinks when firefox/web browser is maximized and mouse is moving on the panel icons.

Ubuntu 22.04.
GNOME Shell 42.4

Dash-to-Panel 52 ( occurs with the old versions)
installed directly from github.

**Comment by jonas-w** [comment] 2022-10-12 13:35
Having the same problem in firefox with intellihide, when i want to open the panel it flickers and is really unusable, this also happens with chromium / chromium based stuff like electron apps (spotify, vscode etc.)

**Comment by pyway** [comment] 2022-10-13 00:35
I think this problem caused by OS repeatedly updating the area occupied by dash-to-panel.  if dash-to-panel appears as the popup window of an application ( JS related ),  Gnome GUI system will only update the popup window; otherwise, dash-to-panel should be the most top application window, GUI system only updates it, instead of updating two applications alternately.
I also use dash-to-panel with intellihide enabled. thanks to jonas-w.

**Comment by charlesg99** [comment] 2022-10-13 13:15
Could you define "flickers"? Even better, post a video of it. I've never been able to reproduce a "flicker" with maximized firefox/chromium, xorg or wayland, intellihide or not.

In the linked issue by @m1027, I'm pretty sure "flicker" refers to the fact that the panel is always visible when the extension is first enabled, then after a user defined delay (minimum 10 milliseconds), the panel hides. So you end up always seing the panel's hiding animation, even if you unlock your screen and had a maximized window opened before locking.

**Comment by jonas-w** [comment] 2022-10-13 15:35
Okay i tried to screenrecord it, but on the screenrecord it looks like it's working. But it differs completely from what i'm really seeing. That's why i'm sending you a video recorded on my phone. And the file is bigger than the upload limit on GitHub so here is the link: https://0x0.st/ovjt.mp4

**Comment by pyway** [comment] 2022-10-14 00:53
I just installed dash-to-panel, GPaste, GSConnect, no other extensions. but it 's normal with maximized Codium.

**Comment by charlesg99** [comment] 2022-10-14 13:43
@jonas-w Thanks for the video, I've seen reports of this issue come up from time to time but never was able to reproduce (but I'd love to). I tried to setup my panel as yours but it still behaved normally on my system (gnome-shell 42.5, xorg and wayland). Could you share your dash to panel settings?

@pyway what do you mean by "it's normal", does it work correctly or not?

**Comment by pyway** [comment] 2022-10-14 15:42
@charlesg99 it's normal that means dash-to-panel works correctly. i recorded a video by my mobile, but i don't know how to share to you.

**Comment by jonas-w** [comment] 2022-10-18 16:59
@charlesg99 okay the only other notable things i have installed is the Orchis Theme (i already disabled it and it didn't change anything), gsconnect and appindicator support. All the other stuff i have installed shouldn't interfere with it in any way (firefox, rnote, etc.). 

I use plain arch linux with the normal x86_64 kernel and i installed dash-to-panel from the AUR.

It is a fairly new install (3 weeks ago), and it behaves like this since day one.

```toml
[/]
animate-appicon-hover=true
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
appicon-margin=8
appicon-padding=4
available-monitors=[0, 1]
group-apps=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=true
intellihide-behaviour='ALL_WINDOWS'
intellihide-hide-from-windows=true
intellihide-key-toggle=['<Super>i']
intellihide-key-toggle-text='<Super>i'
intellihide-pressure-threshold=200
intellihide-pressure-time=1500
intellihide-show-in-fullscreen=true
intellihide-use-pressure=true
leftbox-padding=-1
panel-anchors='{"0":"MIDDLE","1":"MIDDLE","2":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}],"1":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"dateMenu","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":true,"position":"stackedBR"}]}'
panel-lengths='{"0":70,"1":70,"2":80}'
panel-positions='{"0":"BOTTOM"}'
panel-sizes='{"0":55,"1":55,"2":60}'
primary-monitor=0
show-appmenu=false
status-icon-padding=-1
stockgs-keep-dash=false
stockgs-keep-top-panel=false
stockgs-panelbtn-click-only=false
trans-use-custom-opacity=false
tray-padding=-1
window-preview-title-position='TOP'
```

**Comment by freddyw** [comment] 2022-10-19 06:29
I have seen this kind of behavior as well (fedora 36/37, d-t-p 52 from git) and switch back to x11/xorg for that very reason. With x11/xorg intellihide works as expected, wayland is a totally different story. Maybe someone can confirm that this is indeed wayland related?

**Comment by pyway** [comment] 2022-10-19 11:50
@freddyw yes, wayland related.   dash-to-panel works well with browser(firefox/web) maximized  on x11/xorg.

**Comment by freddyw** [comment] 2022-10-19 14:13
@pyway, thanks for checking, will stay on x11/xorg for now.

**Comment by mihalycsaba** [comment] 2022-11-12 01:18
I have this problem too, tried chrome, steam, nautilus. When I push on the screen edge it appears then instantly disappears with the regular animation, but faster. The weird thing is, it works perfectly with gnome-terminal. 
I'm not sure, but on gnome 42, chrome and electron apps had this issue only.
I'm on arch, gnome 43, wayland and amd gpu.

**Comment by mihalycsaba** [comment] 2022-11-12 01:21
Actually I just remembered, on gnome 42 the mentioned apps had the issue, so it's not a new bug on 43.

**Comment by mihalycsaba** [comment] 2022-11-13 14:07
Tried disabling every extension except dash-to-panel, didn't help. Also it doesn't work with the reveal and hold keyboard shortcut either, so it's probably not because of the mouse position.

**Comment by aportilla** [comment] 2022-11-16 22:13
I'm also seeing this blinking glitch with intellihide and maximized windows on a fresh Fedora 37 install with Gnome 43 and Wayland.

![Screenshot from 2022-11-16 14-08-35](https://user-images.githubusercontent.com/150895/202305581-796f3baa-c961-4bbd-b7c1-5cad295fe5e1.png)

**Comment by cbeley** [comment] 2022-11-18 04:58
I'm also getting this on Ubuntu 22.10 when I have various apps maximized (not full-screen). Using https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/ fixes it for me though.

Dash to dock seems to have a similar issue: https://github.com/micheleg/dash-to-dock/issues/1813 .

**Comment by mihalycsaba** [comment] 2022-11-18 16:59
Can confirm, that extension works on arch too.

**Comment by mmilitzer** [comment] 2022-11-27 14:45
I've been facing the same issue today after upgrading to Fedora 37 from 35. Also had the panel closing immediately again (flickering) with Intellihide when the foreground application window is maximized. Happens with various applications (Firefox, Chrome, Nautilus, ...).

However, there are also applications where the Intellihide panel works fine also with maximized app window (terminal and gedit, for example). On Fedora 35 (before upgrading) I didn't have a problem while I was also on Wayland already.

I can also confirm that the "disable-unredirect-fullscreen-windows" extension linked above solved the problem for me.

**Comment by pyway** [comment] 2022-11-28 06:35
disable-unredirect-fullscreen-windows extension solved this flickering problem for me. 
thanks to @mmilitzer.

**Comment by mmilitzer** [comment] 2022-11-28 07:29
I would suggest keeping this issue open and consider integrating the functionality of the "disable-unredirect-fullscreen-windows" extension directly into Dash-to-Panel. It's just very little code:

https://github.com/kazysmaster/gnome-shell-extension-disable-unredirect/blob/master/unredirect%40vaina.lt/extension.js

And then this issue would be fixed for everyone without the need to install yet another extension (and having to spend time first searching for the solution)...

**Comment by freddyw** [comment] 2022-11-28 10:12
Can confirm as well, adding Meta.[en|dis]able_unredirect_for_display(global.display) to enable/disable in extension.js fixes the issue.

**Comment by freddyw** [comment] 2022-11-28 15:08
> I can't reproduce so @freddyw could you remove Meta.[en|dis]able_unredirect_for_display(global.display) from extension.js and comment out line 340 of panel.js (this.set_offscreen_redirect(Clutter.OffscreenRedirect.ALWAYS);), see if that fix the issue as well?

Tried as suggested but that does NOT fix the issue. The Meta.[en|dis]able_unredirect_for_display(global.display) does seem to ne necessary.

**Comment by pyway** [comment] 2022-11-30 15:08
> I would suggest keeping this issue open and consider integrating the functionality of the "disable-unredirect-fullscreen-windows" extension directly into Dash-to-Panel. It's just very little code:
> 
> https://github.com/kazysmaster/gnome-shell-extension-disable-unredirect/blob/master/unredirect%40vaina.lt/extension.js
> 
> And then this issue would be fixed for everyone without the need to install yet another extension (and having to spend time first searching for the solution)...

Thanks for your suggestion，so reopen this.

**Comment by ztmaev** [comment] 2022-12-13 15:15
> 
This fixes the issue, just make sure your shell version is in **local/share/gnome-shell/extensions/unredirect@vaina.lt/metadata.json**

**Comment by phanos-engineer** [comment] 2022-12-27 15:53
Same problem with Arch linux

**Comment by charlesg99** [comment] 2023-02-10 12:52
This should be fixed on the master branch.

**Comment by charlesg99** [comment] 2023-02-10 12:54
Let's leave https://github.com/home-sweet-gnome/dash-to-panel/issues/1666 opened for now

**Closed by charlesg99** 2023-02-10 12:54 UTC
Labels: bug

**Comment by pyway** [comment] 2023-03-22 12:38
> This should be fixed on the master branch.
v55 is OK, thanks.
