### ISSUE TITLE
Auto-hide intelligent option is not working on Fedora 32 Gnome 3.36.1

### ISSUE THREAD

**Issue by calotam** [home-sweet-gnome/dash-to-panel#935] opened 2020-04-04 08:15 UTC
With the new version of this addon, now I can see all applications, but the dock is now always hidden, and the option auto-hide intelligent is not working.

**Comment by charlesg99** [comment] 2020-04-04 12:55
Hello calotam. Not sure what you mean by "I can see all applications, but the dock is now always hidden", but did you restart gnome-shell following the update? Thanks!

**Comment by calotam** [comment] 2020-04-05 07:47
Forget the comment 'I can see all applications'.
The issue is about the dock is always hidden unless the mouse is in left side (i have the dock in left side).
I mean that if I config the dock to auto-hide intelligent, the dock should be shown if no windows is on the dock. This was the behavior until last dash-to-panel update.

**Comment by charlesg99** [comment] 2020-04-05 15:09
Hello calotam! Yes thank you, I could reproduce the issue when starting gnome-shell with the panel on the left or right. Sorry about this, it is now fixed on the master branch.

@jderose9 This is a side effect of #921, I see that v34 isn't yet approved on e.g.o., might be good to squeeze that in if you feel like it as that's an annoying one too. Sorry about this, hopefully that's the last 3.36 adjustment!

**Comment by jderose9** [comment] 2020-04-05 16:12
@charlesg99 I pulled v34 from the review queue. Should we see how #938 turns out before release?

**Comment by charlesg99** [comment] 2020-04-05 16:28
@jderose9 Ha great, I thought it got approved. In that case I would go ahead now... I could reproduce the issue in #938 and added another fix for it (the clipping wasn't updated correctly when changing the panel size).

On a side note, not sure if the new 3.36.1 Extensions app modified the way it detects the installed version of the extension, but since this morning it overwrites my version (copied by Make) on every gnome-shell restart. Seems like they changed the metadata format (namely the uuid field...), here is what the Extensions app puts in `~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com`:

```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "An icon taskbar for the Gnome Shell. This extension moves the dash into the gnome main panel so that the application launchers and system tray are combined into a single panel, similar to that found in KDE Plasma and Windows 7+. A separate dock is no longer needed for easy access to running and favorited applications.\n\nFor a more traditional experience, you may also want to use Tweak Tool to enable Windows > Titlebar Buttons > Minimize & Maximize.\n\nFor the best support, please report any issues on Github. Dash-to-panel is developed and maintained by @jderose9 and @charlesg99.",
  "extension-id": "dash-to-panel",
  "gettext-domain": "dash-to-panel",
  "name": "Dash to Panel",
  "shell-version": [
    "3.18",
    "3.20",
    "3.22",
    "3.24",
    "3.26",
    "3.28",
    "3.30",
    "3.34",
    "3.32",
    "3.36"
  ],
  "url": "https://github.com/jderose9/dash-to-panel",
  "uuid": "dash-to-panel@jderose9.github.com",
  "version": 33
}
``` 

Anyway, I would release the fix asap and we can look into that later I guess.

**Comment by jderose9** [comment] 2020-04-05 17:18
geeez... 3.36 is the release that keeps on giving, huh? Sure wish we could get some stability here.

**Comment by charlesg99** [comment] 2020-04-05 18:32
Yeah it feels like it started not so bad, but I'm rethinking that initial assessment. 

For the metadata issue, I did some tests and it looks like the problem is the version that e.g.o. think we're at when the Extensions app is calling the verification endpoint. Like if it's considering the v34 that you pulled earlier or something. I would need to check the e.g.o. api code, but I can't find it. Anyway I'm not too worried about this one, if I put v35 in our metadata, that shuts it up, so I'm pretty sure the next released version will fix the mismatch. If not, this should only affect github users, so we can look into it later. 

Thanks!

**Closed** 2020-04-06 13:01 UTC
Labels: bug

**Comment by jderose9** [comment] 2020-04-07 23:48
@charlesg99 Regarding the change in version detection - have you tested, by chance, what happens when the built-in updated has replaced the older version? Does that get written over as well?

**Comment by charlesg99** [comment] 2020-04-08 01:09
Hey Jason! Yep it is overwritten as we install the downloaded package from github before login out. If gnome-extensions has downloaded a new version as well, it'll install it afterwards the one downloaded by our update mechanism. Our mechanism is still useful in the case of a long review, but feels less relevant now. Oh well! 

Also, the v33-v34 mismatch that had me update every time I ran Make seems to be resolved since v35, probably a hiccup.
