### ISSUE TITLE
[Feature Request] Add option to move "Show applications" icon to the left

### ISSUE THREAD

**Issue by Oqtavios** [home-sweet-gnome/dash-to-panel#644] opened 2019-05-09 17:46 UTC
Hi,
When the taskbar position is set to _center_, "Show applications" icon looks _separated_ from apps icons. It _breaks the "centering"_ of the taskbar. My feature request is to add an option to _move this icon to the left_ of the panel, like the launcher button in Chrome OS:
![chrome-os-71-better-together-4](https://user-images.githubusercontent.com/3875187/57474476-d1173580-729a-11e9-8da0-b78de588707f.png)

Thanks!

**Comment by charlesg99** [comment] 2019-05-09 20:52
Hello Oqtavios, the Show Applications icon has its own padding, so you can separate it a bit from the app icons. You could remove this padding so its spacing would be the same as the app icons:

![image](https://user-images.githubusercontent.com/33044886/57485629-31e24600-727a-11e9-84ba-20e7d4a26419.png)

As for the request to move it to the left of the panel, this is a duplicate of #150, so please register to this issue for updates or new information about it. 

Thanks!

**Closed by charlesg99** 2019-05-09 20:52 UTC
