### ISSUE TITLE
Show mounted devices in dash.

### ISSUE THREAD

**Issue by emoxam** [home-sweet-gnome/dash-to-panel#2085] opened 2024-04-18 10:11 UTC
**Describe the idea or feature you'd like**
Dash-to-dock showing mounted devices.
Dash-to-panel don't. There is no such option.

**Is your feature request related to a problem? Please describe.**
I want to ask you to add such feauture - showing mounted devices.

**Additional context**
Add any other context or mock-ups for requested feature here.
thanks

**Comment by tekstryder** [comment] 2024-04-18 12:09
Duplicate of https://github.com/home-sweet-gnome/dash-to-panel/issues/1888

Please mark as such and close this issue.

**Closed** 2024-04-18 12:35 UTC
Labels: enhancement
