### ISSUE TITLE
When a lot of WIFIs appear on the WIFI quick tile list the quick settings panel disappears

### ISSUE THREAD

**Issue by Stidon** [home-sweet-gnome/dash-to-panel#1792] opened 2022-11-06 10:22 UTC
**Describe the bug**
The first screencast is showing the screen that has just enough WIFIs to not disappear.
The second one is after there is too many WIFIs for the screen to show.

**Linux distribution and version**
Ubuntu 22.10

**GNOME Shell version**
43

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
[1st Screencast](https://user-images.githubusercontent.com/72616233/200165334-ddbca4d4-5c55-4926-9a58-b0b8fcc7c71e.webm)
[2nd Screencast](https://user-images.githubusercontent.com/72616233/200165364-a49b4a73-6e8e-4442-9796-7143cdd075b7.webm)

**Comment by Stidon** [comment] 2022-11-06 10:24
The first screencast is showing the screen that has just enough WIFIs to not disappear.
The second one is after there are too many WIFIs for the screen to show.

**Comment by charlesg99** [comment] 2022-11-13 14:44
Thanks for reporting this, it is a duplicate of #1779. I'll rename it so it is more obvious.

**Closed by charlesg99** 2022-11-13 14:44 UTC
Labels: bug
