### ISSUE TITLE
Icons is not showing in taskbar in dash to panel

### ISSUE THREAD

**Issue by huyhoang8398** [home-sweet-gnome/dash-to-panel#1680] opened 2022-05-28 12:23 UTC
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
A clear and concise description of what the problem is, any steps to reproduce, and what you expected to happen instead.
Icons is not showing in taskbar in dash to panel

**Linux distribution and version**
Ubuntu 22.04 gnome

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
Dash-to-Panel version 50 

**Where was Dash-to-Panel installed from?**
Gnome extension website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/25379882/170825333-0d56a5a3-e71e-4270-a966-4b54a7e70013.png)

**Additional Info**

**Comment by huyhoang8398** [comment] 2022-05-28 12:33
The problem apprears when using multi monitors

**Comment by huyhoang8398** [comment] 2022-05-30 15:38
Look like if I setup a vertical multi monitor and enable show dash to panel on both monitors

**Comment by josuegomes** [comment] 2022-05-31 19:03
Experiencing the same problem here. Same system: Ubuntu 22.04, Gnome 42, Dash to Panel 50.
Logs captured:

```
Window manager warning: Failed to start restart helper: Failed to execute child process “/usr/libexec/mutter-restart-helper” (No such file or directory)
Window manager warning: Failed to start restart helper: Failed to execute child process “/usr/libexec/mutter-restart-helper” (No such file or directory)
Window manager warning: Failed to start restart helper: Failed to execute child process “/usr/libexec/mutter-restart-helper” (No such file or directory)
Object .MetaWindowActorX11 (0x559a6149a370), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .MetaWindowActorX11 (0x559a6149a370), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .MetaWindowActorX11 (0x559a6149a370), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x559a59c44190 ==
== Stack trace for context 0x559a59c44190 ==
== Stack trace for context 0x559a59c44190 ==
#0   559a5d3ce898 i   resource:///org/gnome/shell/ui/windowManager.js:1542 (26aa82429c90 @ 23)
#0   559a5d3ce898 i   resource:///org/gnome/shell/ui/windowManager.js:1542 (26aa82429c90 @ 23)
#0   559a5d3ce898 i   resource:///org/gnome/shell/ui/windowManager.js:1542 (26aa82429c90 @ 23)
#1   7ffd399aeca0 b   self-hosted:1181 (2a9b603b0a10 @ 454)
#1   7ffd399aeca0 b   self-hosted:1181 (2a9b603b0a10 @ 454)
#2   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
#1   7ffd399aeca0 b   self-hosted:1181 (2a9b603b0a10 @ 454)
#2   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
GNOME Shell crashed with signal 11
#2   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
GNOME Shell crashed with signal 11
== Stack trace for context 0x559a59c44190 ==
GNOME Shell crashed with signal 11
== Stack trace for context 0x559a59c44190 ==
#0   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
== Stack trace for context 0x559a59c44190 ==
#0   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
JS ERROR: TypeError: window is null
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1543:9
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:260:16
JS ERROR: TypeError: window is null
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1543:9
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:260:16
#0   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)


JS ERROR: TypeError: window is null
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1543:9
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:260:16

Window manager warning: Failed to start restart helper: Failed to execute child process “/usr/libexec/mutter-restart-helper” (No such file or directory)
Object .MetaWindowActorX11 (0x559a6149a370), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x559a59c44190 ==
#0   559a5d3ce898 i   resource:///org/gnome/shell/ui/windowManager.js:1542 (26aa82429c90 @ 23)
#1   7ffd399aeca0 b   self-hosted:1181 (2a9b603b0a10 @ 454)
#2   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
GNOME Shell crashed with signal 11
== Stack trace for context 0x559a59c44190 ==
#0   559a5d3ce818 i   resource:///org/gnome/shell/ui/main.js:260 (2a9b603ef150 @ 12)
JS ERROR: TypeError: window is null
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1543:9
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:260:16

Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
ATK Bridge is disabled but a11y has already been enabled.
ATK Bridge is disabled but a11y has already been enabled.
ATK Bridge is disabled but a11y has already been enabled.
ATK Bridge is disabled but a11y has already been enabled.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 5
Will monitor session 5
Telepathy is not available, chat integration will be disabled.
Telepathy is not available, chat integration will be disabled.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 5
Telepathy is not available, chat integration will be disabled.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 5
Telepathy is not available, chat integration will be disabled.
Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b570 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8c6c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8b9d0 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e8e050 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x561ef6e95e90 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
GNOME Shell started at Tue May 31 2022 16:01:17 GMT-0300 (-03)
Registering session with GDM
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
GNOME Shell started at Tue May 31 2022 16:01:17 GMT-0300 (-03)
Registering session with GDM
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
GNOME Shell started at Tue May 31 2022 16:01:17 GMT-0300 (-03)
Registering session with GDM
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
GNOME Shell started at Tue May 31 2022 16:01:17 GMT-0300 (-03)
Registering session with GDM
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561ef62f2360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb2750] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb66c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561ef7fb3b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561ef7fb7840] is on because it needs an allocation.
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.1.1
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.1.1
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.1.1
DING: Detected async api for thumbnails
DING: GNOME nautilus 42.1.1

```

**Comment by josuegomes** [comment] 2022-05-31 19:05
![Screenshot from 2022-05-31 15-59-35](https://user-images.githubusercontent.com/2146286/171265419-4720f117-34ce-4eff-83f9-8bd7058bd051.png)

Terminal and VS Code icons missing.

**Comment by toastard** [comment] 2022-07-10 23:01
I'm also experiencing the same problem. Also not sure if it's related, but sometimes the icon does appear but it shows up extremely tiny. See the fourth icon for "software" in the below.

![image](https://user-images.githubusercontent.com/63200988/178165362-bc1cf81f-e13f-414e-a4e4-a73d656d4c88.png)

**Comment by darkblaze69** [comment] 2022-08-29 09:17
I also have this annoying problem. Using Manjaro GNOME 42.4 + Wayland + Fixed 1 workspace

**Comment by dragonwize** [comment] 2022-09-14 17:00
This is fixed for me in the lastest version (v51).

**Comment by drewdrew0** [comment] 2022-11-29 19:16
I am still having this exact problem, and it makes my workflow, well un-workable, as I'm constantly loosing windows.  They either disappear (and maybe will reappear temporarily later, usually upon workspace switching, just to disappear again for the most part), or once in a while display super tiny/thin as described above.  And FWIW, I do not have multiple monitors.  Just using built-in laptop display, and 4 fixed workspaces.

Linux distribution and version
Ubuntu 22.04 gnome

GNOME Shell version
GNOME Shell 42.5

Dash-to-Panel version
Dash-to-Panel version 52

Where was Dash-to-Panel installed from?
Gnome extension website

**Comment by charlesg99** [comment] 2023-03-12 14:58
Is this still an issue with the latest version? Can't reproduce that so far

**Comment by darkblaze69** [comment] 2023-03-12 15:49
Haven't experienced this problem for long time already

**Comment by charlesg99** [comment] 2023-03-12 16:56
Thanks, let's close this, we'll reopen if needed.

**Closed by charlesg99** 2023-03-12 16:56 UTC
Labels: bug

**Comment by Neubulae** [comment] 2024-07-12 10:01
I'm experiencing this for quite a while and I don't know how should I provide any information for this.
