### ISSUE TITLE
Intellihide with maximized windows

### ISSUE THREAD

**Issue by blackjackshellac** [home-sweet-gnome/dash-to-panel#619] opened 2019-04-17 14:08 UTC
I have my panel on top, with a window maximized the intellihide doesn't show the panel with the mouse.  Double clicking on the window title doesn't always restore the window, and clicking on the little max/restore icon at the top right of the window usually displays the panel instead of restoring the window.  The same is sometimes true of the close and minimize buttons.

I'm using version 19 from extensions.gnome.org

**Comment by charlesg99** [comment] 2019-04-17 21:01
Hello blackjackshellac! Never encountered any of those issues with intellihide... Could you please provide more information on your system (gnome-shell version, intellihide settings, xorg or wayland, your other extensions). Thanks!

**Comment by blackjackshellac** [comment] 2019-04-19 12:52
Hi Charles.  This is on Ubuntu 18.04 LTS,

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
$ gnome-shell --version
GNOME Shell 3.28.3
$ cd  ~/.local/share/gnome-shell/extensions
$ ls -1
alternate-tab@gnome-shell-extensions.gcampax.github.com
caffeine@patapon.info
dash-to-panel@jderose9.github.com
gnome-shell-screenshot@ttll.de
openweather-extension@jenslody.de
places-menu@gnome-shell-extensions.gcampax.github.com
Recents@leonardo.bartoli.gmail.com
touchpad-indicator@orangeshirt
user-theme@gnome-shell-extensions.gcampax.github.com
```

Intellihide options are reset to defaults.

**Comment by charlesg99** [comment] 2019-04-19 21:20
Can't reproduce on ubuntu 18.04 with your extensions and default intellihide settings. The panel correctly shows up over maximized windows. Does it happen with every window? Do you see errors in your gnome-shell logs? I would say that the double click and the max/restore issues are probably unrelated to dash to panel. Thanks!

**Comment by charlesg99** [comment] 2019-05-12 02:29
Closing for now, as I believe this is unrelated to dash to panel. I you can reproduce this issue on a vanilla gnome-shell installation, please let us know. Thanks!

**Closed by charlesg99** 2019-05-12 02:29 UTC
