### ISSUE TITLE
panel cuts off rounded corner of background when super key pressed

### ISSUE THREAD

**Issue by marcus13345** [home-sweet-gnome/dash-to-panel#1598] opened 2022-03-31 18:39 UTC
Im new to fedora / gnome, so im not sure what these things are called, but here is a screenshot of what i mean.

![image](https://user-images.githubusercontent.com/6365746/161126348-7aca677e-5fa2-4975-8c51-7f27194d7a52.png)

as you can see, when I press the super key, and the background moves inwards, a bit is cut off the bottom of the image, making the rounded corner look strange.

**Comment by birneee** [comment] 2022-04-02 23:08
Duplicate of https://github.com/home-sweet-gnome/dash-to-panel/issues/1355

**Comment by charlesg99** [comment] 2022-04-02 23:16
Thanks, this is now fixed on the master branch

**Closed by charlesg99** 2022-04-02 23:16 UTC

**Comment by marcus13345** [comment] 2022-04-02 23:19
@charlesg99 how long does it typically take for it to go from master branch to released in the extensions store?
