### ISSUE TITLE
postion is abnormal

### ISSUE THREAD

**Issue by onhao** [home-sweet-gnome/dash-to-panel#625] opened 2019-04-22 02:28 UTC
![image](https://user-images.githubusercontent.com/28284702/56479637-0d9c1080-64e9-11e9-8452-6026203d86e1.png)
Restart the computer or log in again, and it will become the case as shown above.
runing  Ubuntu 19.04
The current solution is to re-enable the plug-in and return to normal.
![image](https://user-images.githubusercontent.com/28284702/56479889-4092d400-64ea-11e9-96b6-3c96f8992225.png)

**Comment by charlesg99** [comment] 2019-04-23 02:43
Hello onhao, I can't reproduce this on Ubuntu 19.04. What dash to panel version are using? Do you see errors in your gnome-shell logs? Does it happens if you disable all of your extensions aside from dash to panel? My guess is that one of your other extensions runs into an error when disabling itself. Thanks!

**Comment by onhao** [comment] 2019-04-23 08:54
![image](https://user-images.githubusercontent.com/28284702/56567876-66060780-65e8-11e9-8fbe-f33be4d3d657.png)

**Comment by onhao** [comment] 2019-04-23 08:55
> Hello onhao, I can't reproduce this on Ubuntu 19.04. What dash to panel version are using? Do you see errors in your gnome-shell logs? Does it happens if you disable all of your extensions aside from dash to panel? My guess is that one of your other extensions runs into an error when disabling itself. Thanks!

JS ERROR: TypeError: actor is undefined
                                              findIndexForActor@resource:///org/gnome/shell/ui/layout.js:946:13
                                              findMonitorForActor@resource:///org/gnome/shell/ui/layout.js:958:42
                                              _getBoxPointerPreferredHeight@/home/wuhao/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:286:34
                                              enable/<@/home/wuhao/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:109:24

**Comment by onhao** [comment] 2019-04-23 10:03
Maybe it conflicts with this plug-in
'Dash to Dock'

**Comment by charlesg99** [comment] 2019-04-23 21:20
I tested with dash to dock and still can't reproduce. Could you please disable all extensions aside from dash to panel and see if it works? If so, you could then enable extensions one at a time and see which one is conflicting. Thanks!

**Comment by onhao** [comment] 2019-04-24 06:01
> I tested with dash to dock and still can't reproduce. Could you please disable all extensions aside from dash to panel and see if it works? If so, you could then enable extensions one at a time and see which one is conflicting. Thanks!

I'm test again  
this extensions Unite turn off The display is normal.

**Comment by charlesg99** [comment] 2019-04-24 18:12
Yes thank you, I could reproduce the issue with the Unite extension. Like dash to panel, Unite replaces the main panel's allocation, so whichever of the two extensions is loaded last will have its allocation respected, while the other one's will be ignored. 

When you manually re-enable dash to panel to "fix" it, you force dash to panel's allocation to take effect, which works fine. I'm gonna close this as it is an unilateral incompatibility and I would suggest to open an [Unite issue](https://github.com/hardpixel/unite-shell/issues), maybe they could accommodate both allocations if they detect that dash to panel was loaded prior to their initialization. 

Thanks!

**Closed by charlesg99** 2019-04-24 18:12 UTC
