### ISSUE TITLE
Support for Gnome 40 / Fedora 34

### ISSUE THREAD

**Issue by koa9** [home-sweet-gnome/dash-to-panel#1346] opened 2021-06-01 19:51 UTC
Getting support for Gnome 40 would be great.  

As of now I am unable to use dash to panel on Gnome 40.

**Comment by wshihdehx** [comment] 2021-06-02 12:47
Second this!

**Comment by koa9** [comment] 2021-06-02 12:50
@wshihdehx Try installing it from source. I managed to get it to work (at least for now). 
See more details here: 
https://github.com/home-sweet-gnome/dash-to-panel/issues/1345

**Comment by nekohayo** [comment] 2021-06-09 12:26
@koa9, please close this ticket as it is a duplicate of issue #1265.

**Closed** 2021-06-09 12:27 UTC
Labels: enhancement
