### ISSUE TITLE
Panel breaks after screen lock on multiple monitors.

### ISSUE THREAD

**Issue by ikogan** [home-sweet-gnome/dash-to-panel#623] opened 2019-04-21 21:31 UTC
Whenever I lock my screen the panel seems to get pushed down a few pixels onto the other monitor, throws some stack traces, and the app menu appears.

```
Apr 21 17:24:22 Chislobog gnome-shell[2748]: JS ERROR: TypeError: o.compareFn is not a function
                                             _recursiveApply@/home/kogan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js:256:16
                                             _applyStyles/this._rightBoxActorAddedID<@/home/kogan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js:205:21
                                             _addToPanelBox@resource:///org/gnome/shell/ui/panel.js:1144:9
                                             _updateBox@resource:///org/gnome/shell/ui/panel.js:1131:13
                                             _updatePanel@resource:///org/gnome/shell/ui/panel.js:1073:9
                                             _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                             _sync@resource:///org/gnome/shell/ui/sessionMode.js:204:9
                                             pushMode@resource:///org/gnome/shell/ui/sessionMode.js:166:9
                                             activate@resource:///org/gnome/shell/ui/screenShield.js:1272:17
                                             lock@resource:///org/gnome/shell/ui/screenShield.js:1321:9
                                             LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:380:9
                                             _handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:295:9
                                             _wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Apr 21 17:24:22 Chislobog gnome-shell[2748]: JS ERROR: TypeError: o.compareFn is not a function
                                             _recursiveApply@/home/kogan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js:256:16
                                             _applyStyles/this._rightBoxActorAddedID<@/home/kogan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js:205:21
                                             _addToPanelBox@resource:///org/gnome/shell/ui/panel.js:1144:9
                                             _updateBox@resource:///org/gnome/shell/ui/panel.js:1131:13
                                             _updatePanel@resource:///org/gnome/shell/ui/panel.js:1073:9
                                             _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                             _sync@resource:///org/gnome/shell/ui/sessionMode.js:204:9
                                             pushMode@resource:///org/gnome/shell/ui/sessionMode.js:166:9
                                             activate@resource:///org/gnome/shell/ui/screenShield.js:1272:17
                                             lock@resource:///org/gnome/shell/ui/screenShield.js:1321:9
                                             LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:380:9
                                             _handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:295:9
                                             _wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
Apr 21 17:24:22 Chislobog gnome-shell[2748]: JS ERROR: TypeError: o.compareFn is not a function
                                             _recursiveApply@/home/kogan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js:256:16
                                             _applyStyles/this._rightBoxActorAddedID<@/home/kogan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelStyle.js:205:21
                                             _addToPanelBox@resource:///org/gnome/shell/ui/panel.js:1144:9
                                             _updateBox@resource:///org/gnome/shell/ui/panel.js:1131:13
                                             _updatePanel@resource:///org/gnome/shell/ui/panel.js:1073:9
                                             _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                             _sync@resource:///org/gnome/shell/ui/sessionMode.js:204:9
                                             pushMode@resource:///org/gnome/shell/ui/sessionMode.js:166:9
                                             activate@resource:///org/gnome/shell/ui/screenShield.js:1272:17
                                             lock@resource:///org/gnome/shell/ui/screenShield.js:1321:9
                                             LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:380:9
                                             _handleMethodCall@resource:///org/gnome/gjs/modules/overrides/Gio.js:295:9
                                             _wrapJSObject/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:326:16
```

![Screenshot from 2019-04-21 17-30-19](https://user-images.githubusercontent.com/1840337/56475777-2bbb2f80-645b-11e9-9a51-5028211d3e52.png)

I just upgraded to Ubuntu 19.04 with Gnome 3.32.0. I wasn't using Gnome Shell previously due to performance but have used Dash To Panel with this configuration in the past.

**Comment by charlesg99** [comment] 2019-04-23 02:32
Hello ikogan, thank you for the report. I can't reproduce it so far on ubuntu 19.04 xorg or wayland. Seems like it happens when an item is added to the right part of the panel, could you please tell us the extensions you're using? Thanks!

**Comment by ikogan** [comment] 2019-04-26 23:16
So I can't replicate this anymore today. I'm using the same set of extensions today as yesterday... I'm not sure what changed. I did multiple reboots yesterday.

**Comment by charlesg99** [comment] 2019-04-27 14:26
Maybe an update happened? Let us know if this re-surface again, but for now I'll close this. Thanks!

**Closed by charlesg99** 2019-04-27 14:26 UTC
