### ISSUE TITLE
v35 crops panel

### ISSUE THREAD

**Issue by mrjavum** [home-sweet-gnome/dash-to-panel#957] opened 2020-04-13 14:41 UTC
v35 crops bottom of the panel with Ant-slim or Flat-Remix gnome-shell theme:

v34
![image](https://user-images.githubusercontent.com/977334/79129261-1b6c3500-7dcf-11ea-9119-6e619744b6dd.png)

v35
![image](https://user-images.githubusercontent.com/977334/79129285-24f59d00-7dcf-11ea-9efb-198ca8cb0df3.png)

My Linux distribution is Arch Linux
Linux archie 5.6.2-arch1-2 #1 SMP PREEMPT Sun, 05 Apr 2020 05:13:14 +0000 x86_64 GNU/Linux

with Gnome 3.36.1

**Comment by charlesg99** [comment] 2020-04-13 17:04
Hello mrjavum, thank you for reporting this, I could reproduce the issue. So sorry, I always forget about the flat-remix theme when testing :cry: It should now be fixed on the master branch, could you please [install it](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) to confirm that it works for you as well? Thanks!

@daniruiz

**Comment by mrjavum** [comment] 2020-04-14 13:14
Hello!
The latest master does not fix the problem :(

**Comment by charlesg99** [comment] 2020-04-14 15:13
Hello, are you sure you're on the latest version (see highlight in the screenshot)? Mine looks like this with Flat-Remix:

![image](https://user-images.githubusercontent.com/33044886/79241257-d08b0580-7e40-11ea-8bff-e450312b6a97.png)

Thanks!

**Comment by mrjavum** [comment] 2020-04-14 16:29
Yes, you are right! My problem was to run `make` and then `make install` and it's not the same as just `make install`.

Thank you for your help and such superior extension!

**Comment by charlesg99** [comment] 2020-04-14 17:30
Great, thanks!

**Closed by charlesg99** 2020-04-14 17:30 UTC
Labels: bug
