### ISSUE TITLE
Issue #310 appearing again; Lag after moving mouse rapidly over app icons

### ISSUE THREAD

**Issue by lckjosh** [home-sweet-gnome/dash-to-panel#317] opened 2018-01-26 12:12 UTC
Sadly I experience this again, whole system animations and even glxgears start to become choppy. However, disabling window previews on hovering over icons seems to fix the issue.

**Comment by lckjosh** [comment] 2018-01-26 13:25
Also, can I add a feature suggestion, which is to add "show window previews" as an opton under "click action"? That would essentially solve the problem for me personally.

**Comment by charlesg99** [comment] 2018-01-26 13:33
Could you please provide your distro/gnome-shell version? Also, for it to happen, does the window preview popup menu needs to appear or do you only have to move the mouse rapidly over the icons? I would like to try to fix that, but I can't reproduce it here (arch, gnome-shell 3.26.2). Thanks

**Comment by lckjosh** [comment] 2018-01-26 14:36
Sure. Here are my system specs too, just in case.
OS: Ubuntu 17.10
Gnome 3.26.2
CPU: i3-4170
GPU: Radeon R7 250
RAM: 8GB DDR3

I think the window has to appear, it will anyway when I move my mouse over the icons. The choppy animations don't appear immediately though, it gets worse over time. 

Here's a video showing the difference between the smooth and choppy animations: https://youtu.be/nMNmI0XgWC4

**Comment by lckjosh** [comment] 2018-01-31 06:12
Update: It seems like this issue has been reported before in issue #186 
A recent reddit thread [https://www.reddit.com/r/gnome/comments/7teono/possible_fix_to_improve_gnome_lag/](url) has also mentioned this.

**Comment by notresponding123** [comment] 2018-02-20 09:22
while using a service for your any device, if they don't respond or don't work, then you can visit this site to get an insant technical support [window taskbar fix](https://notresponding.net/windows-taskbar-fix/)

**Comment by LiamDawe** [comment] 2018-03-12 15:54
I've been experience a really "laggy" system for the last few days, disabled Dash to Panel and suddenly it's golden again.

Something in the extension is causing huge system slowdowns for me.

**Comment by charlesg99** [comment] 2018-03-13 20:30
@LiamDawe Do you experience the same problem as Ickjosh (slow down over time with the window previews enabled)? When you see the lag, what is the gnome-shell process cpu usage like? Could you also please provide some more information on your system? Dash to panel settings, distro, system specs, gnome-shell version, xorg or wayland. Thanks

**Comment by TechnoSparks** [comment] 2018-03-16 02:03
I used to also have this lag overtime that I even decided to distro hop to Budgie. However, the change was not feasible and I had to come back to Gnome. Gnome and Dash to Panel really rocks. I didn't think that Dash to Panel was the reason behind the lag, but I will definitely keep an eye to see this. Will report findings later since I was just clean reinstalled my distro.

Also, i would also vouch for the suggestion in the second post. Would be better if window previews could be disabled but only leave text items to click on.

**Comment by charlesg99** [comment] 2018-03-16 03:39
Hey @TechnoSparks, sounds good, I really would love to be able to reproduce it reliably. I'm using

**Comment by TechnoSparks** [comment] 2018-03-17 20:43
I see @charlesg99 . But I have a very contradicting finding here.

Unfortunately, disabling window previews for Dash to Panel is not the cause of the lag, so my issue is completely unrelated with this specific GitHub issue…

I have also disabled window previews in ALT TAB switcher by modifying options for Alternate Tab extension to see if it was to blame. However, the answer is “no” too.

As to the true cause of the “over time” lag, that is still a mystery. I have tried to disable one extension at a time to see the offending extension (except Dash to Panel. Will do it after a test that I will explain in the next sentence) — but those extensions are not to blame. If anyone wants to hear something positive, I have disabled Dash to Panel’s “Show AppMenu Button” and “Application Menu” in Tweak Tools. I am currently experiencing no “over time” lag, **but** it is still too early to say so. I need more time (possibly days) to confirm if this may be the cause to _my_ lag.

I’d suggest other affected participants of this issue to try the same.

**Comment by charlesg99** [comment] 2018-03-18 20:01
@TechnoSparks When you say "over time", are you talking minutes or hours? Thanks

**Comment by TechnoSparks** [comment] 2018-03-19 00:35
@charlesg99 I need to use the desktop productively and then the issue will appear roughly after 30-40 minutes. If i instead leave the machine idling, the lag doesn’t happen.

-------

Disabling AppMenu seemed to not fixing it. I have now disabled launching and switching animations under “Fine Tune” tab of Dash to Panel settings.

I am preparing to use Gnome without Dash to Panel as a final experiment, if and only if my previous test yield a negative result.

**Comment by TechnoSparks** [comment] 2018-03-24 01:41
Seems to be an issue of Gnome after all. In light of [this post](https://www.omgubuntu.co.uk/2018/03/gnome-shell-has-a-memory-leak-and-it-might-not-be-fixed-for-ubuntu-18-04-lts) which now publicised the shell lag issue.

**Comment by TechnoSparks** [comment] 2018-08-10 09:08
Hello I am back to report that yes, the original description of the issue is the true replication method. @charlesg99 
Animations started to stutter after moving my cursor on the favourite (running) icons on the panel. I moved the cursor quite fast, but not too fast so that the window preview may appear briefly.

Unique to me however, the stutter decreases after a while, but still retain a little bit of stutter. I dont know if this relates to my issue ranted above, as I will test that out later and will create a new Issue if required.

**Comment by TechnoSparks** [comment] 2018-08-19 01:11
I can now confirm the source of the stuttering is caused by "Show window previews on hover".

**Comment by sgmihai** [comment] 2018-08-19 14:02
Can confirm the same. Turning off window previews fixes the lag. Randomly turning on/off extensions temporarily fiexes it, for some while. This has been bugging me for 3 days since I installed the extension.
Manjaro Linux, Kernel 4.18, Vega 64, Gnome 3.28.3/Wayland.
Please fix so this wonderful extension can be perfect.

**Comment by TechnoSparks** [comment] 2018-09-09 12:47
@sgmihai do you use an SSD?

**Comment by sgmihai** [comment] 2018-09-09 12:58
@TechnoSparks  yes I do, Samsung NVME

**Comment by TechnoSparks** [comment] 2018-09-09 13:05
@sgmihai Hm. I just upgraded to Sandisk Ultra, although SATA link. The problem seemed to be have gone (I tried to replicate the bug), but I also have updated to v16. Have you also updated?

**Comment by TechnoSparks** [comment] 2018-09-09 13:12
My theory is that Dash to Panel may have an aggressive caching of the window thumbnails, thus may explain why this stuttering appears after a while and not instantaneously. Although I can read `js`, I unfortunately cannot _read_ Gnome extension. I think, if we could provide a way to disable window thumbnail (just show text like windows do if thumbnails disabled), this could be a great workaround for us unfortunates who have this animation stutters.

**Comment by jderose9** [comment] 2018-09-10 14:37
@TechnoSparks You may disable window previews by turning off `Show window previews on hover` on the Behavior tab of the settings.

I certainly have interest in resolving this problem, but it is not clear to me what is causing the problem, and I have never been able to reproduce it, on a variety of hardware and Virtual Machine settings.

Still, if you are willing to test, I can attempt different strategies for creating/cleaning up the live preview, or possibly using a static snapshot of the window rather than a live preview, and see if you have any improvement.

Thanks!

**Comment by TechnoSparks** [comment] 2018-09-10 21:17
@jderose9 Yes, I have disabled it for so long. Just that sometimes I enable it for the sake of trying to track the true cause of the animation stutter. Of course, as of now, still no avail…

I am definitely interested and willing to test anything that you can come up with.

Oh, I need to emphasise on one particular behaviour of the panel: To make the animation stutter come earlier, one need to hover the active tasks' icons on the panel until the preview appears, then proceed to another icon, back and forth. The more the apps running and you did this, the quicker the issue appears.

Completely speculative: it could be that each hover spawns a listener(?) that updates based on the window state, and if hovered repeatedly, duplicate numbers of listeners exists and bring down the performance of the shell. (whew that is weird speculation, but hey, I am trying my best 😅)

Anyway, I am really interested in testing. Just reply to this issue and I will be right on my way!

**Comment by TechnoSparks** [comment] 2018-10-13 21:02
Issue disappeared in Gnome 3.30. Could be upstream issue after all?

**Comment by charlesg99** [comment] 2019-06-24 13:17
Hello, closing for now as the issue is related to the previous window previews. Please install the latest master and reopen the issue if the lag persists with the new version of the previews! Thanks!

**Closed by charlesg99** 2019-06-24 13:17 UTC
Labels: bug
