### ISSUE TITLE
[Feature Request] Separate panel to act like window list

### ISSUE THREAD

**Issue by yar05** [home-sweet-gnome/dash-to-panel#487] opened 2018-10-28 13:13 UTC
Hi, I love your latest devel version ! You should definitely place some donate button !

Is there any way to move window list to separate panel on the same screen ? 

I would love to have the main panel on top but to move window list on the bottom like with window list extension. 

Thanks,

**Comment by jderose9** [comment] 2018-10-28 15:35
Hi @yar05 ! Would it be suitable to use the window list extension in conjunction with this one?

https://extensions.gnome.org/extension/602/window-list/

**Comment by yar05** [comment] 2018-10-28 15:39
I was using it yes, it is very suitable however I need to theme it with every update :| 
If there would be a fork of window list that follows the same theme as dash to panel then I'm sorted.

**Comment by yar05** [comment] 2018-10-28 15:56
If I could have runningApps = this._getRunningApps().sort(this.sortAppsCompareFunction); in second panel that I can move to the bottom of the screen and then disable runningApps in the top one would be a blast !

**Comment by charlesg99** [comment] 2018-10-28 16:31
Hi, I just added a similar setting to keep the original dash in the overview and I'm thinking that I could add another one to keep gnome-shell top panel. We could just create another "secondary" panel on the primary monitor and leave the top panel untouched.

I see the following adjustments that would need to be dealt with if the top panel is present:

- If the user puts the dash to panel on top, our panel position would need to be modified to go under the top panel. That might look weird :) We could also simply disable this option if the dash to panel at the top.
- The option to select where to display the "primary panel" in a multi-monitors configuration would need to affect the top panel instead of our panel.

@jderose9 do you see anything else? Do you think it is a good idea? There has been another request to this effect not long ago #459.

Thanks!

**Comment by jderose9** [comment] 2018-10-28 16:47
I'm fine with the change, and I can't think of any other issues. I would probably force dash-to-panel to the bottom OR put the gnome panel at the opposite, rather than attempting to stack them.

In terms of the settings layout I want to make sure we don't lose the primary goal of being an integrated taskbar, so any settings around this should probably not be too front and center so as to confuse those users.

**Comment by charlesg99** [comment] 2018-10-28 18:48
I tried to fiddle with this and I quickly got both the top panel and our panel on the primary screen, but I also realized that to bring this feature up to standard, it would require much work (intellihide, transparency, panelGhost, allocation, etc.). 

As @jderose9 said, since the primary goal is being an integrated taskbar, I don't think it is worth spending more time on this, sorry. I've pushed my initial work on a new branch "keep-gs-top-panel" if anyone would like to take over. I'm gonna close this because this is a duplicate of 459. Thanks!

**Closed by charlesg99** 2018-10-28 18:48 UTC

**Comment by yar05** [comment] 2018-10-28 19:01
I've tried cloning this into separate extension, I've changed names : dash-to-panel and dashtopanel with all of its variations upper case etc, recompiled the schema.

I can lunch the extension and it shows separate panel but for some reason changing  settings in one changes them in the other. 
Do you guys have any pointers ? I would just run copy of this extension but at the bottom leaving only window list ... 

Any help would be appreciated

**Comment by charlesg99** [comment] 2018-10-28 19:17
Not sure if this is gonna work, but for the settings you will need to change every reference to `org.gnome.shell.extensions.dash-to-panel` or `/org/gnome/shell/extensions/dash-to-panel/`. You'll also need to rebuild the extension so it uses your new schema (after modifying `Convenience.getSettings('org.gnome.shell.extensions.dash-to-panel')`). 

You could also try the branch "keep-gs-top-panel" that I just pushed, I think it would be easier and maybe it will suit your needs (even though it isn't complete). Thanks!

**Comment by yar05** [comment] 2018-10-28 19:19
I'm trying 
find . -type f -print0 | xargs -0 sed -i 's/DashToPanel/DashToWindow/g'
find . -type f -print0 | xargs -0 sed -i 's/dashtopanel/dashtowindow/g'
find . -type f -print0 | xargs -0 sed -i 's/dash-to-panel/dash-to-window/g'
find . -type f -print0 | xargs -0 sed -i 's/Dash-To-Panel/Dash-To-Window/g'
find . -type f -print0 | xargs -0 sed -i 's/Dash-to-Panel/Dash-to-Window/g' 

Then replacing svg and png names containing dash-to-panel etc. 

I've tried the keep-gs-top-panel branch but with that It disappears entirely.
The GS top panel comes back but there is no your extension visible.

**Comment by yar05** [comment] 2018-10-28 19:35
With keep-gs-top-panel  I get : 


Oct 28 19:32:45 thinkH gnome-shell[30304]: Extension "dash-to-panel@jderose9.github.com" had error: TypeError: panelManager is null
Oct 28 19:32:45 thinkH gnome-software[31386]: dash-to-panel_jderose9.github.com has error: TypeError: panelManager is null

**Comment by charlesg99** [comment] 2018-10-28 21:42
> I'm trying
> find . -type f -print0 | xargs -0 sed -i 's/DashToPanel/DashToWindow/g'
> find . -type f -print0 | xargs -0 sed -i 's/dashtopanel/dashtowindow/g'
> find . -type f -print0 | xargs -0 sed -i 's/dash-to-panel/dash-to-window/g'
> find . -type f -print0 | xargs -0 sed -i 's/Dash-To-Panel/Dash-To-Window/g'
> find . -type f -print0 | xargs -0 sed -i 's/Dash-to-Panel/Dash-to-Window/g'

Please read my previous message.


> With keep-gs-top-panel I get :
> 
> Oct 28 19:36:45 thinkH gnome-shell[30304]: Extension "[dash-to-panel@jderose9.github.com](mailto:dash-to-panel@jderose9.github.com)" had error: TypeError: panelManager is undefined
> Oct 28 19:36:45 thinkH gnome-software[31386]: dash-to-panel_jderose9.github.com has error: TypeError: panelManager is undefined
> 
> BTW, same issue is with the master branch. Issue disappears when cloning the tag v16

Not sure how you end up with this error on the branch or the latest master. Did you correctly `make install` then restart gnome-shell? What distro/gnome-shell version are you on? Thanks!

**Comment by yar05** [comment] 2018-10-28 21:46
Yes exactly. 

Must be to do with https://github.com/home-sweet-gnome/dash-to-panel/commit/aa5f7a47e2602e858c1cbd8c5ab4efa96c31cd28 


Ubuntu 18.10 GNOME Shell 3.30.1

**Comment by charlesg99** [comment] 2018-10-28 22:20
Yes, thank you for the report! It should be fixed now on master.
