### ISSUE TITLE
Add option to behave as a dock - to not extend to the edges of the screen

### ISSUE THREAD

**Issue by matfantinel** [home-sweet-gnome/dash-to-panel#1049] opened 2020-06-17 14:48 UTC
**Describe the idea or feature you'd like**
I'd like to be able to use Dash to Panel as a dock that doesn't extend to the edges of the screen. With the recent addition of the option to keep GNOME's original top bar, I've grown to like keeping it since it provides a more consistent experience. However, since the topbar contains the time and indicators, there's no reason to keep the panel spanning the entire screen. Dash to Dock currently has a similar option, where you can select if you want the dock to span the entire screen or not.

Why not use Dash to Dock instead? Because Dash to Panel has more features that I rely on, like the amazing window previous and ungrouping apps. It's also more reliable and customizable.

**Additional context**
For reference, the current setup I could achieve:

![image](https://user-images.githubusercontent.com/24247035/84913029-71d84700-b090-11ea-880a-25363c2cb0b0.png)

Ideally, I would like the background to also be centered, like the apps, instead of reaching the edges of the screen. It's important too that Intellihide considers this change in size, so if I put the mouse on the bottom left corner, for example, it doesn't trigger the display of the panel.

**Comment by charlesg99** [comment] 2020-06-17 23:24
Hello matfantinel, sounds like a duplicate of #726. Also, I'm not sure I agree with the intellihide part, as in your case the size of the dock would be dynamic. Seems to me that it would be quite confusing to have the "triggering area" changing every time an app opens/closes (especially with ungrouped applications). What do you think?

Nice wallpaper btw!

**Comment by matfantinel** [comment] 2020-06-18 00:31
Really seems like a duplicate, I searched but didn't find that one before, sorry.

About the triggering area, I don't think it would be confusing. Since the dock would be centered, that's where the user would drag the mouse to bring it up (usually at the center of the dock/screen, not at the edges of the dock).
 It seems to me that dragging the mouse to the edge of the monitor bringing a dock in the center would be more confusing. Iirc, dash to dock and Plank only toggle autohide inside the dock width.

**Comment by charlesg99** [comment] 2020-06-18 11:56
Not sure about Plank, but I don't think this is accurate for Dash to Dock, as the dock is revealed when approaching any part of the edge of the monitor, no matter what size the dock has.

![Peek 2020-06-18 07-50](https://user-images.githubusercontent.com/33044886/85016996-c0d9b700-b138-11ea-8612-cb2e9c2dcaca.gif)

Let's close this one in favor of the previous issue, thanks!

**Closed by charlesg99** 2020-06-18 11:56 UTC
Labels: enhancement
