### ISSUE TITLE
Shell crashes when switching running applications via the panel

### ISSUE THREAD

**Issue by williamd5** [home-sweet-gnome/dash-to-panel#1664] opened 2022-05-14 11:27 UTC
**Describe the bug**
When clicking on icons of running apps on the panel, gnome shell appears to crash and I am sent back to the login screen.
**Linux distribution and version**
Ubuntu 22.04 LTS
**GNOME Shell version**
42.0

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Steps to reproduce**
1. Run Ubuntu 22.04 with Gnome 42 and only Dash to Panel enabled
2. Open any two applications (will be called A and B)
3. Click the icon of application A, then the icon of app B
4. Repeat step 3 roughly 3-5 times
5. The system freezes for a second. A black screen with `_` symbol appears; shortly after the gnome login screen appears.

**Comment by obriand1** [comment] 2022-05-21 12:45
I have the same problem with Manjaro stable channel (same GNOME & extension versions )

**Comment by charlesg99** [comment] 2022-05-26 12:56
I can't reproduce this on Ubuntu 22.04

**Comment by williamd5** [comment] 2022-06-07 14:21
journalctl at time of crash
```
Jun 07 17:16:39 razer gnome-shell[1320]: GNOME Shell crashed with signal 11
Jun 07 17:16:39 razer gnome-shell[1320]: == Stack trace for context 0x5580334a24b0 ==
Jun 07 17:16:40 razer gnome-shell[5521]: (EE) failed to read Wayland events: Broken pipe
Jun 07 17:16:40 razer firefox[5757]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer gsd-media-keys[2730]: # Error reading events from display: Broken pipe
Jun 07 17:16:40 razer gjs[6867]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer update-notifier[2847]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer xdg-desktop-por[1947]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer unknown[1605]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer unknown[1606]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer evolution-alarm[1678]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer unknown[1608]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer unknown[1620]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer unknown[1599]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer unknown[2741]: Error reading events from display: Connection reset by peer
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.MediaKeys.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Keyboard.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Wacom.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Power.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer gjs[2054]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Power.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: vte-spawn-72d846f0-a274-4ba0-ab70-3d8361ad0fbc.scope: Consumed 4.883s CPU time.
Jun 07 17:16:40 razer systemd[1203]: gnome-terminal-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: gnome-terminal-server.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: gnome-terminal-server.service: Consumed 15.728s CPU time.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Keyboard.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Color.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.MediaKeys.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Wacom.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: app-gnome-update\x2dnotifier-2847.scope: Consumed 45.660s CPU time.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.SettingsDaemon.Color.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.Shell@wayland.service: Main process exited, code=dumped, status=11/SEGV
Jun 07 17:16:40 razer xdg-desktop-por[1858]: Error reading events from display: Broken pipe
Jun 07 17:16:40 razer systemd[1203]: snap.snap-store.ubuntu-software.1ebf6a65-f412-404b-9c56-125a22739902.scope: Consumed 8.430s CPU time.
Jun 07 17:16:40 razer systemd[1203]: xdg-desktop-portal-gnome.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 17:16:40 razer systemd[1203]: xdg-desktop-portal-gnome.service: Failed with result 'exit-code'.
Jun 07 17:16:40 razer gnome-shell[5520]: X connection to :0 broken (explicit kill or server shutdown).
Jun 07 17:16:40 razer gnome-shell[5520]: Select the window whose client you wish to kill with button 1....
Jun 07 17:16:40 razer pulseaudio[1212]: X11 I/O error handler called
Jun 07 17:16:40 razer pulseaudio[1212]: X11 I/O error exit handler called, preparing to tear down X11 modules
Jun 07 17:16:40 razer systemd[1203]: org.gnome.Shell@wayland.service: Failed with result 'core-dump'.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.Shell@wayland.service: Triggering OnFailure= dependencies.
Jun 07 17:16:40 razer systemd[1203]: org.gnome.Shell@wayland.service: Consumed 1min 3.096s CPU time.
Jun 07 17:16:40 razer systemd[1203]: Stopped target GNOME Wayland Session (session: ubuntu).
Jun 07 17:16:40 razer systemd[1203]: Stopped target Current graphical user session.
Jun 07 17:16:40 razer firefox.desktop[6554]: Exiting due to channel error.
Jun 07 17:16:40 razer firefox.desktop[6408]: Exiting due to channel error.
Jun 07 17:16:40 razer firefox.desktop[6355]: Exiting due to channel error.
Jun 07 17:16:40 razer firefox.desktop[6515]: Exiting due to channel error.
Jun 07 17:16:40 razer firefox.desktop[6045]: Exiting due to channel error.
Jun 07 17:16:40 razer firefox.desktop[5969]: Exiting due to channel error.
Jun 07 17:16:40 razer firefox.desktop[7628]: Exiting due to channel error.
```

**Comment by williamd5** [comment] 2022-06-07 14:33
Here is a log generated by following:
1. Restart system
2. Quickly trigger the bug
3. Restart system after shell crashes
4. `journalctl -b-1 > prevboot.txt`
[prevboot.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/8854104/prevboot.txt)

**Comment by williamd5** [comment] 2022-06-25 12:00
Appears to be fixed in version 50

**Comment by williamd5** [comment] 2022-06-25 12:21
Nevermind. Shell still crashes.

On fresh boot, I am immediately logged out upon trying to launch an app via the panel.

**Comment by charlesg99** [comment] 2022-10-15 13:16
Please install the latest master

**Comment by williamd5** [comment] 2022-10-18 15:05
> Please install the latest master

I installed from source at 94e7be214f07dd5197818cc14ad84c5961f1f9e0 (latest master, as suggested) and can still reproduce this problem.

Even by simply clicking the same icon (to toggle open/minimise) quickly a few times this issue occurs within seconds.

**Comment by williamd5** [comment] 2022-10-18 15:13
I reset my configuration with `dconf reset -f /org/gnome/shell/extensions/dash-to-panel/` and upgraded `zlib1g` (due to an error report, not sure if related) and it seems like that resolved the issue.

I exported my config before resetting, if that is of any use.
[dtp-conf.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/9811943/dtp-conf.txt)

**Comment by charlesg99** [comment] 2022-10-18 15:16
Does the issue return if you re import your settings?

**Comment by charlesg99** [comment] 2023-02-11 15:55
Should be fixed on master

**Closed** 2023-03-12 14:37 UTC
Labels: bug
