### ISSUE TITLE
GNOME 42 Support

### ISSUE THREAD

**Issue by hf29h8sh321** [home-sweet-gnome/dash-to-panel#1581] opened 2022-02-24 02:10 UTC

**Comment by freddyw** [comment] 2022-02-25 19:44
The panel worked on gnome 42 alpha, but after an update to gnome 42 beta ( gnome-shell-42~beta-2.fc36.x86_64 to be exact) the panel is not working and this error appears in the journal: 
Object 0x14b6bd21bbb8 is not a subclass of GObject_Object, it's a Object
So I guess it needs a bit of work for the upcoming Gnome 42. Wish I had the knowledge to fix is myself.

**Comment by miigotu** [comment] 2022-03-03 05:22
```
Mar 02 23:43:02 RAIDER gnome-shell[2304]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: GObject_Object.prototype.[__GObject__hook_up_vfunc] called on incompatible Object
                                          hookVfunc@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:350:39
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:84:15
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:269:23
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:123:18
                                          hookVfunc@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:350:39
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:84:15
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:269:23
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:123:18
                                          _enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:86:20
                                          enable/extensionChangedHandler<@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:58:13
Mar 03 00:02:24 RAIDER gnome-shell[11581]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x2cfbdce1ee48 is not a subclass of GObject_Object, it's a Object
                                           _createPanel@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:404:18
                                           enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
                                           _enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:106:18
                                           enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
Mar 03 00:18:15 RAIDER gnome-shell[2303]: JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x1a4460d9688 is not a subclass of GObject_Object, it's a Object
                                          _createPanel@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:404:18
                                          enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
                                          _enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:106:18
                                          enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
                                          hookVfunc@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:350:39
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/overview.js:84:15
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:269:23
                                          disable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:123:18
                                          _enable@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:86:20
                                          enable/extensionChangedHandler<@/home/miigotu/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:58:13
```

**Comment by miigotu** [comment] 2022-03-03 05:28
```
st_widget_get_theme_node called on the widget [0x55a5d1a78200 Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock.bottom dashtodock autohide:insensitive "dashtodockContainer"] which is not in the stage.
Spurious clutter_actor_allocate called for actor 0x55a5d1a78200/<dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55a5d1a78200] which isn't a descendent of the stage!
Spurious clutter_actor_allocate called for actor 0x55a5d1a78200/<dashtodockContainer>[<Gjs_ubuntu-dock_ubuntu_com_docking_DashToDock>:0x55a5d1a78200] which isn't a descendent of the stage!
JS ERROR: Impossible to enumerate trash children: TypeError: this.location is null
_updateTrash@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:654:40
async*_init@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:597:14
LocationAppInfo@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:95:4
TrashAppInfo@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:564:1
_ensureApp@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1085:22
getApp@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1091:14
wrapFileManagerApp@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:1035:22
_ensureLocations@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1694:50
DashToDock_DockManager@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1592:14
conditionallyenabledock@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js:52:23
enable@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js:27:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:350:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:596:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:571:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:605:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:636:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:268:22
start@resource:///org/gnome/shell/ui/main.js:165:5
@resource:///org/gnome/shell/ui/init.js:6:17
```

**Comment by miigotu** [comment] 2022-03-03 17:53
Ha, I posted the wrong error log here anyway, they are similar errors. Fwiw installing dash-to-dock from source worked, so maybe the fix is seen in their recent git history.

**Comment by crosser** [comment] 2022-03-03 18:57
FWIW I started to get the same error on jammy with gnome-shell from the distro: `ii  gnome-shell                                   41.3-1ubuntu1`, when I try to use `dash-to-panel` from the distro (45-1) _or_ locally built from the current master likewise.
It makes me suspect that it it triggered by an upgrade of some library (libglib?)

**Comment by philippun1** [comment] 2022-03-03 19:02
I also have the same error on the latest jammy build with gnome-shell 41.3. Probably since the upgrade to gjs 71.1.
My spontaneous guess would be the Utils.defineClass method is no longer compatible with the latest gjs version?

**Comment by miigotu** [comment] 2022-03-03 22:39
> FWIW I started to get the same error on jammy with gnome-shell from the distro: `ii  gnome-shell                                   41.3-1ubuntu1`, when I try to use `dash-to-panel` from the distro (45-1) _or_ locally built from the current master likewise.
> It makes me suspect that it it triggered by an upgrade of some library (libglib?)

I'm in jammy also.

**Comment by irenegr** [comment] 2022-03-04 17:44
Same problem, gnome-shell version 41.3, gnome version 42.beta (jammy)

**Comment by thuandt** [comment] 2022-03-05 08:24
Ubuntu 22.04 and have same issue :)

**Comment by fcole90** [comment] 2022-03-05 12:04
On Ubuntu 22.04, I get the following:
```
JS ERROR: Extension dash-to-panel@jderose9.github.com: TypeError: Object 0x2834251a0878 is not a subclass of GObject_Object, it's a Object
_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:61:14
_createPanel@/home/fabio/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:404:18
enable@/home/fabio/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panelManager.js:84:34
_enable@/home/fabio/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:106:18
enable@/home/fabio/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:66:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:350:26
_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:283:35
Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:136:41
Caused by: Error: This JS object wrapper isn't wrapping a GObject. If this is a custom subclass, are you sure you chained up to the parent _init properly?
```

**Comment by fcole90** [comment] 2022-03-05 12:17
Just compiled from source, same issue.

**Comment by fcole90** [comment] 2022-03-05 12:20
Is there any resource with the list of changes? :blush:

**Comment by miigotu** [comment] 2022-03-08 19:58
This is the patch that caused this, in gjs:
https://mail.gnome.org/archives/commits-list/2019-September/msg00008.html

**Comment by miigotu** [comment] 2022-03-09 03:19
Anyone else not have a top bar anymore? So annoying since the update all my indicators and time missing smh

**Comment by Larx** [comment] 2022-03-09 04:07
In Ubuntu 22.04, try disabling (!) extensions. This works for me to get at least the top panel back.

**Comment by bakuii** [comment] 2022-03-11 12:04
I also have the same error on the latest jammy build with gnome-shell 41.3. I follow philippun1 hint about downgrading gjs. 
I downgrade gjs to 1.70.1-1 and this error gone.

**Comment by crosser** [comment] 2022-03-11 12:46
JFYI, I filed a launchpad but for jammy: https://bugs.launchpad.net/gnome-shell-extension-dash-to-panel/+bug/1964593

**Comment by jhpratt** [comment] 2022-03-15 22:11
Anything someone (me) who has never touched gnome extensions can do to help?

**Comment by crab2313** [comment] 2022-03-16 10:43
Hi guys, I have fixed it myself based on @philippun1's prior work.


[gnome42.tar.gz](https://github.com/home-sweet-gnome/dash-to-panel/files/8261325/gnome42.tar.gz)

**Comment by crosser** [comment] 2022-03-16 11:23
@crab2313 does it continue to work with gnome 41? If yes, should it be `"shell-version": [ "41", "42" ],` in `metadata.json`?

I am going to test your patches momentarily

**Comment by crab2313** [comment] 2022-03-16 11:24
> @crab2313 does it continue to work with gnome 41? If yes, should it be `"shell-version": [ "41", "42" ],` in `metadata.json`?
> 
> I am going to test your patches momentarily

I think the difference is about gjs.

**Comment by crosser** [comment] 2022-03-16 11:36
Aand it works for me! (In jammy source package, I've put the patches into `debian/patches` and rebuilt, as simple as that.)

Thanks a lot @crab2313 for your effort!

Any chance to make this into an PR?

**Comment by nexryai** [comment] 2022-03-16 12:50
> Hi guys, I have fixed it myself based on @philippun1's prior work.
> 
> [gnome42.tar.gz](https://github.com/home-sweet-gnome/dash-to-panel/files/8261325/gnome42.tar.gz)

Excellent!!! This patch worked perfectly in my environment (openSUSE Tumbleweed + Gnome42 RC).

**Comment by nename0** [comment] 2022-03-16 12:56
Does not work for me on jammy.
I get: `proto[Gi.gobject_prototype_symbol] is undefined`

**Comment by miigotu** [comment] 2022-03-16 13:18
> @crab2313 does it continue to work with gnome 41? If yes, should it be `"shell-version": [ "41", "42" ],` in `metadata.json`?
> 
> I am going to test your patches momentarily

Does that include 42.beta?

**Comment by crosser** [comment] 2022-03-16 14:36
IIRC right click on panel icons was broken some time before the extension stopped to load.

It is annoying, but probably a matter for a separate ticket.

**Comment by crab2313** [comment] 2022-03-16 15:49
Confirmed. Please try the new patch set below.

[gnome42-v2.tar.gz](https://github.com/home-sweet-gnome/dash-to-panel/files/8264895/gnome42-v2.tar.gz)


> ![Screenshot from 2022-03-16 15-40-14](https://user-images.githubusercontent.com/1404921/158615684-0fa80b20-4e43-40b8-91cb-2ae035755c76.png) IIRC right click on panel icons was broken some time before the extension stopped to load.
> 
> It is annoying, but probably a matter for a separate ticket.
> 
> Edit: I confirm that the panel is broken after locking and unlocking

**Comment by crab2313** [comment] 2022-03-16 16:05
The issue of right clicking seems to be caused by this error.

```
Mar 16 23:53:18 yoga14s gnome-shell[91650]: JS ERROR: TypeError: super[func] is not a function
                                            callParent@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 94 > eval:1:199
                                            _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1463:14
                                            C@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js line 94 > eval:1:46
                                            popupMenu@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:645:26
                                            vfunc_button_press_event@resource:///org/gnome/shell/ui/appDisplay.js:3146:18
```

**Comment by crosser** [comment] 2022-03-16 18:04
> Confirmed. Please try the new patch set below.
> 
> [gnome42-v2.tar.gz](https://github.com/home-sweet-gnome/dash-to-panel/files/8264895/gnome42-v2.tar.gz)

Works for me (not broken after lock now). :+1:

**Comment by hf29h8sh321** [comment] 2022-03-16 18:21
@crab2313 There's an issue I'm experiencing. If I hover over something on the panel, the hover effect (preview, color, tooltip, etc) stays if I move my mouse up. The only way to get it to go away if to move mouse sideways to an empty part of the panel.

**Comment by philippun1** [comment] 2022-03-16 18:33
I have added the patches from @crab2313 to my MR: #1584

**Comment by Boulotaur2024** [comment] 2022-03-25 06:07
> I have added the patches from @crab2313 to my MR: #1584

![Screenshot from 2022-03-25 07-02-09](https://user-images.githubusercontent.com/8013986/160063711-be4455d7-19c7-4686-9dcc-196a9ccc427d.png)

Still can't get it to work by installing your patches, see above.

What I did : 

$ git clone https://github.com/philippun1/dash-to-panel.git
$ cd dash-to-panel
$ make install

**Comment by miigotu** [comment] 2022-03-26 02:00
> @crab2313 There's an issue I'm experiencing. If I hover over something on the panel, the hover effect (preview, color, tooltip, etc) stays if I move my mouse up. The only way to get it to go away if to move mouse sideways to an empty part of the panel.

This happens in other extensions with gnome42 also, dash-to-dock, etc.

**Comment by Lucapz** [comment] 2022-03-26 12:20
https://discourse.ubuntu.com/t/update-for-dash-to-panel-package/27346/1

dash-to-panel package likely to be removed from Ubuntu repositories.

**Comment by nexryai** [comment] 2022-03-26 12:32
I have tried this branch and Intellihide does not appear to be working. The taskbar is always visible instead of hidden.

**Comment by nexryai** [comment] 2022-03-26 14:26
> @crab2313 There's an issue I'm experiencing. If I hover over something on the panel, the hover effect (preview, color, tooltip, etc) stays if I move my mouse up. The only way to get it to go away if to move mouse sideways to an empty part of the panel.

Oddly enough, I am encountering the same glitch with popup notifications: up until 41, hovering over the popup notification and then moving the cursor to another location would close the popup, but in 42, nothing happens when I move the cursor.
So it appears that this is not an extension-specific issue, but rather a glitch in the processing that is triggered by "mouse away" in Gnome 42.

**Comment by miigotu** [comment] 2022-03-27 01:56
> https://discourse.ubuntu.com/t/update-for-dash-to-panel-package/27346/1
> 
> dash-to-panel package likely to be removed from Ubuntu repositories.
> 
> 

Most people install from extensions.gnome.org anyway. We don't need it in the package center. Imo, most people don't even use the package center, or snaps. I completely removed snaps, and use apt entirely, or gnome extensions website.

**Comment by Lucapz** [comment] 2022-03-27 08:09
@miigotu 

>>Maintainer could very well provide their own

As it stands it doesn't look like we have one as @jderose9 no longer has time for the project and @charlesg99 hasn't bothered to tell us what is happening with the project, he removed the paypal donation link and applied a couple of commits months ago and that's about it.

**Comment by psarraf** [comment] 2022-03-27 18:00
> > @crab2313 There's an issue I'm experiencing. If I hover over something on the panel, the hover effect (preview, color, tooltip, etc) stays if I move my mouse up. The only way to get it to go away if to move mouse sideways to an empty part of the panel.
> 
> This happens in other extensions with gnome42 also, dash-to-dock, etc.

This appears to be an issue with mutter. https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321

**Comment by crosser** [comment] 2022-03-27 18:56
> Most people install from extensions.gnome.org anyway. We don't need it in the package center.

Please do not make decisions based on this reasoning. Every additional source from which software can be installed increases the user's attack surface. In this respect, having the package removed from the distro's deb repo is rather bad news.

**Comment by philippun1** [comment] 2022-03-27 19:56
Yes, dash-to-panel being removed from Ubuntu packages is sad indeed. But with Extension Manager on Flathub there is a very convenient way now to get extensions and keep them up to date.
https://flathub.org/apps/details/com.mattjakeman.ExtensionManager

**Comment by miigotu** [comment] 2022-03-28 01:37
> @miigotu 
> 
> >>Maintainer could very well provide their own
> 
> As it stands it doesn't look like we have one as @jderose9 no longer has time for the project and @charlesg99 hasn't bothered to tell us what is happening with the project, he removed the paypal donation link and applied a couple of commits months ago and that's about it.

I could very well fork and maintain a clone if there were enough support and code contributions. I'm not interested in just keeping another stale repository on my profile though.

**Comment by miigotu** [comment] 2022-03-28 01:41
> > Most people install from extensions.gnome.org anyway. We don't need it in the package center.
> 
> Please do not make decisions based on this reasoning. Every additional source from which software can be installed increases the user's attack surface. In this respect, having the package removed from the distro's deb repo is rather bad news.

That's just incorrect. Separate source locations that are trusted limits the reach any single attack can achieve. Mostly everyone adds at least one external software repository on their daily use machine unless they are disallowed by policy. If an extension has any attack surface at all, it is the extensions implementation at fault, not the extension.

**Comment by philippun1** [comment] 2022-03-28 08:15
@charlesg99 If you do not have the time at the moment, you can add me to the team and I can help. And @miigotu as well, he is willing to maintain it. I will keep contributing code.

**Comment by Lucapz** [comment] 2022-03-28 11:23
@miigotu 
@philippun1 

It might be worth starting a new thread on the future of this project in case this one gets closed.

**Comment by jderose9** [comment] 2022-03-28 12:10
> 
> As it stands it doesn't look like we have one as @jderose9 no longer has time for the project and @charlesg99 hasn't bothered to tell us what is happening with the project, he removed the paypal donation link and applied a couple of commits months ago and that's about it.

If it is helpful, I'd offer to coordinate releases by reviewing pull requests, gathering the translations, release notes, etc. and deal with packaging issues, as I was doing before, but that's quite a bit of effort itself. Realistically I don't have time to keep up with all the breaking changes on every Gnome release as well. I can try to reach out to @charlesg99 and see if he wants to add me back to the project.

When a breaking change happens upstream, it's not generally sufficient to hack around it. The reason for the upstream change needs to be understood (as sometimes they were unintentional and get rolled back), all of the features and configuration permutations that might be affected in dash-to-panel need to be addressed, and backwards compatibility needs to be considered. So, someone else will need to volunteer to own that process.

**Comment by miigotu** [comment] 2022-03-28 19:20
> > 
> > As it stands it doesn't look like we have one as @jderose9 no longer has time for the project and @charlesg99 hasn't bothered to tell us what is happening with the project, he removed the paypal donation link and applied a couple of commits months ago and that's about it.
> 
> If it is helpful, I'd offer to coordinate releases by reviewing pull requests, gathering the translations, release notes, etc. and deal with packaging issues, as I was doing before, but that's quite a bit of effort itself. Realistically I don't have time to keep up with all the breaking changes on every Gnome release as well. I can try to reach out to @charlesg99 and see if he wants to add me back to the project.
> 
> When a breaking change happens upstream, it's not generally sufficient to hack around it. The reason for the upstream change needs to be understood (as sometimes they were unintentional and get rolled back), all of the features and configuration permutations that might be affected in dash-to-panel need to be addressed, and backwards compatibility needs to be considered. So, someone else will need to volunteer to own that process.

Ideally a workflow should exist that compiles releases on tags pushed that reference a tag on master. It should be built and released to extensions.gnome.org, Github packages, a ppa, and any other endpoint we can provide and maintain... automatically. Everything should be merged to a devel or even a nightly branch between releases, and release a nightly/devel package automatically for people to try when things aren't working for them. 

After that, we should find a way to better track changes in gnome-shell/gjs. Even if we have to build a custom tool to track commits to their repository and check diffs for what symbols/items we need to hook into.

**Comment by jderose9** [comment] 2022-03-28 19:55
> Ideally a workflow should exist that compiles releases on tags pushed that reference a tag on master. It should be built and released to extensions.gnome.org, Github packages, a ppa, and any other endpoint we can provide and maintain... automatically. Everything should be merged to a devel or even a nightly branch between releases, and release a nightly/devel package automatically for people to try when things aren't working for them.
> 
> After that, we should find a way to better track changes in gnome-shell/gjs. Even if we have to build a custom tool to track commits to their repository and check diffs for what symbols/items we need to hook into.

Those things mostly exist. Still, someone has to decide which changes will make it in a release, notify translators of an upcoming release, review translations, review outstanding pull requests, test multiple permutations of configurations compatibility with multiple versions of multiple distros.

GNOME extensions monkey patch the running desktop environment. Any changes upstream can potentially break the extension because it is essentially replacing the guts of private classes. There's close to no code-freeze time period up-stream and as I mentioned, even a minor release of gnome can break the extension.  It can be only a couple of days between commit and hitting the machines of arch and tumbleweed users. 

The biggest issue is that _someone has to fix the problem_, with code that maintains backward compatibility, test it, and send it through the manual GNOME extension review process. It sounds nice to say that the community can review the development branch, but generally speaking, people on an LTS distro don't test the development branch, and people on a rolling distro don't test for backward compatibility, so someone needs to make sure it happens. Otherwise, the stable distro machines will break as they all get their extensions from the same source (e.g.o).

**Comment by Lucapz** [comment] 2022-03-28 22:34
Great to see you back [jderose9](https://github.com/jderose9), Thanks for trying to keep your project going even though it sounds like there isn't a clear way forward with the way gnome keeps changing things about and breaking things.

Couldn't some of the dash-to-dock commits be used as a base to fix dash-to-panel?

**Comment by philippun1** [comment] 2022-03-29 00:02
@jderose9 The biggest problem at the moment is not to fix the problems. I.e., the gnome 42 fixes are ready (for a while now), but they are not being merged into the main branch.

**Comment by CountOmega** [comment] 2022-03-29 00:58
I can confirm @philippun1 branch is working so far on Debian unstable.

**Comment by miigotu** [comment] 2022-03-29 02:20
> @jderose9 The biggest problem at the moment is not to fix the problems. I.e., the gnome 42 fixes are ready (for a while now), but they are not being merged into the main branch.
> There are also enough eyes on the Pull Requests to find (most) bugs and regressions. But someone has to merge the branches and create the versions.
> 
> So in my opinion the team has to grow or the project will ultimately be forked at some point. Gnome 42 has been released and many people are waiting for a release...

I have already forked and applied some changes for references, because I didn't think the OG's were going to respond.

For now I think I will use my fork to try and automate some of the review, release, and resolution processes, as well as adding a way to trigger warnings on upstream changes so we know faster when something is going to break. We can trigger a test every time gnome pushes a commit even and check if the extension still runs without user intervention, and let us know if it doesn't, before gnome changes ever get released to an end user.

I know first hand that maintaining a project like this is draining and stressful. But I also know that automation is the key to ease that workload dramatically.

**Comment by miigotu** [comment] 2022-03-29 02:22
I also fixed an issue in the Makefile for extraction of strings for the pot file, I'll see if I can PR that here when I get to my laptop next.

**Comment by RubenRibGarcia** [comment] 2022-03-30 08:53
> Confirmed. Please try the new patch set below.
> 
> [gnome42-v2.tar.gz](https://github.com/home-sweet-gnome/dash-to-panel/files/8264895/gnome42-v2.tar.gz)
> 
> > ![Screenshot from 2022-03-16 15-40-14](https://user-images.githubusercontent.com/1404921/158615684-0fa80b20-4e43-40b8-91cb-2ae035755c76.png) IIRC right click on panel icons was broken some time before the extension stopped to load.
> > It is annoying, but probably a matter for a separate ticket.
> > Edit: I confirm that the panel is broken after locking and unlocking

This solutions worked for me as well on the Debian Testing/bookworm, which have the Gnome Shell 41.4.
Add to revert one of the patches that requires that I had the Gnome 42, and I still only have the 41.
Will trying to work as is to see If I find another problem :)

**Comment by beardogg0524** [comment] 2022-04-02 15:22
> Confirmed. Please try the new patch set below.
> 
> [gnome42-v2.tar.gz](https://github.com/home-sweet-gnome/dash-to-panel/files/8264895/gnome42-v2.tar.gz)
> 
> > ![Screenshot from 2022-03-16 15-40-14](https://user-images.githubusercontent.com/1404921/158615684-0fa80b20-4e43-40b8-91cb-2ae035755c76.png) IIRC right click on panel icons was broken some time before the extension stopped to load.
> > It is annoying, but probably a matter for a separate ticket.
> > Edit: I confirm that the panel is broken after locking and unlocking

I'm new to applying patches, so how do I apply these patches? I'm on Ubuntu 22.04 Beta.

**Comment by block6791** [comment] 2022-04-03 14:08
Just installed the development version by following [instructions here (](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github)on) Fedora 36 beta. It works including the settings panel.

**Comment by charlesg99** [comment] 2022-04-05 01:35
Hey guys, I think the master branch is almost ready for the next release supporting GS 42. Please pull the latest changes and let us know if you find a problem. I'll prepare an e.g.o. package this week, unless something major surfaces. Thanks!

**Comment by miigotu** [comment] 2022-04-05 04:46
@erickwill disable all other broken extensions, and build this from the master branch. Other users have reported the entire extensions support in gnome as a whole stopping working the breaking changes of gnome 42, once one extension crashes.

**Comment by philippun1** [comment] 2022-04-05 12:52
The only thing missing is #1600 but this is not a dealbreaker in my opinion. Everything else works fine, running Manjaro (gnome41) and Ubuntu (gnome42) as daily drivers with the latest git version.
@charlesg99 Go for the new version! :)

**Comment by mrjavum** [comment] 2022-04-06 16:24
Just updated to Gnome 42 in Arch and installed dash-to-panel latest master branch. I have weird with "sticky" icon labels which sometimes not disapperared.
![image](https://user-images.githubusercontent.com/977334/162021905-25291189-01fa-488d-96c2-3f64709fff06.png)

**Comment by philippun1** [comment] 2022-04-06 17:25
@mrjavum This is a known gnome bug.
#1606 is now fixed. So everything looks ready to me! :)

**Comment by mrjavum** [comment] 2022-04-07 03:01
@philippun1
Thanks, I have found this: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321
So waiting for updates on Arch)

**Comment by averyfreeman** [comment] 2022-04-07 05:09
> Can we just take a moment to appreciate the phrase, `Impossible to enumerate trash children`.

I know I've seen that somewhere before 🤔 https://www.youtube.com/watch?v=PGNVJV3Imlg

**Comment by charlesg99** [comment] 2022-04-07 11:46
Just updated arch and the new mutter package fixed the hover issue. Now we're ready!

**Comment by charlesg99** [comment] 2022-04-07 14:03
Thanks to a speedy review by JustPerfection, v46 is already available on e.g.o. Closing, please open new issues if you find a problem.

**Closed as completed by charlesg99** 2022-04-07 14:03 UTC

**Comment by crosser** [comment] 2022-04-08 19:12
Huh, this was covered [in the media](https://www.omgubuntu.co.uk/2022/04/dash-to-panel-now-supports-gnome-42)!
