### ISSUE TITLE
No "quit" option anymore

### ISSUE THREAD

**Issue by kouros174** [home-sweet-gnome/dash-to-panel#902] opened 2020-03-20 00:29 UTC
With latest release and gnome 3.36 (in manjaro) when I click with "right click" an opened app I don't have the "quit" option anymore (in order to close the app).

![Screenshot](https://user-images.githubusercontent.com/62362829/77126677-a8330580-6a52-11ea-961f-c93790a2ac19.png)

**Comment by charlesg99** [comment] 2020-03-20 18:34
Hello, I can't reproduce this, the Quit option is there for me. Did you try another theme maybe? Thanks!

**Comment by jderose9** [comment] 2020-03-20 20:40
Everything works fine for me on 3.36.0 on Fedora Rawhide, but on Manjaro Testing repos I get some errors.

Enabling extension:
> JS WARNING: [/home/jason/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js 693]: reference to undefined property "_tweeningToSize"

Right clicking appIcon or empty panel area:
> JS WARNING: [resource:///org/gnome/shell/ui/appDisplay.js 2439]: reference to undefined property "app"
JS ERROR: TypeError: this._source.app is undefined
_rebuildMenu@resource:///org/gnome/shell/ui/appDisplay.js:2439:23
popup@resource:///org/gnome/shell/ui/appDisplay.js:2553:14
popupMenu@/home/jason/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1711:20
_onButtonPress@/home/jason/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:809:47

**Comment by charlesg99** [comment] 2020-03-20 21:34
Hey Jason! The second issue should be fixed on master and I'll have a look at the first one (haven't encountered it yet as I use the ungrouped icons). Those are new since this morning for me on Arch...

**Comment by kouros174** [comment] 2020-03-20 23:45
@charlesg99 I installed the extension from github and the issue fixed! 
Now I have the "quit" option again. 
Thanks a lot for the best gnome extension and if you wish you can close the issue. :)

**Comment by jderose9** [comment] 2020-03-21 02:24
@charlesg99 Awesome, from what I can tell, everything looks good behavior wise with the latest master.

The _tweeningToSize warning is still there, but not sure if the event timing changed or maybe the gjs build for that package is just set to strict mode... I don't think it's going to fall into the code block there so it doesn't seem like an actual concern.

I'm also getting this in the log periodically when hovering over app icons: `Ignoring excess values in shadow definition`, but maybe that's related specifically to the manjaro theme.

Everything looks good though and I don't see either of these on rawhide so I'm kind of inclined just to wait and see if they get cleaned up by upstream changes.

**Comment by charlesg99** [comment] 2020-03-21 12:44
@jderose9 I would say the same. The "shadow" warning definitely comes from the theme and probably occurs on vanilla gnome-shell as well. Let's close this one for now as it seems the underlying cause was the recent [function name change](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/bf2d012e4095825c1a51c159ebdaa11f2989d549). Thanks!

**Closed by charlesg99** 2020-03-21 12:44 UTC

**Comment by jderose9** [comment] 2020-03-21 13:21
Thanks @charlesg99 . I’m a little bit confused about the gnome-shell workflow... it doesn’t look like they’ve made a release branch for 3.36 yet so I’m assuming 3.36 builds are still coming from master and that this is going to hit the stable repos eventually. Assuming that’s all accurate, we probably need to go ahead and release v31 with this fix?

**Comment by charlesg99** [comment] 2020-03-21 13:48
Yeah from what I gather Arch packages come from gnome-shell master since the 3.36 tag. Not too sure what happens when point releases are tagged/branched. Anyway since the breaking change was added to g-s master, we might as well release v31 now for Arch users.

**Comment by lights0123** [comment] 2020-03-21 19:48
I've upgraded to the latest version on Arch, but I'm still experiencing this error.

![Screenshot from 2020-03-21 15-45-59](https://user-images.githubusercontent.com/3756309/77235348-432efb00-6b8b-11ea-8455-7901fdfdad9d.png)

**Comment by jderose9** [comment] 2020-03-21 19:53
@lights0123 I released v31 a couple of hours ago but the AUR package has not been updated yet. You can install directly from GitHub if you would like the fix immediately.

**Comment by Devorlon** [comment] 2020-03-22 14:25
Just updated on arch using the gnome-shell-extension-dash-to-panel-git AUR package and it appears now. Thanks

![](https://i.imgur.com/7Mc0hI3.png)
