### ISSUE TITLE
Gnome Shell segfault when clicking the date area

### ISSUE THREAD

**Issue by lnicola** [home-sweet-gnome/dash-to-panel#950] opened 2020-04-08 17:06 UTC
**Describe the bug**
Sometimes Gnome Shell crashes when I click on the date/clock area. I'm not sure if it's related to this extension, so I'm cross-filing this (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2605).

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
3.36.1, Wayland

**Dash-to-Panel version**
v35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**

```
Apr 08 19:44:32 maru kernel: gnome-shell[107105]: segfault at 0 ip 00007f2aa1150756 sp 00007ffc45984140 error 4 in libst-1.0.so[7f2aa114d000+48000]
Apr 08 19:44:32 maru kernel: Code: 00 00 85 db 0f 84 9a 00 00 00 49 8b 87 28 01 00 00 89 dd 4a 8b 04 30 83 e5 01 0f 84 54 ff ff ff 48 8b 08 48 8d 3d 41 07 05 00 <48> 8b 09 48 8b 31 b9 06 00 00 00 f3 a6 0f 97 c1>
```

No backtrace yet. I'll come back when I have one.

**Comment by charlesg99** [comment] 2020-04-09 13:08
Hello Inicola, thank you for the report. We can keep it opened until there is a fix from gnome-shell, but seeing the number of similar issues they received (with or without dash to panel), I think we should wait and see. Thanks!

**Comment by nnleaf** [comment] 2020-04-19 06:09
Hi, I'm having similar issues.Gnome Shell crashes when I click on the date/click/wifi area and I have a simliar setup. I've tired disabling all extensions, down to the bare minimum and I believe it has to do with Dash-To-Panel. I've grown accustomed to this extension, so it'd be hard to live without it!

**Linux distribution and version**
Arch Linux

**GNOME Shell version**
3.36.1-1, Wayland or x11

**Dash-to-Panel version**
v35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**
sudo journalctl /usr/bin/gnome-shell
`Apr 19 01:02:50 x1 gnome-shell[2352]: libinput error: client bug: timer event18 debounce: scheduled expiry is in the past (-3ms), your system is too slow
Apr 19 01:02:50 x1 gnome-shell[2352]: libinput error: client bug: timer event18 debounce short: scheduled expiry is in the past (-16ms), your system is too slow
Apr 19 01:26:51 x1 gnome-shell[2352]: loading user theme: /usr/share/themes/Adwaita-red-dark/gnome-shell/gnome-shell.css
Apr 19 01:54:17 x1 gnome-shell[2352]: An active wireless connection, in infrastructure mode, involves no access point?
Apr 19 01:54:17 x1 gnome-shell[2352]: Could not release device (13,83): GDBus.Error:org.freedesktop.login1.DeviceNotTaken: Device not taken
Apr 19 01:54:17 x1 gnome-shell[2352]: Could not release device (13,82): GDBus.Error:org.freedesktop.login1.DeviceNotTaken: Device not taken
Apr 19 01:54:17 x1 gnome-shell[2352]: 0x60000c: frame_complete callback never occurred for frame 206354
Apr 19 01:54:19 x1 gnome-shell[2352]: loading user theme: /usr/share/themes/Adwaita-red-dark/gnome-shell/gnome-shell.css
Apr 19 01:54:22 x1 audit[2352]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=3 pid=2352 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Apr 19 01:54:33 x1 gnome-shell[42370]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Apr 19 01:54:33 x1 gnome-shell[42370]: Will monitor session c2
Apr 19 01:54:33 x1 gnome-shell[42370]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Apr 19 01:54:34 x1 gnome-shell[42370]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Apr 19 01:54:34 x1 gnome-shell[42370]: libinput error: client bug: timer event15 keyboard: scheduled expiry is in the past (-295ms), your system is too slow
Apr 19 01:54:34 x1 gnome-shell[42370]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Apr 19 01:54:34 x1 gnome-shell[42370]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 24]: reference to undefined property "MetaWindowXwayland"
Apr 19 01:54:34 x1 gnome-shell[42370]: Registering session with GDM
Apr 19 01:55:19 x1 gnome-shell[42370]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Apr 19 01:55:19 x1 gnome-shell[42370]: == Stack trace for context 0x5574acccc450 ==
Apr 19 01:55:19 x1 gnome-shell[42370]: == Stack trace for context 0x5574acccc450 ==
Apr 19 01:55:19 x1 gnome-shell[42370]: == Stack trace for context 0x5574acccc450 ==
Apr 19 01:55:19 x1 gnome-shell[42370]: == Stack trace for context 0x5574acccc450 ==
Apr 19 01:55:19 x1 gnome-shell[42370]: == Stack trace for context 0x5574acccc450 ==
Apr 19 01:55:19 x1 gnome-shell[42370]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remov>
Apr 19 01:55:19 x1 gnome-shell[42370]: The offending signal was notify on NMDeviceEthernet 0x5574af2c8220.
Apr 19 01:55:19 x1 gnome-shell[42370]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remov>
Apr 19 01:55:19 x1 gnome-shell[42370]: The offending signal was notify on NMDeviceWifi 0x5574af2cc370.
Apr 19 01:55:19 x1 gnome-shell[42370]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remov>
Apr 19 01:55:19 x1 gnome-shell[42370]: The offending signal was notify on NMActiveConnection 0x5574af2d5180.
Apr 19 01:55:19 x1 gnome-shell[42370]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remov>
Apr 19 01:55:19 x1 gnome-shell[42370]: The offending signal was state-changed on NMDeviceEthernet 0x5574af2c8220.
Apr 19 01:55:19 x1 gnome-shell[42370]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remov>
Apr 19 01:55:19 x1 gnome-shell[42370]: The offending signal was state-changed on NMDeviceWifi 0x5574af2cc370.`

**Comment by lnicola** [comment] 2020-04-19 06:20
@nnleaf my Gnome issue was probably a duplicate of https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2596 or https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2541, in case you didn't follow through the link.

**Comment by avbor** [comment] 2020-04-20 09:36
Same random crashes on Fedora 32 (gnome 3.36.1 on wayland, dash to panel 35)... =(
But this happens not only when clicking in the tray, sometimes gnome crashes when i unlock my session.

**Comment by nnleaf** [comment] 2020-04-24 22:17
@lnicola It seems your two links no longer work. I saw you closed your original issue https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2605 , did you get it resolved?

**Comment by lnicola** [comment] 2020-04-25 04:30
@nnleaf no, the two linked issues are still open. I have no idea why they no longer work. I closed it because it was a duplicate of those, and because I couldn't get a crash dump.

**Comment by MPratley** [comment] 2020-04-26 11:29
Just to add a couple of points: 

- It seems to happen more often for me when dash-to-panel is enabled, but still happens without. 
- (Wayland) If it happens once, it'll happen much faster the next time you log in until you reboot.

Sadly I've not been able to get anything decipherable from the crash dump yet, it's blamed everything from misrendering windows to missing font files. I'm guessing there's a race condition somewhere awkward.

Just a note for anyone googling: this issue is much more manageable in xorg than wayland.

**Comment by wada3n** [comment] 2020-04-26 22:19
Hello, I'm having similar issues.
Gnome Shell crashes when I click on the date/Battery/wifi area.
I think the problem is related to the extension, because it doesn't appear after being disabled.

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.1, x11

**Dash-to-Panel version**
v35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by lnicola** [comment] 2020-04-27 09:58
For anyone who wants to compile their own version of `gnome-shell`, there seems to be a fix at https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1218.

**Comment by hvitoi** [comment] 2020-04-28 18:36
I'm having the same issue regarding this extensions. When clicking on any icon close to the clock/date, the gnome-shell instantly crashes and goes back to gdm login screen. Furthermore all the opnened applications are force closed, including unsaved work.

**Linux distribution and version**
Debian GNU/Linux bullseye/sid

**GNOME Shell version**
3.36.1 on Wayland

**Dash-to-Panel version**
v37

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**General protection fault from /var/log/kern.log**
`Apr 28 15:20:00 callisto kernel: [ 4605.852749] traps: gnome-shell[1875] general protection fault ip:7fecb1f0495f sp:7ffcca8e52e0 error:0 in libst-1.0.so[7fecb1ee3000+4a000]`

**Comment by charlesg99** [comment] 2020-04-29 00:58
Hello, I tried to reproduce this today but couldn't using v37 on Ubuntu 20.04 (wayland). Anything particular with your setup? Which theme/icon set are you using? Anyway, seems like the [gnome-shell fix](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1218) was merged earlier, so Ubuntu should be updated soon I guess. Thanks!

**Comment by jonmacd** [comment] 2020-04-29 05:11
I'm wondering if this is related to using a secondary monitor? I run Arch with Gnome on both my desktop and laptop. Both machines are using dash to panel. However, only my desktop (two identical monitors) seems to have these segfaults.

**Comment by lnicola** [comment] 2020-04-29 05:25
No, I see it on my laptop without a secondary monitor. It happens more often after suspend, I think. I'm using a custom theme. One of the linked issues mentions crashing after changing the theme and locking the computer.

**Comment by charlesg99** [comment] 2020-05-01 21:46
Let's close this one since it was replaced by #976.

**Closed by charlesg99** 2020-05-01 21:46 UTC
Labels: bug
