### ISSUE TITLE
Font color

### ISSUE THREAD

**Issue by eturkes** [home-sweet-gnome/dash-to-panel#727] opened 2019-09-12 10:34 UTC
It would be nice to be able to change the color of text to facilitate light task bar colors. This is done with the SLE classic theme extension on SUSE, if a reference might help. Thanks!

**Comment by pmontrasio** [comment] 2019-10-20 19:41
It would be enough to know where to patch the installed extension. I tried to put `color: #000000` in several places of `stylesheet.css` and restart the shell, nothing changed.

**Comment by charlesg99** [comment] 2019-10-20 23:17
@pmontrasio To get started with the color of the gnome-shell panel items, you could try adding:
```
#panel StLabel, #panel StIcon {
	color: rgba(0, 0, 0, 1);
}
```
Of course this won't work for everything as other extensions might define their colors more explicitly. Thanks!

**Comment by charlesg99** [comment] 2019-10-20 23:17
Oops didn't mean to close that sorry :)

**Comment by pmontrasio** [comment] 2019-10-21 05:30
@charlesg99 Thanks! That suggestion fixed the color of the text and icons in the panel, except for the running apps.

To change that I couldn't find another way than doing this

```
--- a/appIcons.js	2019-10-20 21:58:44.931383774 +0200
+++ b/appIcons.js	2019-10-20 21:59:04.875096181 +0200
@@ -446,9 +446,7 @@
             this._windowTitle.set_style('font-size: ' + this._dtpSettings.get_int('group-apps-label-font-size') + 'px;' +
                                         'font-weight: ' + fontWeight + ';' +
                                         (useFixedWidth ? '' : 'max-width: ' + maxLabelWidth + 'px;') + 
-                                        'color: ' + this._dtpSettings.get_string('group-apps-label-font-color'));
+                                        'color: #000000');
         }
     },
```

Obviously this is a very wrong way to do it.
I wonder where those settings come from. Maybe from the Gnome shell theme?

To set the color of the title of the preview I did this

```
--- a/windowPreview.js	2019-10-20 21:58:44.931383774 +0200
+++ b/windowPreview.js	2019-10-20 21:59:59.538380215 +0200
@@ -913,9 +913,7 @@
             let icon = this._previewMenu.getCurrentAppIcon().app.create_icon_texture(iconTextureSize);
             let workspaceIndex = '';
             let workspaceStyle = null;
-            let commonTitleStyles = 'color: ' + this._previewMenu._dtpSettings.get_string('window-preview-title-font-color') + ';' +
+            let commonTitleStyles = 'color: #000000;' +
                                     'font-size: ' + this._previewMenu._dtpSettings.get_int('window-preview-title-font-size') + 'px;' +
                                     'font-weight: ' + this._previewMenu._dtpSettings.get_string('window-preview-title-font-weight') + ';';
```

Then I used "Override panel theme background color" to set a light gray color and I'm happy with that for now.

**Comment by charlesg99** [comment] 2019-10-21 12:12
@pmontrasio Well, sorry, seems like I didn't correctly understand your question... I provided this example specifically because theses are the only colors that you can't change from our settings directly :joy:

Application titles:

![image](https://user-images.githubusercontent.com/33044886/67203827-14dda180-f3da-11e9-910e-d219afe556cd.png)


Window preview titles:

![image](https://user-images.githubusercontent.com/33044886/67203868-2fb01600-f3da-11e9-8c43-3a3118960e70.png)

Thanks!

**Comment by pmontrasio** [comment] 2019-10-22 12:02
@charlesg99 I didn't realized those settings controlled the color of the text, or maybe I thought they didn't work: changing the font size has an immediate effect, changing the color doesn't. I reverted my changes to the file, set the colors, restarted the shell and it worked.
Thanks!

**Comment by charlesg99** [comment] 2019-10-22 12:30
> changing the font size has an immediate effect, changing the color doesn't

Could you please provide more info on that? It should be instantaneous (and it is for me on 3.34, Xorg and Wayland):

![Peek 2019-10-22 08-18](https://user-images.githubusercontent.com/33044886/67285090-ebd61300-f4a4-11e9-9c86-abe118fa46c2.gif)

Thanks!

**Comment by pmontrasio** [comment] 2019-10-22 13:43
I did what you showed in the GIF and it worked for me too. I either hallucinated or didn't realize it was working because I have intellihide active. 
Well, I think I already abused enough of your kindness. To recap: it's possible to change the color of the labels and your suggestion 

```
#panel StLabel, #panel StIcon {
	color: rgba(0, 0, 0, 1);
}
```

also changes the color of the standard labels and icons such as clock, network, battery, etc.  Maybe this issue could be closed as it stands or you might want to make this extension set `#panel StLabel, #panel StIcon` too. Probably that should be an option: I keep them in the bottom panel and it makes sense to display them with the same color of the app icons. Probably not everybody is doing that.

**Closed** 2020-07-03 01:28 UTC

**Comment by Lassebq** [comment] 2023-12-20 19:36
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/68742864/22142266-8f09-4e58-83c8-fbd8be04bbc2)
Having the same issue on latest git. Was there a regression? I'm also unable to find property to modify title color in the extension's settings
