### ISSUE TITLE
Drag files Trough Dash to panel.

### ISSUE THREAD

**Issue by ViniciusVargas17** [home-sweet-gnome/dash-to-panel#1257] opened 2021-01-06 18:43 UTC
I will just give an example to better explain what i have in mind.
I want to take an png from a folder and put in GIMP by dragging the file above the gimp icon in my panel, and then the gimp would maximize or just appear in my screen while i hold the the file and then drop into the gimp.

**Comment by panta82** [comment] 2021-04-15 19:20
That would be fantastic. Having to go through that silly full-screen "overview" thing is so slow.

**Comment by jderose9** [comment] 2021-06-09 13:19
Closing as dupe of #46

**Closed by jderose9** 2021-06-09 13:19 UTC
Labels: enhancement
