### ISSUE TITLE
Time does not update when dash-to-panel in hiding state

### ISSUE THREAD

**Issue by colben** [home-sweet-gnome/dash-to-panel#1206] opened 2020-10-08 09:46 UTC
# ENV
- Archlinux with gnome: latest
- dash-to-panel installed by pacman: latest

# ISSUE
- Dash-to-panel does not update time when it is hidden.

**Comment by regzon** [comment] 2020-10-09 07:07
The same issue. OS: Debian Testing. Dash-to-panel installed from the source code (master branch).

**Comment by qifei9** [comment] 2020-10-15 13:54
same issue here.

**Comment by qifei9** [comment] 2020-10-15 13:57
same issue here.

**Comment by charlesg99** [comment] 2020-10-19 11:58
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2973

**Comment by ByteEnable** [comment] 2020-11-15 18:20
A work-around was posted in the issue above:

As stated above, the issue should be resolved in 3.38.2, but you need to wait for your distro to provide this. In the meantime, if you enable "Show seconds" in gnome-tweaks, the issue will be resolved.

**Comment by crivaronicolini** [comment] 2020-11-28 21:45
I have the same problem, but with de battery percentage instead.

**Comment by regzon** [comment] 2020-12-11 19:19
For Debian Testing and Arch Linux the issue is resolved (with a `gnome-shell` update).

**Comment by jderose9** [comment] 2020-12-12 22:09
I’ll close this since it’s resolved upstream.

**Closed by jderose9** 2020-12-12 22:09 UTC
