### ISSUE TITLE
Animated drag and drop to rearrange

### ISSUE THREAD

**Issue by aayushdutt** [home-sweet-gnome/dash-to-panel#1044] opened 2020-06-13 12:54 UTC
**Describe the idea or feature you'd like**
Adding an animated drag and drop on the panel to rearrange the tabs (just like windows) would be a huge huge improvement in UX.

**Comment by charlesg99** [comment] 2020-06-14 23:52
Hello aayushdutt, thank you for the suggestion, I'll close this one as it is a duplicate of #839. Thanks!

**Closed by charlesg99** 2020-06-14 23:52 UTC
Labels: enhancement
