### ISSUE TITLE
Custom Border Radius Setting

### ISSUE THREAD

**Issue by karkar-div** [home-sweet-gnome/dash-to-panel#2033] opened 2024-02-14 11:06 UTC
Adding a slide to customize border-radius from sharp angles (like how focused apps are displayed) to round edges (like the apps button) and making it clear in the extension settings will be nice.

I'm a little bit frustrated when I see sharp edges or circles. This is my preference and everyone has his own.

If this feature is not possible to make, can someone please point to the source code file that controls this?

**Comment by yarecco** [comment] 2024-02-21 16:51
You can add to the stylesheet.css the entry as follows:
#panelBox #panel {
    border-radius: 16px;
}

#panelBox {
padding-bottom: 12px;

The second one if for some space from the bottom edge of the screen.
The problem is ( in my case) that after adding this my screen does not go blank anymore LOL
so far can't fix that weird issue

**Comment by karkar-div** [comment] 2024-02-21 20:46
thanks

**Comment by charlesg99** [comment] 2024-04-09 19:17
duplicate of #1819

**Closed by charlesg99** 2024-04-09 19:17 UTC
Labels: enhancement
