### ISSUE TITLE
Hot corner is hard to activate

### ISSUE THREAD

**Issue by dessant** [home-sweet-gnome/dash-to-panel#610] opened 2019-03-26 09:01 UTC
I have placed the panel at the top, and the hot corner doesn't always activate, or only after a bit of delay. For the corner to activate the mouse gesture must be exaggerated. This usually results in several tries until I manage to activate the hot corner.

Disabling the extension restores the expected behavior of the hot corner. Tested with Dash to Panel 19 and [master](https://github.com/home-sweet-gnome/dash-to-panel/tree/3d55bc5c4dc410a315502843d227697dd4fa1466) on Gnome 3.32.0.

**Comment by mweirauch** [comment] 2019-03-26 15:00
I think I wittness the same. Wasn't really annoying me that much, but now that there is an open issue ...
Fedora 29
Gnome 3.30.2
DtP b3aecfce1d79cedcdc4e398c55f32d44d0c1f448 (master @ 2019-03-17)

**Comment by charlesg99** [comment] 2019-03-27 23:25
Hello! Thank you for bringing that up, but so far I can't reproduce this. Is it something that was introduced recently or was it always like this (I can't be of much help as I always disable the hot corner)? Seems unrelated to 3.32 since mweirauch is on 3.30. Are you on wayland? The only thing I can think of that could interfere with the hot corner is the intellihide pressure barrier. Is intellihide enabled in your case? Thanks!

**Comment by mweirauch** [comment] 2019-03-28 10:29
At work I am on Xorg. At home on Wayland. Same setup though (F29,3.30.2,DtP@git)
No Intellihide here.

What I just did was testing it again. What I observed when  moving the mouse pointer in top-left corner:
* need exagerated "movement" most of the time
* when the pointer hits the left screen edge first and then goes along the left edge to the top, there's a little delay (the pointer is in topleft-most position) and then hotcorner activates and the "wave anmiation" triggers (when redoing in activity mode this way, I can mostly get out of it this way again to the desktop)
* when the pointer hits the top screen edge first and then goes along the top edge to the left, there's a higher chance the hot-corner feature doesn't trigger (perhaps 20% chance it works)

So using left->top seems to trigger hot-corner better but still enough "pressure" is needed and not always works, but more reliable then top->left movement.

**Comment by dessant** [comment] 2019-04-04 08:19
Hi @charlesg99! I'm not sure when was the bug introduced, new user here. I'm on X11 and Intellihide is disabled. The issue is only reproducible if the panel is placed at the top.

**Comment by BorisHollas** [comment] 2019-04-11 07:52
I have the panel on top and the hot corner is activated if I move the mouse into the top left corner. If the mouse is already near the top left corner, the the hot corner is never activated. However, I see this as a useful feature that prevents the hot corner from being activated accidentally.

**Comment by charlesg99** [comment] 2019-09-03 18:53
I think I stumble on the cause of this... Since the multi-monitor support, we added a small barrier on the left-hand side of the panel (like the default right-hand one) to easily "throw" the mouse in the corner. This barrier is overlapping with the hotcorner. I'm working on something related, so I'll fix it whilst I'm there.

**Comment by charlesg99** [comment] 2019-09-11 03:24
This should now be fixed on branch "vertical-panel". Thanks!

**Comment by fthx** [comment] 2019-09-20 20:01
Hi Charles,

I'm back to DtP since official Horizontal Workspaces GNOME extension !
Well, I did experience the same issue.

Running vertical-panel branch, I cannot activate the hot corner (sometimes it does, but it's very rare). In a way that solves the original issue. :-p

**Comment by fthx** [comment] 2019-09-20 20:37
Ok it works again. I think my bug was related to some incompatibility with some others extensions (straight top bar ? transparent top bar ?). The hot corner works as usual i.e. without any extension.

**Comment by charlesg99** [comment] 2019-09-23 02:41
The fix to remove the extra barrier is now on master, thanks!

**Closed by charlesg99** 2019-09-23 02:41 UTC
