### ISSUE TITLE
Occasionally maximized windows are offset by Y

### ISSUE THREAD

**Issue by darkblaze69** [home-sweet-gnome/dash-to-panel#1799] opened 2022-11-21 05:18 UTC
**Things to do first**
Standard install of dash-to-panel
Panel is set to bottom
Couple of windows opened maximized

**Describe the bug**
Occasionally front windows are offset by I suppose the size of the original top shell panel.
I cannot figure out the conditions for this bug to appear, but more often it appears when coming back from login screen to a session.

**Linux distribution and version**
Manjaro

**GNOME Shell version**
GNOME Shell 43.1

**Dash-to-Panel version**
v52

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Screenshot shows 2 windows - Evolution and Tilix. They were originally both maximized. But after login back to the session Evolution appeared offset by Y.
![Screenshot from 2022-11-21 09-52-42](https://user-images.githubusercontent.com/6976920/202970953-9714914d-de4e-4867-8e9a-0265e7134556.png)

**Comment by sonicnkt** [comment] 2022-11-26 23:20
i can confirm this issue on my setup. Im also using manjaro  and gnome 43 (wayland), this usually happens when screens turn off and lock screen opens. 
For me i notice this the most with firefox.

**Comment by vksdev** [comment] 2022-11-27 13:29
I am facing this same issue with same versions of d2p and gnome but on fedora 37.

**Comment by erenoglu** [comment] 2022-12-11 21:05
I can consistently reproduce this. Panel at bottom, upon lock and unlock, any maximized windows will shift down by probably the size of "hidden" top panel. This makes Dash-to-Panel hard to use as each time I lock and unlock, I need to re-maximize my windows.

**Comment by paulenit** [comment] 2022-12-13 11:28
I experience the same behavior on GNOME 43.2 with Dash-to-Panel built and installed from the master on December 12 (Arch Linux). However, the only windows that exhibit this behavior are Firefox windows...

**Comment by charlesg99** [comment] 2022-12-14 00:52
Duplicate of #1600

https://gitlab.gnome.org/GNOME/mutter/-/issues/1627

**Closed by charlesg99** 2022-12-14 00:52 UTC
Labels: bug

**Comment by erenoglu** [comment] 2022-12-14 06:05
I can consistently reproduce this on Gnome 43.1 Wayland on up to date Arch. Dash-to-Panel at bottom or left, upon lock and unlock, any maximized windows will shift down by probably the size of "hidden" top panel. This makes Dash-to-Panel hard to use as each time I lock and unlock, I need to re-maximize my windows. The app windows also overlap the Dash-to-Panel's panel.
This shift for example prevent you from seeing the bottom or left side of the window as the Dash now overlaps that area
