### ISSUE TITLE
Improve drag'n'drop detection / Add option to disable drag'n'drop

### ISSUE THREAD

**Issue by RalfJung** [home-sweet-gnome/dash-to-panel#433] opened 2018-07-08 17:07 UTC
Fairly frequently, I find myself accidentally dragging an icon in the panel-dash. This happens several times a day and can sometimes be irritating when I do not realize why my focus is behaving so strangely. This does not happen to me in any other application, so it seems to me that dash-to-panel could improve the way it detects whether dragging has started.

Alternatively, I'd appreciate a way to just disable drag'n'drop. I have never wanted to actually drag those icons around, every single time it happened was accidental.

**Comment by MartinPL** [comment] 2018-07-09 14:30
Yep disable sound good, my problems that Dash to Dock and Dash to Panel favorites are connected, also d&p don't work when favorites are disabled.

**Comment by RalfJung** [comment] 2018-08-03 06:54
In fact I think this is responsible for https://bugzilla.gnome.org/show_bug.cgi?id=789691: I sometimes (~once a week) have the problem that I cannot interact with applications any more. I thought this was a gnome-shell bug, but actually I am pretty sure now that this is dash-to-panel drag'n'drop just "eating" all events.

**Comment by jderose9** [comment] 2018-08-03 13:58
@RalfJung You are talking about that drag/drop reordering or adding to favorites, correct?

I think disabling the drag/drop seems like a fine option (something similar to a "Lock Panel" option seen in other DEs). What makes the most sense in terms of placement for this (probably within settings pane and also some sort of shortcut from the actual panel?)

I think it would be best to report the focus issue in another issue. It sounds like you are experiencing a stuck "grab". Essentially, elements in gnome, can grab the focus which will bury events from making it to application windows, for example when a menu or modal is displayed. It's certainly possible there is a bug in the panel code or elsewhere in gnome shell that causes the grab to not get released. You can verify that this is the cause by hitting the Super key. That should always release the grab and you should be able to interact with the applications again.

In your bugzilla, you mentioned having trouble with VMs. There was a specific issue with stuck grabs and VM mouse integration, but as far as I know, that has been resolved. You can read the details at #212.

Thanks!

**Comment by RalfJung** [comment] 2018-08-19 17:51
> You are talking about that drag/drop reordering or adding to favorites, correct?

Yes. Maybe it is just buggy and can be fixed, but every two or three days I find myself in the situation where the panel thinks I want to drag'n'drop something, and I cannot get it out of that state. I click some other window, and then click Firefox again -- and it immediately beings dropping. I found that often, clicking Firefox like 4 or 5 times helps.

> In your bugzilla, you mentioned having trouble with VMs.

Yeah I originally thought VMs might be related, but since then I've had it when there were no VMs, and it always correlates with the panel thinking I want to drag something.

**Comment by RalfJung** [comment] 2018-10-21 15:32
TBH I am not even sure what the purpose of the drag'n'drop support is. I have not found a place where I can actually drop these items. Reordering them certainly does not work.

**Comment by charlesg99** [comment] 2018-10-21 20:03
> TBH I am not even sure what the purpose of the drag'n'drop support is. I have not found a place where I can actually drop these items. Reordering them certainly does not work.

Hey RalfJung, I'm guessing you're not displaying your favorite applications on your taskbar? The drag and drop is meant to add running applications to your favorites or to reorder them, like so:

![peek 2018-10-21 15-38](https://user-images.githubusercontent.com/33044886/47271495-0ef37d00-d548-11e8-802d-0e8d7e4ea417.gif)

Thanks

**Comment by charlesg99** [comment] 2018-11-06 00:15
Hi, an option to lock the taskbar was added to master. To lock/unlock, use the contextual menu of the "ShowApps" button. Some more options to reorder applications by dnd were added as well. Thanks!

**Comment by tkachen** [comment] 2018-11-06 00:17
I have same problem as @RalfJung - everything goes fine for couple days but at some moment dash icon stick to my cursor as if I was moving it in drag'n'drop mode (but I'm not - it is always single click and not holding it). It's always first icon in panel. gnome-shell: 3.30.1-2ubuntu1

**Comment by charlesg99** [comment] 2018-11-07 14:39
I could reproduce the issue mentioned by @RalfJung (I think). I've opened an [issue upstream](https://gitlab.gnome.org/GNOME/gnome-shell/issues/764) as the issue can be reproduced on vanilla gnome-shell. Thanks!

**Closed by charlesg99** 2018-11-07 14:39 UTC

**Comment by RalfJung** [comment] 2018-12-14 09:17
> Hey RalfJung, I'm guessing you're not displaying your favorite applications on your taskbar? The drag and drop is meant to add running applications to your favorites or to reorder them, like so:

I am displaying them. However, I have never seen drag'n'drop used for "add"-style actions. Drag'n'drop is for ordering things!  And I cannot even reorder items amongst my favorites. Considering that there is no visual distinction between favorite and non-favorite applications once they run, you are breaking user expectations by making some of these items behave differently than others.

Even if the "hang" bug gets fixes, this is still bad UI. I propose to replace the drag'n'drop my a context menu item to add/remove from favorites. Maybe you want to allow drag'n'drop of favorites so that they can be reordered amongst themselves, but that's already very confusing when I cannot move them to the right into positions where they mix with non-favorite running applications. So if you offer any drag'n'drop, then a visual indicator should appear between favorite and non-favorite items (e.g., a gap) to tell the user what they can and cannot achieve with drag'n'drop.

In terms of UI metaphors, the current situation just makes no sense at all.

**Comment by jderose9** [comment] 2018-12-14 15:38
The UI you are complaining about comes standard from GNOME. It also matches the behavior in Windows as well as MacOS.

Charles has provided a way to disable the drag and drop so that you don't make this action by mistake. 

The context menu to add/remove applications from favorites already exists, and is also standard gnome behavior.

**Comment by RalfJung** [comment] 2018-12-15 09:44
> Charles has provided a way to disable the drag and drop

How can I do that? (I just updated to the latest version.)

**Comment by RalfJung** [comment] 2018-12-15 09:45
> I'm unsure of what else should happen when you drag a non favorite running application between 2 favorite applications?

The thing is that a year after setting up my favorites, I don't always remember which applications are my favorites and which not.

**Comment by charlesg99** [comment] 2018-12-16 03:39
@RalfJung I've been playing a bit with the favorite highlight, do you think something like this would help to make it clearer as to which icons are your favorites?

![peek 2018-12-15 22-35](https://user-images.githubusercontent.com/33044886/50049745-09cf2c00-00ba-11e9-81ba-bfc04aac3c60.gif)

**Comment by RalfJung** [comment] 2018-12-18 17:35
So the blue is meant to indicate favorites?  However it is still the case that moving the icon between the non-favorites shows a preview where the item is between these two non-favorites, which is not what will actually happen when dropping the icon, right?

**Comment by charlesg99** [comment] 2018-12-18 18:34
Yes the blue (just for the demo), or whatever color/css style that we would elect for this purpose, is meant to indicate the favorites. Also, in the latest version you can reorder the non favorite icons between them, so wherever you drop the dragged icon (where a placeholder shows), is where it'll stay. This is also true for the window icons (in ungrouped mode) of the same applications (see #436). Thanks!

**Comment by RalfJung** [comment] 2018-12-18 19:01
> in the latest version you can reorder the non favorite icons between them, so wherever you drop the dragged icon (where a placeholder shows), is where it'll stay

That's cool!

But dragging something to in between favorites still has the effect of making it a favorite?

**Comment by charlesg99** [comment] 2018-12-18 19:19
> But dragging something to in between favorites still has the effect of making it a favorite?

Yes, but as I said earlier, I'm not sure what else should happen. Any suggestions?

**Comment by RalfJung** [comment] 2018-12-18 19:36
It could just reorder without making anything a favorite. Not sure if that makes much sense.

Or it could refuse to move items across the divider that separates favorites from non-favorites. That may nor may not be less confusing than what it does now, I am not sure.

**Comment by jderose9** [comment] 2018-12-25 22:14
@charlesg99 The blue highlight looks good to me but wanted to go ahead and get v17 out the door and couldn't find the commits anywhere. Feel free to add to master if you would like :)

**Comment by DragoCubed** [comment] 2019-02-08 14:37
When you move an icon in between two pinned apps on Windows, it does not pin it.
