### ISSUE TITLE
All Applications Menu Doesn't Show

### ISSUE THREAD

**Issue by StiffSinger** [home-sweet-gnome/dash-to-panel#1492] opened 2021-10-19 01:08 UTC
**Describe the bug**
Applications will not be displayed when the "Show Applications" button is clicked.

**Linux distribution and version**
Arch Linux x86_64

**GNOME Shell version**
40.5

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
Arch AUR

**Screenshots / Video captures**
![Screenshot from 2021-10-18 20-56-41](https://user-images.githubusercontent.com/50000936/137826923-4c999be5-1eb0-4733-9b04-189f570cd5e0.png)

**Comment by MarkoShiva** [comment] 2021-10-20 00:41
I get annoyed with missing that same feature for a long. 
It happen on multiple versions.
I cant find the correct setting in the settings so I think they overwrite it in code.

**Comment by dalpat** [comment] 2021-11-05 05:48
https://github.com/home-sweet-gnome/dash-to-panel/issues/1437#issuecomment-902875910

I think issue is solved, just waiting for it to be available in extension gnome site.

**Comment by kaimast** [comment] 2021-11-07 18:44
This is fixed for me with version 44!

**Comment by tekstryder** [comment] 2021-11-10 19:48
Verified Fixed on Gnome 40.x with extension v44.

Also verified Fixed on Gnome 41.x with extension v45.

Thanks!

**Comment by dalpat** [comment] 2021-11-11 06:39
Can be closed as the issue is Resolved with the new update. Confirmed in my ubuntu 21.10 Gnome 40.4.0

**Comment by MarkoShiva** [comment] 2021-12-11 02:45
idiots.

**Closed** 2022-04-09 18:34 UTC
Labels: bug
