### ISSUE TITLE
Videos in Chrome cannot be made full screen if dash to panel is enabled

### ISSUE THREAD

**Issue by shaoormunir** [home-sweet-gnome/dash-to-panel#862] opened 2020-02-09 11:22 UTC
I am facing an issue while playing videos in chrome when dash to panel is enabled. Videos in chrome can not go full screen when dash to dock extension is enabled. If either the extension is disabled or the chrome window is not maximized, this issue does not happen. However, as soon as the chrome window is maximized, the videos refuse to become full screen. Here is a video showing the issue in action (https://imgur.com/a/CMC85Uy). This is happening on every video playing site.

I am running Gnome 3.34.3 on Fedora 31. I have tried the latest version of dash to dock from gnome extensions website and also built from github source. Here is a link to the settings file (https://drive.google.com/file/d/18xTQqB5Iz_zHdzcDBTO7COlDRfQyYGZZ/view?usp=sharing)

**Comment by ppd1990** [comment] 2020-02-11 15:43
A similar problem in an extension that modifies the top bar: https://github.com/mlutfy/hidetopbar/issues/203

**Comment by charlesg99** [comment] 2020-02-11 18:58
Any chance you could give more details on you system? I'm on gnome 3.34.3 (xorg and nvidia drivers) as well but can't reproduce this using your settings. Thanks!

**Comment by shaoormunir** [comment] 2020-02-11 19:01
I am using Wayland and an intel graphics card on a Late 2017 HP Spectre Laptop. I'll test it out on Xorg and see if the problem persists.

**Comment by saboya** [comment] 2020-02-22 18:59
I don't have this issue, using Xorg on Nvidia or Intel, so might be exclusive to Wayland setups.

**Comment by AbzHussain** [comment] 2020-03-09 12:47
Having this exact same problem as the OP. This occurs for any 'chromium' based browser. Chromium, Chrome and Vivaldi. It does not happen with Firefox. Im using Manjaro 19 and Gnome 3.34.4
I also had this exact same problem on POPos 19.10. 
Disabling the extension solves the issue as does having the window unmaximized as the OP pointed out.

**Comment by jderose9** [comment] 2020-03-09 17:47
So far I am unable to reproduce this. I tried Fedora 30 with 3.22 and Fedora 31 with 3.34.2 and 3.34.4 and @shaoormunir's settings file and going fullscreen on a video in Chromium 79.0.3945.130 and everything is working fine for me.

**Comment by AbzHussain** [comment] 2020-03-09 20:16
I just installed the extension on Fedora 31 with 3.34.4 and can confirm full screen is working on chromium. This is on a Dell venue pro 11 vpro. 
The machine I am having problems on is a Thinkpad X1 carbon 3rd Gen. Its definitely the extension causing the issue as when it is disabled the fullscreen works.
Any idea what it could be?

**Comment by jderose9** [comment] 2020-03-09 21:58
It's possible that the issue is within Mutter and doesn't present itself under the default Gnome UI layout.

@AbzHussain Can you please try to identify any differences between the two systems? Which graphics drivers are you using for each? Can you switch between Xorg/Wayland to see if that changes anything? Do you have a difference in hardware acceleration being enabled on either?

Can you also try different configurations of dash-to-panel - Does it happen with the bar in the top position? What about hidden via intellihide? With window previews disabled? Does it happen whether Chromium window is maximized before going into full screen?

**Comment by AbzHussain** [comment] 2020-03-10 08:14
Its intellihide - thats the problem.
Extension works in fullscreen now with intellihide disabled. As soon as its re-enabled the fullscreen stops working.
I tested all the individual settings in the intellihide menu and that didnt make a jot of difference. Setting intellihide to default didnt make a difference too.
It only works on my thinkpad x1 with intellihide disabled - i can live with that though.
This was tested in Manjaro 19 only though. Not on Fedora 31 or Pop os. I dont have access to those machines till i get home.

**Comment by jderose9** [comment] 2020-03-10 14:36
@AbzHussain Let us know what happens when you test on the other devices.

Does this happen with intellihide regardless of whether the panel is visible or hidden at the time you trigger full screen mode?

**Comment by AbzHussain** [comment] 2020-03-10 14:41
@jderose9 I will do.
As for the answer to your question, it happens regardless.

**Comment by charlesg99** [comment] 2020-03-10 14:50
Hello AbzHussain, I can't reproduce the issue on my system, but I added a fix to the master branch that might help, could you give it a try? Thanks!

**Comment by AbzHussain** [comment] 2020-03-10 15:31
@charlesg99 
Hi Charles. 
Still the same, works ok when intellihide is disabled, as as it is re-enabled then fullscreen stops working. Thats still on my manjaro 19 thinkpad. Wont have access to the other systems for a while yet.
Like i said Im not too bothered with intellihide disabled, i can use it this way, not a big deal.

**Comment by AbzHussain** [comment] 2020-03-10 20:20
@jderose9 @charlesg99 
Ok, so i just tested intellihide on Fedora 31, gnome 3.34.4, Dell venue pro 11. With intellihide ENABLED full screen is available on both Chromium and Firefox (Firefox was never an issue). No tinkering with settings, just enabled it and regardless of maximized windows or not, panel in veiw or not, fullscreening a youtube video works fine.
I dont have access to the POPos but im just going to assume that disabling intellihide would cure the issue as it did on Manjaro 19.

**Comment by AlexanderMelde** [comment] 2020-04-08 09:53
just another workaround as i had the same issue as in the video: 
Don't maximize your chrome window. 
If it is manually resized at least a pixel smaller than maximum, Fullscreen will work as usual.

**Comment by charlesg99** [comment] 2020-07-03 01:06
I'm going to close this for now, I can't reproduce the issue using the latest chromium and dash to panel version, so let us know if you find a way to reliably reproduce this on more than one machine using vanilla gnome-shell installations. Thanks!

**Closed by charlesg99** 2020-07-03 01:06 UTC
