### ISSUE TITLE
Dash to Panel is not centered correctly on certain floating panel shell themes 

### ISSUE THREAD

**Issue by rdgh8** [home-sweet-gnome/dash-to-panel#1487] opened 2021-10-16 05:09 UTC
**Describe the bug**

Dash to Panel is not correctly centered on certain shell themes that have a floating panel, namely the [Flat-Remix](https://www.gnome-look.org/p/1013030) theme. 

**Linux distribution and version**

Reproducible on Pop!_OS 21.04, Ubuntu 21.04 VM, Pop!_OS 21.10 Beta VM, Ubuntu 21.10 VM

**GNOME Shell version**

GNOME Shell 3.38.4, GNOME Shell 40.5

**Dash-to-Panel version**

42, 43

**Where was Dash-to-Panel installed from?**

Gnome extensions website

**Screenshots / Video captures**

![image](https://user-images.githubusercontent.com/66289396/137574448-a0246d76-e1b2-4505-b54e-80d45736f7ed.png)

**Additional Info**

Would be cool if Dash to Panel could have a floating panel option, instead of having to rely on a shell theme. See how ZorinOS does it with their fork of Dash to Panel:
![image](https://user-images.githubusercontent.com/66289396/137574650-85b08f68-fe10-47d9-be4f-1c8179ced0fc.png)

**Comment by shinysocks** [comment] 2022-01-23 04:10
also having this issue with ubuntu 20.04 using flat-remix theme.

**Comment by v1per404** [comment] 2022-03-25 21:40
It's not a bug.

And this can be simply fixed by changing the CSS sheet in the theme.
Change the "TOP BAR" portion of the CSS as follow, would get you what you want:

/* TOP BAR */
#panelBox {
  padding-top: 0.35em; 
  padding-bottom: 0.35em; 
  padding-right: 0.9em;
  text-align: center;
  background: transparent; }

**Comment by charlesg99** [comment] 2022-04-09 18:32
[Flat remix](https://aur.archlinux.org/packages/flat-remix-git) works fine for me on v46.

**Closed by charlesg99** 2022-04-09 18:32 UTC
Labels: bug

**Comment by Struki84** [comment] 2024-05-27 10:10
@v1p0r How is this not a bug? Same issue, Gnome 42
