### ISSUE TITLE
[Feature request] Option to place 'dash-to-panel' on a new separate panel (or dock)

### ISSUE THREAD

**Issue by tnilzon** [home-sweet-gnome/dash-to-panel#459] opened 2018-09-11 07:13 UTC
An option to have the 'dash-to-panel' on a separate vertically aligned panel (or dock) on the left or right side of the desktop or as a new horizontal panel (or dock) at the bottom of the desktop would be great. It would be similar to the extension 'dash-to-dock', but with all of the superior features that comes with 'dash-to-panel' (only need to contain favourites and running apps icons). The Gnome main panel would be left on top of the screen (with its optional extensions) as it originally is.

**Comment by chrisjbillington** [comment] 2019-06-29 17:07
I would also like to see this.

The gnome main panel can start to get pretty crowded with extensions, and having a single panel dedicated to window management is pretty nice and clean. It consumes more screen real estate, but it's worth it on large screens compared to trying to put everything in one panel.

This is particularly useful when using the 'ungroup windows' option with window titled displayed, since that makes the tasks take up quite a bit more space.

At this point one might ask "why use dash2panel at all, when you're basically describing dash2dock? Why not just use that?" The answer for me is that dash2dock doesn't support ungrouping windows and displaying window titles.

**Comment by charlesg99** [comment] 2019-08-16 02:00
I'll close this one since it's a duplicate of #457. Thanks!

**Closed by charlesg99** 2019-08-16 02:00 UTC
