### ISSUE TITLE
notification badges not working, but competition can do it.

### ISSUE THREAD

**Issue by NickBelhomme** [home-sweet-gnome/dash-to-panel#2071] opened 2024-04-03 13:56 UTC
* nothing reported in the log
* latest version V62.

Stale ticket found: https://github.com/home-sweet-gnome/dash-to-panel/issues/1695

**Describe the bug**
Notification badges are not shown , however competing extensions can do it.
See the Signal badge indicating 2 messages are waiting.
The extension that can do it https://extensions.gnome.org/extension/615/appindicator-support/
This extension is also mentioned on this project README file.

**Linux distribution and version**
openSUSE Tumbleweed x86_64 

**GNOME Shell version**
GNOME 46.0

**Dash-to-Panel version**
V62

**Where was Dash-to-Panel installed from?**
[extension ](https://extensions.gnome.org/local/)

**Screenshots / Video captures**

example for signal. But discord applies as well.
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/312003/2ac65932-e0e5-4821-9c2a-b3673ea08b4f)

**Additional Info**
If one extension can do it (for signal, discord, etc), then probably dash to panel can also do it.

**Comment by tekstryder** [comment] 2024-04-05 11:16
Duplicate of #1695. Please close as such.

**Closed** 2024-04-09 02:15 UTC
Labels: bug
