### ISSUE TITLE
Object 0x142077f7e908 is not a subclass of GObject_Object, it's a Object

### ISSUE THREAD

**Issue by miberecz** [home-sweet-gnome/dash-to-panel#1599] opened 2022-04-02 06:13 UTC
I have just installed the latest version yesterday (with the Gnome 42 fix) manually on the Ubuntu 22.04 Beta, and its works until the first restart (or probably logout) then I get this error:
![image](https://user-images.githubusercontent.com/13240971/161369461-838cf2bc-e56c-4226-8424-b733e025aa9a.png)
Any suggestion what can I do? 
How do I gather more info about this?

**Comment by philippun1** [comment] 2022-04-03 11:05
What Gnome 42 fix did you use and how did you install it?
I installed the latest master branch and it works just fine on Ubuntu 22.04.

**Comment by flpva** [comment] 2022-04-03 12:09
> What Gnome 42 fix did you use and how did you install it? I installed the latest master branch and it works just fine on Ubuntu 22.04.
Latest brach spamed syslog 
`Object .Gjs_dash-to-panel_jderose9_github_com_appIcons_TaskbarAppIcon (0x5637cf72c710), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.`

**Comment by charlesg99** [comment] 2022-04-03 14:07
Seems like gnome-shell are [using new utility methods](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/26235bbe5433c48b81bd3917aaf9ef14ff1929b2) to handle signals disconnect, so we'll have to keep an eye opened for overridden signals, like the one reported by @flpva. This should now be fixed on the master branch, thanks!

**Closed by charlesg99** 2022-04-03 14:07 UTC

**Comment by MostHated** [comment] 2023-08-24 14:13
What is the chance that this is caused by the same thing and that issue is ongoing/reintroducted? My logs are loaded up with hundreds/thousands of these messages, which seemed to have started yesterday or the day before, causing my syslog to reach near 100mb from just these messages. I tried removing the plugin and adding it back, but it seems to have persisted.

```
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: == Stack trace for context 0x55cf0d7ee4a0 ==
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #0   7ffefbb28640 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:687 (1adfb03bc150 @ 25)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #1   7ffefbb28730 b   resource:///org/gnome/shell/ui/environment.js:223 (1adfb03c85b0 @ 570)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #2   7ffefbb28800 b   resource:///org/gnome/shell/ui/environment.js:388 (1adfb03c8d80 @ 23)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #3   7ffefbb288d0 b   /home/mosthated/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:471 (1a8a8137d100 @ 372)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #4   7ffefbb289a0 b   /home/mosthated/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:781 (1a8a81378600 @ 133)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #5   7ffefbb28af0 b   /home/mosthated/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:759 (1a8a81378560 @ 1503)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #6   7ffefbb28ba0 b   /home/mosthated/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:677 (1a8a813783d0 @ 17)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #7   7ffefbb28c80 b   self-hosted:1178 (1adfb03b0a10 @ 454)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #8   55cf151f9e48 i   resource:///org/gnome/shell/ui/main.js:773 (1adfb03ecce0 @ 243)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #9   55cf151f9d88 i   /home/mosthated/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1333 (1a8a81379290 @ 48)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: Object St.DrawingArea (0x55cf12cda9a0), has been already disposed ��� impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #10   55cf151f9c90 i   /home/mosthated/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:936 (1a8a81378790 @ 2290)
Aug 24 09:04:43 mosthated-pc gnome-shell[3300]: #11   55cf151f9bd8 i   resource:///org/gnome/shell/ui/appDisplay.js:3171 (3027aedca8d0 @ 35)
```
