### ISSUE TITLE
Overshooting X-button (close window) top right corner on maximized windows

### ISSUE THREAD

**Issue by dogmax** [home-sweet-gnome/dash-to-panel#598] opened 2019-03-13 23:46 UTC
When you put the cursor is as far as possible into the top right corner, it overshoots the X-button that closes the window and doesn't close the window upon clicking. (maximized windows)

Why does this need to be fixed?

When a window is maximized, it's a better user experience for the user to be able to flick the cursor all the way to the corner without having to aim too precisely for the X button.

Suggested fix:

"extend" the trigger area of the X button to to the top edge and the right edge so that the user will never overshoot the button when the window is maximized. No need for visual changes to the theme. Just extend the trigger area by the small amount that's needed.

See picture: https://i.imgur.com/ytDTTZV.png

This has been in Windows for decades.

Thank you for an otherwise awesome extension.

**Comment by charlesg99** [comment] 2019-03-14 11:55
Hello dogmax! I can't reproduce this with the arc-dark and adwaita themes. Maximized windows are properly closed when clicking with the cursor being on the top rightmost pixel. What theme are you using? Also I'm not sure why this issue would be related to dash-to-panel as we don't interfere with that. Are you saying that this doesn't happen when the extension is disabled (on a secondary monitor where there is no default gnome-shell top bar)? Thanks!

**Comment by charlesg99** [comment] 2019-04-02 01:13
Closing as this is unrelated to dash to panel. Thanks!

**Closed by charlesg99** 2019-04-02 01:13 UTC
