### ISSUE TITLE
Dash to Panel prevents screen auto dim/blank & lock screen display

### ISSUE THREAD

**Issue by msmith3392** [home-sweet-gnome/dash-to-panel#1020] opened 2020-05-23 18:26 UTC
**Describe the bug**
With Dash to Panel installed, screen auto-dim after inactivity and screen blank do not work. Also, lock screen fails to be displayed through either auto lock after screen blank or manually initiated through Super+L or system menu -> Lock. Instead, the desktop session reloads.

**Linux distribution and version**
Ubuntu 20.04 with kernel v. 5.4.0-31-generic

**GNOME Shell version**
GNOME Shell 3.36.2

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
https://extensions.gnome.org/ + Gnome Shell Integration browser add-on

**Comment by Polynomendivision** [comment] 2020-05-23 19:35
Can confirm the Bug

Linux Distro Ubuntu 20.04
5.4.0-31-generic
Gnome Shell 3.36.2
Dash-to-Panel Version 37

My guess: it has something to do with the latest update of Ubuntu to 5.4.0-31-generic - before that I didn't noticed any issues

**Comment by vineet8588** [comment] 2020-05-23 20:09
Same issue here.

**Comment by theol0403** [comment] 2020-05-23 20:51
I'm having the same issue. When the screen auto dims or I lock the desktop, the display manager seems to crash. I see my computer's boot logo flash onto the screen for a few seconds, and then I land on the logon screen you get after booting. After unlocking, I am greeted with a new desktop session.

Pop!_OS 20.04 LTS x86_64
5.4.0-7629-generic
Gnome Shell 3.36.2

**Comment by gittyupper** [comment] 2020-05-24 02:18
Same issue. I did discover that, if I deleted the extension and reinstalled it, lock screen would once again function. Otherwise, I get the session restart as described by others.

20.04
5.4.0-31
GNOME Shell 3.36.2
DTP v 37

**Comment by lisufabuntuman** [comment] 2020-05-24 12:50
Same issue … 
---
System: Ubuntu 20.04 
GNOME Shell 3.36.2
uname -a: 5.4.0-31-generic
---
The version from git, install today, is good.

**Comment by 4ndt3s** [comment] 2020-05-25 19:33
Same issue with v37 using Ubuntu 20.04. If the extension is disabled and enabled again (with gnome-tweaks -> extensions) lock screen works until next reboot.

**Comment by charlesg99** [comment] 2020-05-25 23:51
Hello, sounds a lot like #1019 and all its linked issues, although I can't reproduce this on a fully updated Ubuntu 20.04 with v37 (X.org and Wayland). Could you guys provide more info on your setups so we can find some commonalities? Thanks!

**Comment by GuilleW** [comment] 2020-05-26 07:39
Hi ! Same here :

#### Linux distribution and version
- Debian GNU/Linux bullseye/sid

#### GNOME Shell version
- GNOME Shell 3.36.2

#### Dash-to-Panel version
- 37

#### Where was Dash-to-Panel installed from?
- [Gnome Shell Integration browser add-on](https://extensions.gnome.org/)

**Comment by GuilleW** [comment] 2020-05-26 07:56
Here's log from `tail -f -n 50 /var/log/messages` while pressing **Super**+**L**

```
May 26 09:51:49 debian gnome-shell[28254]: clutter_actor_set_child_below_sibling: assertion 'sibling->priv->parent == self' failed
May 26 09:51:49 debian gnome-shell[28254]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 776]: reference to undefined property "_delegate"
May 26 09:51:49 debian kernel: [12038.431588] gnome-shell[28254]: segfault at 7373 ip 00007f860783246a sp 00007ffeb164c2c0 error 4 in libst-1.0.so[7f8607813000+4a000]
May 26 09:51:49 debian kernel: [12038.431593] Code: 48 83 c3 01 41 39 9f 30 01 00 00 0f 8e 2f 01 00 00 49 8b 87 28 01 00 00 48 8d 35 d6 f5 02 00 48 8b 2c d8 48 8b 45 00 48 8b 00 <4c> 8b 20 4c 89 e7 e8 3b 28 fe ff 85 c0 74 c7 41 80 7c 24 0a 00 0f
May 26 09:51:50 debian gsd-media-keys[1430]: Couldn't lock screen: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
May 26 09:51:50 debian gsd-media-keys[1430]: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L’interface « org.gnome.Shell » n’existe pas pour l’objet à l’emplacement /org/gnome/Shell
May 26 09:51:50 debian gnome-shell[28874]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
May 26 09:51:50 debian gnome-shell[28874]: Will monitor session 2
May 26 09:51:51 debian tracker-extract[28918]: Set scheduler policy to SCHED_IDLE
May 26 09:51:51 debian tracker-extract[28918]: Setting priority nice level to 19
May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:hibernate
May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:rfkill
May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:playback-random
May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:playback-repeat
May 26 09:51:52 debian gnome-shell[28874]: gvc_mixer_stream_get_port: assertion 'stream->priv->ports != NULL' failed
May 26 09:51:53 debian gnome-shell[28874]: GNOME Shell started at Tue May 26 2020 09:51:51 GMT+0200 (CEST)
May 26 09:51:53 debian gnome-shell[28874]: Registering session with GDM
```

**Comment by lisufabuntuman** [comment] 2020-05-26 09:42
Hey,

on my system is Wayland with v37 … 
the version from git 9999 with Wayland works fine.


Am Montag, den 25.05.2020, 16:51 -0700 schrieb Charles Gagnon:
> Hello, sounds a lot like #1019 and all its linked issues, although I
> can't reproduce this on a fully updated Ubuntu 20.04 with v37 (X.org
> and Wayland). Could you guys provide more info on your setups so we
> can find some commonalities? Thanks!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
-- 
Mfg …
Buntuknilchkasten … 

* Ubuntu-20.04 
* GNOME-3.36

**Comment by charlesg99** [comment] 2020-05-26 12:58
Here is yet another related issue on gnome-shell's Gitlab https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2823.
 
@GuilleW, could you provide the log entries that came before the gnome-shell segfault (more is better here...)? There probably is an error in there. Also, after the crash please run `coredumpctl dump` and post the output. Thanks!

**Comment by GuilleW** [comment] 2020-05-26 13:40
1. I removed Dash to panel
2. open terminal with `tail -f /var/log/messages`
3. reinstall D2P (no error)
4. **Super** + **L** (same error as my post before, no more info)

`coredumpctl` is not found on my Debian. `apt install coredumpctl` return package not found.

**Comment by msmith3392** [comment] 2020-05-26 14:50
Attached are the logs for a crash when attempting to lock with Super+L and the output of a coredump immediately afterwards.
[d2p.log](https://github.com/home-sweet-gnome/dash-to-panel/files/4682994/d2p.log)
[d2p-coredump.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/4682999/d2p-coredump.txt)

**Comment by eshcheglov** [comment] 2020-05-26 18:14
Some weird observation: opening a Telegram Desktop application window increase chance of gnome-shell segfault. 
Other GUI application also may lead to crash during screen lock probably, but with Telegram I can reproduce it almost every time. 

So, some simple s.t.r.:
- Enable only "Dash to Panel" extension 
- Open "Telegram" application
- Lock screen

I'll try to play with other GUI apps too and maybe return to this tread with more info

Oh god, bugs in gnome-shell become more and more ridiculous

**Comment by kindaran** [comment] 2020-05-26 19:55
> Here's log from `tail -f -n 50 /var/log/messages` while pressing **Super**+**L**
> 
> ```
> May 26 09:51:49 debian gnome-shell[28254]: clutter_actor_set_child_below_sibling: assertion 'sibling->priv->parent == self' failed
> May 26 09:51:49 debian gnome-shell[28254]: JS WARNING: [resource:///org/gnome/shell/ui/popupMenu.js 776]: reference to undefined property "_delegate"
> May 26 09:51:49 debian kernel: [12038.431588] gnome-shell[28254]: segfault at 7373 ip 00007f860783246a sp 00007ffeb164c2c0 error 4 in libst-1.0.so[7f8607813000+4a000]
> May 26 09:51:49 debian kernel: [12038.431593] Code: 48 83 c3 01 41 39 9f 30 01 00 00 0f 8e 2f 01 00 00 49 8b 87 28 01 00 00 48 8d 35 d6 f5 02 00 48 8b 2c d8 48 8b 45 00 48 8b 00 <4c> 8b 20 4c 89 e7 e8 3b 28 fe ff 85 c0 74 c7 41 80 7c 24 0a 00 0f
> May 26 09:51:50 debian gsd-media-keys[1430]: Couldn't lock screen: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
> May 26 09:51:50 debian gsd-media-keys[1430]: Failed to grab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L’interface « org.gnome.Shell » n’existe pas pour l’objet à l’emplacement /org/gnome/Shell
> May 26 09:51:50 debian gnome-shell[28874]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
> May 26 09:51:50 debian gnome-shell[28874]: Will monitor session 2
> May 26 09:51:51 debian tracker-extract[28918]: Set scheduler policy to SCHED_IDLE
> May 26 09:51:51 debian tracker-extract[28918]: Setting priority nice level to 19
> May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:hibernate
> May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:rfkill
> May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:playback-random
> May 26 09:51:51 debian gsd-media-keys[1430]: Failed to grab accelerator for keybinding settings:playback-repeat
> May 26 09:51:52 debian gnome-shell[28874]: gvc_mixer_stream_get_port: assertion 'stream->priv->ports != NULL' failed
> May 26 09:51:53 debian gnome-shell[28874]: GNOME Shell started at Tue May 26 2020 09:51:51 GMT+0200 (CEST)
> May 26 09:51:53 debian gnome-shell[28874]: Registering session with GDM
> ```

Seeing the nearly exact same thing in syslog (re: segfault on libst). Also ubuntu 20.04, shell 3.36.2, extension version 37 installed from gnome extensions browser

**Comment by 4ndt3s** [comment] 2020-05-26 21:28
It seems a gnome-shell [bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2757). It is already solved (merged) but not released yet.

**Comment by kindaran** [comment] 2020-05-26 21:30
> It seems a gnome-shell [bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2757). It is already solved (merged) but not released yet.

I was just about to add that this is happening in more than one extension, not just this dash to panel. Will await further updates!! :)

**Comment by charlesg99** [comment] 2020-05-26 22:31
Yes @msmith3392 log pretty much confirms that it is a duplicate of #976 as the core dump is the same. Closing this one as well, thanks!

**Closed by charlesg99** 2020-05-26 22:31 UTC

**Comment by GuilleW** [comment] 2020-06-09 20:40
Just updating to last version of gnome-shell-common. **It's fixed.** :tada: 
`Dépaquetage de gnome-shell-common (3.36.3-1) sur (3.36.2-1) ...`
