### ISSUE TITLE
Icon misplacement

### ISSUE THREAD

**Issue by vozeo** [home-sweet-gnome/dash-to-panel#616] opened 2019-04-04 08:49 UTC
Recently I updated gnome, the icons are misplaced.
![Screenshot from 2019-04-04 16-38-41](https://user-images.githubusercontent.com/34589749/55542255-38b8ee80-56f9-11e9-83f1-a0db1693d1cf.png)
![Screenshot from 2019-04-04 16-37-15](https://user-images.githubusercontent.com/34589749/55542261-3b1b4880-56f9-11e9-843d-88debacbabf7.png)
![Screenshot from 2019-04-04 16-41-54](https://user-images.githubusercontent.com/34589749/55542277-44a4b080-56f9-11e9-9025-1aad2a984692.png)
I use manjaro. It used to be normal.
Thanks! :)

**Comment by charlesg99** [comment] 2019-04-04 11:30
Hello vozeo, thank you for reporting this. This probably happened when you updated arc-theme? Their new version breaks dash-to-panel and dash-to-dock (NicoHood/arc-theme#217 and NicoHood/arc-theme#220). A fix for it was recently added to dash-to-panel to work around the issue, could you please [install the latest version](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) and confirm that it restores the correct style? Thanks!

**Comment by JouHouFin** [comment] 2019-04-04 12:11
Hello, I'm having a similar problem which appeared after I upgraded to Ubuntu 19.04 and consequently Gnome 3.32.0. My screen is a 14" 2560x1440 and I'm using the Yaru theme. 

App icons and running indicators are placed too low (pic one). If I set the app Icon padding to bigger than four, the indicator disappears completely (pic two). 
![Screenshot from 2019-04-04 15-01-26](https://user-images.githubusercontent.com/46995443/55554468-875f8c00-56eb-11e9-9446-0e3aa4b42b3a.png)
![Screenshot from 2019-04-04 15-09-03](https://user-images.githubusercontent.com/46995443/55554518-a3fbc400-56eb-11e9-89f4-299378eb0efd.png)

**Comment by charlesg99** [comment] 2019-04-04 23:51
@JouHouFin Are you on the latest development version of dash to panel (as per my previous comment)? Thanks!

**Comment by JouHouFin** [comment] 2019-04-06 15:25
> @JouHouFin Are you on the latest development version of dash to panel (as per my previous comment)? Thanks!
I just installed the latest version from source and I can confirm that the issue is gone now.

**Comment by charlesg99** [comment] 2019-04-07 13:54
Closing this as arc-theme reverted the commit that originally caused this issue, see NicoHood/arc-theme#221. Thanks!

**Closed by charlesg99** 2019-04-07 13:54 UTC
