### ISSUE TITLE
Unable to start dash-to-panel gnome-shell 3.30.1+29+g38c1ebba6-1

### ISSUE THREAD

**Issue by mikey242** [home-sweet-gnome/dash-to-panel#476] opened 2018-10-10 08:43 UTC
Hello,

I have been using dash-to-panel on Arch for a few weeks now without issue. This morning I updated gnome shell to 3.30.1+29+g38c1ebba6-1. After a restart I noticed that all the panel content is squeezed into the left corner. I tried uninstalling it and even re-installing without any change. I checked gnome-tweaks and saw that there was an error saying it was unable to load the extension. When I checked the journalctl I noticed these lines:

Oct 10 10:28:58 Arch-PC gnome-shell[2675]: GNOME Shell started at Wed Oct 10 2018 10:28:57 GMT+0200 (CEST)
Oct 10 10:29:35 Arch-PC gnome-shell[2675]: Extension "dash-to-panel@jderose9.github.com" had error: Error: No signal 'allocate' on object 'Gjs_Panel'

I have also noticed it sometimes says "TypeError: overview is undefined", similar to #464.

I found this thread on the Arch forums from earlier today. Not sure if it's related:
https://bbs.archlinux.org/viewtopic.php?id=241108

Edit: Just reverted back to gnome-shell-3.30.1-1 and everything works fine now.
![screenshot from 2018-10-10 10-32-10](https://user-images.githubusercontent.com/949639/46724226-dc10d580-cc79-11e8-83af-2e9b234629c1.png)

**Comment by wiktor-k** [comment] 2018-10-10 11:14
Confirmed, I have the same problem.

**Comment by hogar1977** [comment] 2018-10-10 11:41
same issue here...

**Comment by hogar1977** [comment] 2018-10-10 12:36
@mikey242

just out of curiosity, do I need to do something special for downgrading to last version of gnome-shell? After running "pacman -U gnome-shell-extensions-3.30.1-1-any.pkg.tar.xz" I get the following in the terminal, but the actual version stays the updated one, i.e. nothing really changes:

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                                                                                                           [#########################################################################################################################################] 100%
(1/1) checking package integrity                                                                                                                                                                                         [#########################################################################################################################################] 100%
(1/1) loading package files                                                                                                                                                                                              [#########################################################################################################################################] 100%
(1/1) checking for file conflicts                                                                                                                                                                                        [#########################################################################################################################################] 100%
(1/1) checking available disk space                                                                                                                                                                                      [#########################################################################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling gnome-shell-extensions                                                                                                                                                                                [#########################################################################################################################################] 100%

:: Running post-transaction hooks...
(1/2) Compiling GSettings XML schema files...
cannot provide per-desktop overrides for localised key “visible-name” in schema “org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:bla-bla-bla-code” (override file “/usr/share/glib-2.0/schemas/90_antergos_gnome.gschema.override”); ignoring override for this key.
(2/2) Arming ConditionNeedsUpdate...

I even tried to downgrade to a version 3.30.0, and still the installed version remains 3.30.1+29

Am I doing something wrong?

**Comment by mikey242** [comment] 2018-10-10 12:51
> @mikey242
> 
> just out of curiosity, do I need to do something special for downgrading to last version of gnome-shell? After running "pacman -U gnome-shell-extensions-3.30.1-1-any.pkg.tar.xz" I get the following in the terminal, but the actual version stays the updated one, i.e. nothing really changes:
> 
> :: Proceed with installation? [Y/n] y
> (1/1) checking keys in keyring [#########################################################################################################################################] 100%
> (1/1) checking package integrity [#########################################################################################################################################] 100%
> (1/1) loading package files [#########################################################################################################################################] 100%
> (1/1) checking for file conflicts [#########################################################################################################################################] 100%
> (1/1) checking available disk space [#########################################################################################################################################] 100%
> :: Processing package changes...
> (1/1) reinstalling gnome-shell-extensions [#########################################################################################################################################] 100%
> 
> :: Running post-transaction hooks...
> (1/2) Compiling GSettings XML schema files...
> cannot provide per-desktop overrides for localised key “visible-name” in schema “org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:bla-bla-bla-code” (override file “/usr/share/glib-2.0/schemas/90_antergos_gnome.gschema.override”); ignoring override for this key.
> (2/2) Arming ConditionNeedsUpdate...
> 
> I even tried to downgrade to a version 3.30.0, and still the installed version remains 3.30.1+29
> 
> Am I doing something wrong? Restarting the shell or computer does not change anything...

That's the command I ran, the only difference is that I specified the location (in cache) of the package to install:

`sudo pacman -U /var/cache/pacman/pkg/gnome-shell-3.30.1-1-x86_64.pkg.tar.xz `

**Comment by hogar1977** [comment] 2018-10-10 12:56
@mikey242

I didn't have to do that bcs I was already in that directory when I ran the command... But whatever I do, when I look at installed packages in pamac (I use Antergos, so that's my default GUI package installer) it is still the last version to which I updated yesterday. It doesn't downgrade anything. Weird. This usually works for me with no issues... And Pamac (as far as I know) has no ability for downgrading.

**Comment by work-chausat** [comment] 2018-10-10 15:39
**i have the same problem too!!!!!!!!!!!!!!!!!!!!!!!!!!**

**Comment by work-chausat** [comment] 2018-10-10 15:40
I have the same problem too!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by VxMxPx** [comment] 2018-10-10 15:46
Same here. For anyone who has this problem, downgrade gnome shell for now, using command mikey242 provided: 

`sudo pacman -U /var/cache/pacman/pkg/gnome-shell-3.30.1-1-x86_64.pkg.tar.xz`

**Comment by robvelor** [comment] 2018-10-11 01:01
@charlesg99 Thanks for looking into it, hopefully it is a quick fix.

**Comment by Bruce-YC** [comment] 2018-10-11 03:45
Same issue here... downgrading gnome-shell worked well

**Comment by charlesg99** [comment] 2018-10-11 04:42
A fix for this issue was added to master. Please let us know if you encounter any problems with it. Thanks!

**Comment by zurchpet** [comment] 2018-10-11 05:13
master indeed works on 3.30.1+29+g38c1ebba6-1

Thanks for the fix!

**Comment by work-chausat** [comment] 2018-10-11 06:07
**the fix works now, thank charlesg99, well done!!**

**Comment by mikey242** [comment] 2018-10-11 07:36
Great, it's working fine now. Thanks for the quick fix!

**Comment by vieruuuu** [comment] 2018-10-11 12:15
I updated gnome-shell and everything works for now

**Comment by charlesg99** [comment] 2018-10-11 14:03
I realized that the icon paddings were a bit off after the fix. The styling was adjusted on master. Thanks for the feedback!

**Closed by charlesg99** 2018-10-11 14:03 UTC

**Comment by charlesg99** [comment] 2018-10-11 15:02
@work-chausat What do you mean not centered? What gnome-shell version are you on? What dash-to-panel size settings are you using?

ubuntu 18.04:
![image](https://user-images.githubusercontent.com/33044886/46813596-011e4a80-cd45-11e8-9a80-f2d1657f08ef.png)

**Comment by work-chausat** [comment] 2018-10-11 15:28
> @work-chausat What do you mean not centered? What gnome-shell version are you on? What dash-to-panel size settings are you using?
> 
> ubuntu 18.04:
> ![image](https://user-images.githubusercontent.com/33044886/46813596-011e4a80-cd45-11e8-9a80-f2d1657f08ef.png)

use panel size 39, margin 4, padding 4 to try!

**Comment by charlesg99** [comment] 2018-10-11 15:37
![image](https://user-images.githubusercontent.com/33044886/46815972-fca86080-cd49-11e8-89bc-2b9c2d3a5c4d.png)

**Comment by work-chausat** [comment] 2018-10-12 02:40
[
![2018-10-12 10-34-27](https://user-images.githubusercontent.com/29337670/46844765-0219af80-ce0b-11e8-869f-c5d8861218fe.png)
![2018-10-12 10-35-21](https://user-images.githubusercontent.com/29337670/46844767-0219af80-ce0b-11e8-9851-c749c056b0f4.png)
]

**Comment by work-chausat** [comment] 2018-10-12 02:47
4b639ec is ok, 55da368 is  too ugly, the icons in 55da368 are not centered!!!

**Comment by DuckThom** [comment] 2018-10-12 07:17
I'm experiencing the same issue with the non-centered icons. I'm on the same version and OS as @work-chausat 
The icons seem to be offset a bit too far to the right.

![](https://img.tjwiringa.nl/view/ouNdAO)

**Comment by charlesg99** [comment] 2018-10-12 13:14
Yeah I can reproduce, the new baseicon allocation introduced in 3.30.1+29+g38c1ebba6-1 doesn't allow non squared layout. I added a fix to add the side paddings back, without distorting the baseicon.

**Comment by work-chausat** [comment] 2018-10-12 13:42
b8ab43f is much better, but it still a little to the right, 1px perhaps.

![2018-10-12 21-41-55](https://user-images.githubusercontent.com/29337670/46872777-aaf5f800-ce67-11e8-8bbe-2dbb16c3e73e.png)

**Comment by DuckThom** [comment] 2018-10-12 13:44
It's indeed much better now, however there seems to be a vertical line when there are 2 windows open of the same app

![](https://img.tjwiringa.nl/view/iJVApm)

**Comment by charlesg99** [comment] 2018-10-12 14:55
Ok please try again, I believe that, this time, I tested everything :)

**Comment by DuckThom** [comment] 2018-10-12 15:11
Yep, looks good now :smile: 

![](https://img.tjwiringa.nl/view/cpTO-W)
