### ISSUE TITLE
Shell crash on click, Pop OS 20.04

### ISSUE THREAD

**Issue by sudoWiz** [home-sweet-gnome/dash-to-panel#1007] opened 2020-05-15 05:43 UTC
**Describe the bug**
Occasionally when I click the upper right corner to view my wifi settings or volume or other things in this menu, instead of opening, the whole system freezes, and after a couple of seconds, the shell restarts and everything is normal. This seems to happen once per boot.

**Linux distribution and version**
Pop OS 20.04, Pop Shell, tiling enabled

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
extensions.gnome.org

**Additional Info**
Sound Input & Output Device Chooser is also installed

**Comment by charlesg99** [comment] 2020-05-18 01:17
Hello, this is a duplicate of #950, which is fixed on the latest gnome-shell version. Thanks!

**Closed by charlesg99** 2020-05-18 01:17 UTC
Labels: bug
