### ISSUE TITLE
Hide items from view in some kind of box

### ISSUE THREAD

**Issue by aindriu80** [home-sweet-gnome/dash-to-panel#1117] opened 2020-08-02 20:55 UTC
Hi,

Dash To Panel is great but I now have a lot of icons of applications on the panel and I would like to tidy things up a bit.
Here is my dash to panel
https://i.imgur.com/JBsWvFC.png 

Is it possible to move the icons into some kind of box container where they could be accessed via clicking on an Up arrow.  Something similar to the taskbar in windows? I use Caffeine and the weather every day but I don't really need to see the other items directly on the taskbar even if I use them every day.

**Comment by jderose9** [comment] 2020-08-02 21:59
Hello, this is a duplicate of #438. Thanks!

**Closed by jderose9** 2020-08-02 21:59 UTC
Labels: enhancement
