### ISSUE TITLE
no window preview for Firefox on Wayland

### ISSUE THREAD

**Issue by simonbcn** [home-sweet-gnome/dash-to-panel#605] opened 2019-03-22 11:25 UTC
```
Arch Linux
GNOME Shell 3.32.0 on Wayland
gnome-shell-extension-dash-to-panel-git version 19.r11.gb3aecfc-1
```
I execute Firefox with the environment variable `MOZ_ENABLE_WAYLAND=true` but in this case when I put the cursor over the icon it shows an empty thumbnail:
![captura_20190322_121742](https://user-images.githubusercontent.com/428231/54819850-73ed0380-4c9d-11e9-8367-32aa6818a2e7.png)

**Comment by charlesg99** [comment] 2019-03-23 02:10
Hello simonbcn, thank you for the report. I currently can't reproduce this on Fedora rawhide (3.32) as the Firefox preview appears correctly on wayland and xorg (even when setting `MOZ_ENABLE_WAYLAND=true`). Do you see errors in your logs perhaps? I should soon update my arch to 3.32, maybe I'll be able to reproduce it then. Thanks!

**Comment by simonbcn** [comment] 2019-03-23 15:07
Hi,
Have you tested that your Firefox really runs on Wayland? The best way is using [the Looking Glass tool](https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Does_your_application_run_on_Wayland_natively.2C_or_uses_XWayland_.28X11_compatibility_layer.29.3F).

**Comment by simonbcn** [comment] 2019-03-23 15:19
I don't see any error on log. What unit I have to list?

**Comment by charlesg99** [comment] 2019-03-23 15:41
Hello simonbcn, yes it seems like it is running on Wayland:

![image](https://user-images.githubusercontent.com/33044886/54868138-a9f2bc00-4d5f-11e9-972d-9e0317fbbda9.png)

As for the logs, I would just run `journalctl -f -o cat` and see if something interesting shows up when gnome-shell starts or when a firefox preview opens. Thanks!

**Comment by simonbcn** [comment] 2019-03-24 15:34
No output in log.

**Comment by charlesg99** [comment] 2019-04-02 12:04
Are you using the extension Alternatetab? I'm curious to know if the Firefox preview appears correctly in the alt-tab box? Or in dash-to-dock window preview? Just trying to establish if this is specific to dash-to-panel. Thanks!

**Comment by simonbcn** [comment] 2019-04-02 12:27
`dash-to-dock` fails too.

**Comment by thebitstick** [comment] 2019-04-24 13:12
On Fedora 30, GNOME 3.32, I get the same issue with Firefox on Wayland under the GNOME Wayland session. lg says Firefox is running on Wayland. Affected on both dash-to-panel and dash-to-dock. This may be a Firefox issue.

**Comment by charlesg99** [comment] 2019-06-23 00:14
I'm going to close this as I couldn't reproduce the issue and it isn't related to dash to panel. If this still happens, I would say the best bet to get this solved would be to bring the issue up to the [mutter's people](https://gitlab.gnome.org/GNOME/mutter/issues). Thanks!

**Closed by charlesg99** 2019-06-23 00:14 UTC
