### ISSUE TITLE
When unlocking lock screen maximized windows sometimes overlap the panel

### ISSUE THREAD

**Issue by skontar** [home-sweet-gnome/dash-to-panel#1252] opened 2021-01-02 21:38 UTC
**Describe the bug**
When unlocking lock screen, sometimes (5-10% times?) some maximized windows get maximized also under the panel, and sometimes they do not. Seems like a race condition when panel re-appears on unlock.

**Linux distribution and version**
Fedora 33

**GNOME Shell version**
GNOME Shell 3.38.2

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Additional Info**
It is easier to notice if the panel is transparent, however it also happens when it is opaque.

It is easier to test when "Unblank lock screen" extensions is installed, because you can lock without screen turning off - or you have to unlock really quickly :smile: before it turns off. I have checked that it does also happen with no extensions other than dash-to-panel. It is just convenient. 

I have noticed similar issues with different extensions (their re-enabling after unlock seems to induce race conditions), so it may be caused by newer versions of GNOME shell.

**Comment by skontar** [comment] 2021-01-02 22:07
It does not seem to happen on XOrg, only Wayland. On XOrg I can sometimes see the problem, but only for a fraction of a second, then it fixes itself.

It is most common with Firefox, sometimes Terminal, especially if those are in foreground.

**Comment by skontar** [comment] 2021-01-02 22:48
**No other extensions activated:**

https://user-images.githubusercontent.com/10827040/103467975-d3be7c80-4d54-11eb-9bf2-4d6196b14fa4.mp4

**Comment by skontar** [comment] 2021-01-02 23:34
Interestingly enough, downgrading to GNOME Shell to 3.38.1 resolves the issue.

You can also see that when multiple windows are maximized, on 3.38.2 maximized windows quickly blink through the panel before they are handled correctly. On 3.38.1 this just does not happen.

It is also easily reproducible in GNOME Boxes VM of Fedora 33.

**Comment by skontar** [comment] 2021-01-06 12:07
> You can also see that when multiple windows are maximized, on 3.38.2 maximized windows quickly blink through the panel before they are handled correctly. On 3.38.1 this just does not happen.

This can be actually seen in my video around 0:17, if you go frame-by-frame.

**Comment by mgrewe** [comment] 2021-01-13 08:11
I can confirm the issue. However, I have the panel on top such that the window's title bar gets overlapped. I'm on Arch with gnome 3.28.2 and official dash-to-panel extensions version 40.

**Comment by icher** [comment] 2021-01-19 17:47
Dash to dock (Ubuntu dock) also affected of this bug.

**Comment by aswild** [comment] 2021-01-26 16:35
I bisected this issue to gnome-shell commit [e6369547dd86f395a8d44eea71f999fa1e5fbe42](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/e6369547dd86f395a8d44eea71f999fa1e5fbe42). Reverting that commit on top of 3.38.3 fixes this issue with dash-to-panel for me.

This dash-to-dock issue appears to be the same bug: https://github.com/micheleg/dash-to-dock/issues/1370

**Comment by eraser215** [comment] 2021-02-09 12:52
Can confirm I also have this issue on:
Fedora 33
gnome-shell-3.38.3-1
Dash to Panel 40 from extensions.gnome.org

**Comment by matteoarrighi** [comment] 2021-02-16 15:34
Can confirm. It doesn't have to logout though, it also happens when the screen only goes blank and I can still access to the session by pressing a key or moving the cursor, thus without logging in.
Fedora 33
gnome-shell 3.38.3
dash-to-panel 40 from extensions.gnome.org

**Comment by Jmennius** [comment] 2021-02-21 14:44
Happens to me all the time on Wayland (I'd say the chance of this happening is much more than 50%).
Fedora 33 with GNOME 3.38.3, dash-to-panel from master (as well as v40).

I can help with testing/debugging.

**Comment by mmacura311** [comment] 2021-03-01 17:41
Can confirm, happens most of the time but not always.
Fedora 33 
gnome-shell-3.38.3 on wayland
dash-to-panel from extensions.gnome.org

**Comment by skontar** [comment] 2021-03-03 16:12
As a **workaround** I have created a bash script which allows me to quickly disable/re-enable the plugin, so it is basically a reload and fixes any visual or layout glitches. I bound it to Super+R.

```
#!/bin/bash

PANEL="dash-to-panel@jderose9.github.com"
ICONS="trayIconsReloaded@selfmade.pl"


reload() {
    extension="$1"

    extensions=$( gsettings get org.gnome.shell enabled-extensions )
    extensions_without=$( sed -r "s/'$extension'//;s/\[, /[/;s/, , /, /;s/, \]/]/" <<< "$extensions" )

    gsettings set org.gnome.shell enabled-extensions "$extensions_without"
    gsettings set org.gnome.shell enabled-extensions "$extensions"
}

reload "$PANEL"
reload "$ICONS"
```

As a followup I have created another script, which monitors unlock dbus messages and runs the first script with 0.5 second delay after unlock.
```
#!/bin/bash

dbus-monitor --session "type='signal', interface=org.gnome.ScreenSaver, member=WakeUpScreen" |
while read message; do
    if [[ "$message" =~ "WakeUpScreen" ]]; then
        sleep 0.5
        reload-panel
    fi
done
```

And finally I have created a desktop file in `~/.config/autostart` to start listening for unlock events automatically.
```
[Desktop Entry]
Type=Application
Name=unlock-monitor
Exec=unlock-monitor
```
I know it is rather cumbersome but may be helpful to people who have to lock their screens often and do not want to use gnome-shell <=3.36.

**Comment by Jmennius** [comment] 2021-03-03 16:56
@skontar thank you!
What's up with gnome-shell > 3.36, can you point us somewhere so that we can educate ourselves?

**Comment by skontar** [comment] 2021-03-03 17:05
@Jmennius the problem was introduced with gnome-shell 3.38. If you downgrade gnome-shell to 3.36 the problem disappears. @aswild found an exact commit which caused it https://github.com/home-sweet-gnome/dash-to-panel/issues/1252#issuecomment-767666943 .

**Comment by aswild** [comment] 2021-03-19 01:43
Looks like this got upstream attention in mutter: https://gitlab.gnome.org/GNOME/mutter/-/issues/1627 and https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1755

I'll try backporting that mutter commit to 3.38 when I get a chance

**Comment by Jmennius** [comment] 2021-06-03 11:07
I still observe the issue with GNOME 40 and people have also reported this in the upstream issue...

**Comment by Deminder** [comment] 2021-09-28 18:57
[Here](https://github.com/Deminder/dash-to-panel/commit/b663af320cd90fc4838a770e77e98a1066afa309) is a workaround by starting an animation (similar to `Intellihide._revealPanel`) after 750ms which works for me (on Fedora 34, GNOME 40) and is an alternative to [the workaround by skontar]( https://github.com/home-sweet-gnome/dash-to-panel/issues/1252#issuecomment-789830854).

```(bash)
curl https://github.com/Deminder/dash-to-panel/commit/b663af320cd90fc4838a770e77e98a1066afa309.diff | patch -p1 -d ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/
```

**Comment by skontar** [comment] 2021-10-08 08:48
@Deminder thanks! This seems to work well. My workaround is not reliable enough (apart from manual refresh), so I believe this is a better way.

**Comment by scarlehoff** [comment] 2022-01-13 22:26
I can confirm this issue is still there for Gnome 41. For me it happens consistently every time.

**Comment by Jmennius** [comment] 2022-01-14 10:01
Same here, is it a year already..? :(

I can only suggest going over to https://gitlab.gnome.org/GNOME/mutter/-/issues/1627 and giving Sebastian Keller some encouragement (It looks like he is the one to fix it in the future)...

**Comment by charlesg99** [comment] 2022-04-10 20:56
Closing as this is a mutter bug

**Closed by charlesg99** 2022-04-10 20:56 UTC
Labels: bug

**Comment by xiaq** [comment] 2022-05-27 20:01
Came here looking for a workaround for this bug, unfortunately the reloading trick in https://github.com/home-sweet-gnome/dash-to-panel/issues/1252#issuecomment-789830854 doesn't work for me; in fact, it would reliably trigger the bug.

I've found another workaround - turning intellihide on and off will fix any window that overlaps with the pannel:

```sh
gsettings set org.gnome.shell.extensions.dash-to-panel intellihide true
gsettings set org.gnome.shell.extensions.dash-to-panel intellihide false
```

**Comment by Jmennius** [comment] 2022-05-27 20:16
I must say that with gnome 42 I don't experience this issue. Or maybe it's latest dash-to-panel updates.

**Comment by scarlehoff** [comment] 2022-05-30 11:47
I'm still experiencing it with gnome 42. My workaround for now is just disabling/enabling the extension when I unlock.

**Comment by schneemaier** [comment] 2023-01-04 19:59
I have the same issue under wayland, gnome 43.0

**Comment by Jmennius** [comment] 2023-01-04 20:18
> I have the same issue under wayland, gnome 43.0

Yes, I think it has come back... For me. 43.2

**Comment by apast0r** [comment] 2023-01-12 07:19
Hi, I have the same bug.
I'm using wayland, gnome 43.2 and dash to panel 52.

**Comment by schneemaier** [comment] 2023-01-13 19:27
I created a script which runs every time when I unlock the screen. So far it seems to works around the issue: 

```
#!/bin/sh

dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" |
  while read x; do
    case "$x" in 
      *"boolean true"*)
         echo SCREEN_LOCKED;;
      *"boolean false"*)
         echo SCREEN_UNLOCKED
         gsettings set org.gnome.shell.extensions.dash-to-panel intellihide true
         sleep 1
         gsettings set org.gnome.shell.extensions.dash-to-panel intellihide false;;
    esac
  done
```

Make sure it runs in the background after you login. 

dbus monitor command usage is from [here](https://unix.stackexchange.com/questions/28181/how-to-run-a-script-on-screen-lock-unlock)

**Comment by KaffeineKicks** [comment] 2023-09-19 12:38
Confirmed and constantly reproducible on Wayland, Gnome 44, gnome-shell=44.5, libwayland=1.22.0, and dash-to-dock=v87.

Overlapping does not depend on dock mode (dock/panel) or on dock placement (any screen side), present in any case. Occurs both after screen lock/unlock, and after sleep/wakeup with disabled screen auto-lock.

Only happens on Wayland session, while on X11 session the resizing works correctly.

**Comment by skypexu** [comment] 2023-11-06 05:05
The bug still exists on ubuntu 22.04

**Comment by talonx** [comment] 2025-04-04 07:24
Still seeing this. Ubuntu 22.04
