### ISSUE TITLE
Application titles width after unlock

### ISSUE THREAD

**Issue by gvaleika** [home-sweet-gnome/dash-to-panel#1608] opened 2022-04-05 21:54 UTC
**Describe the bug**
Panel with many open windows after unlocking locked screen doesn't recalculate width of ungrouped application titles and they doesn't fit panel(scroll left and right). After open/close of new window applications title width are recalculated and match panel width.

**Linux distribution and version**
archlinux current

**GNOME Shell version**
GNOME Shell 41.5

**Dash-to-Panel version**
5a9b010cde4e0b21d66b6320315766c2ae26b4fa
noticed this happening from 5d1f8239f47460fb50211a1021fc5c2c40ac7b88 (Support for gjs 1.71.1 and gnome-shell 42)

**Where was Dash-to-Panel installed from?**
cloned git repository/make install

**Comment by charlesg99** [comment] 2022-04-06 18:01
Hi, so far I can't reproduce on x.org/gnome-shell 41.5. Are you on wayland? Anything else on your system that could affect this maybe? Thanks!

**Comment by gvaleika** [comment] 2022-04-06 18:30
Hi, nothing special. xorg, display 2560x1440 on displayport, AMD graphics. Unlocking not from suspended state.

This happens not every time. I didn't identified if it happens when display power saving is on+unlock or it is enough only to unlock. Happens ~ once in day or two.

**Comment by gvaleika** [comment] 2022-04-07 18:58
Meanwhile my archlinux rolled forward to GNOME 42. I updated dash-to-panel to 1efa51b76bdc39d843ff176e756497d30c2326f6 and now I've got case which is repeatable.

Each time I Alt+F2-r I'm getting this.

[Screencast from 2022-04-07 21:48:15.zip](https://github.com/home-sweet-gnome/dash-to-panel/files/8445706/Screencast.from.2022-04-07.21.48.15.zip)

Interesting thing f.e. I launch gitk (one more application) this effect disappears. I close this additional application - panel scrolling after xorg restart returns.

This happen after xorg restart, not after unlock like in original issue.

**Comment by charlesg99** [comment] 2022-04-07 19:49
I also updated arch to gnome 42 yesterday and I can't reproduce it yet on xorg restarts. Could you run `journalctl /usr/bin/gnome-shell -f -o cat`, restart xorg and send the logs you got? Maybe there is an error in there that could help us pin it down. Thanks!

**Comment by gvaleika** [comment] 2022-04-07 20:11
Updated to 7d99c507a2f67e1e1b95c734c6cc3ee58db19834

Log:

[root@gv-pc Downloads]# journalctl /usr/bin/gnome-shell -f -o cat
Can't update stage views actor <unnamed>[<StWidget>:0x5591605a6de0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x5591605a75e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x5591605a8800] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StLabel>:0x5591605a91d0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_taskbar_TaskbarItemContainer>:0x55915f77a240] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_appIcons_TaskbarAppIcon>:0x5591605789e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x5591605bb1d0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x5591605bb9d0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x5591605bcbf0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StLabel>:0x5591605bd5c0] is on because it needs an allocation.
**Alt+F2+r**
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
Object .MetaWindowActorX11 (0x55915dbf8340), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 pid=206176 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
== Stack trace for context 0x55915b769190 ==
#0   55915b8b72c8 i   resource:///org/gnome/shell/ui/windowManager.js:1542 (222b4fd2a740 @ 23)
#1   7ffd3514b9f0 b   self-hosted:1175 (64afaeb0a10 @ 454)
#2   55915b8b7248 i   resource:///org/gnome/shell/ui/main.js:250 (64afaeef150 @ 12)
JS ERROR: TypeError: window is null
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1543:9
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:250:16

Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
ATK Bridge is disabled but a11y has already been enabled.
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 3
Telepathy is not available, chat integration will be disabled.
Some code accessed the property 'SecondaryMonitorDisplay' on the module 'workspacesView'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
loading user theme: /usr/share/themes/Arc/gnome-shell/gnome-shell.css
Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /home/gv/.local/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /home/gv/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
st_widget_get_theme_node called on the widget [0x563b6dfd7920 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6dfd74c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6dfd8c30 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6de4b520 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6de52c70 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6dfd7920 StBin:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6dfd74c0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6dfd8c30 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6de4b520 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x563b6de52c70 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
cr_declaration_parse_list_from_buf: assertion 'parser' failed
GNOME Shell started at Thu Apr 07 2022 23:08:18 GMT+0300 (Eastern European Summer Time)
Registering session with GDM
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x563b6d19c310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x563b6f0be340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x563b6f0c0340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x563b6f0be730] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x563b6f0c06c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x563b6f0beb20] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x563b6f0c0a40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x563b6e30e340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x563b6f0c1f40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x563b6e30eb20] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x563b6f92e6c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x563b6e30ef10] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x563b6f92ea40] is on because it needs an allocation.

**Comment by charlesg99** [comment] 2022-04-08 16:32
I was getting a bunch of those warnings when the taskbar was getting full and had to reduce the max label width. I just pushed a fix for it on the master branch, maybe it helped?

```
Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_taskbar_TaskbarItemContainer>:0x555dd6c23340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_dash-to-panel_jderose9_github_com_appIcons_TaskbarAppIcon>:0x555dcf532da0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x555dcf6fd370] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x555dcf704a70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x555dcf643020] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StLabel>:0x555dcf927880] is on because it needs an allocation.

```

**Comment by gvaleika** [comment] 2022-04-08 17:29
Hi,

4e4efeb06e893ebf2f6289944cc34cd91f1c4b5c - effect happens.
79f54a6fba1e60acece30129436dc3f7d4c99f35 - effect disappeared.

**Comment by charlesg99** [comment] 2022-04-08 18:47
So, "effect disappeared" means fixed?

**Comment by gvaleika** [comment] 2022-04-08 18:48
hi, i hope yes!

**Comment by charlesg99** [comment] 2022-04-08 18:50
Made sense that it fixed it, but I couldn't reproduce so, thanks for the confirmation!

**Closed by charlesg99** 2022-04-08 18:50 UTC
Labels: bug
