### ISSUE TITLE
Wrong transparency exiting from overview

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#369] opened 2018-03-28 15:04 UTC
Hi,

(tested running Wayland / Ubuntu 18.04)

1) open a fullscreen window
2) open a non-fullscreen window
3) enter overview
4) click on show desktop button of DtP
5) enter overview
6) select the non-fullscreen window
7) enter overview
8) select the fullscreen window
9) the Gnome panel is transparent ; it should be opaque

**Comment by charlesg99** [comment] 2018-03-28 17:22
Hey fthx, thank you for your report, I can reproduce the issue by reversing steps 6 and 8. I will look into it.

**Comment by fthx** [comment] 2018-03-30 19:11
I hit this bug without intellihide too.
1) open a fullscreen window
2) show desktop
3) go overview
4) select the fullscreen window
5) the panel is transparent instead of opaque

**Comment by fthx** [comment] 2018-03-30 20:00
Does not happen with version 13 from Ubuntu repository.
Maybe intellihide.js is the key, but I don't understand why this file does affect a non-intellihide DtP setup !
:-)

**Comment by charlesg99** [comment] 2018-03-31 03:20
I can't reproduce this on Ubuntu 18.04 with your exported settings and dash to panel as the only extension installed. When intellihide is disabled and a fullscreen window is displayed, the panel always is hidden in my case (no matter if another smaller window has the focus or not).

In your steps, how can you hit "show desktop" since the panel is hidden when a fullscreen window is displayed? I figure you forgot a step before the second one that would be "go to overview", but even then I can't reproduce it.

Thanks

**Comment by fthx** [comment] 2018-03-31 05:52
I meant that my current settings are to not hide the panel, never do. Sorry!

**Comment by charlesg99** [comment] 2018-03-31 13:49
Sorry but what setting are you referring to? I wasn't aware that you can keep the panel visible in fullscreen mode. Thanks

**Comment by fthx** [comment] 2018-03-31 16:42
ok : I switched back to never-hide mode.
Soooo :-) to be clear enough, this time : 

dconf dump /org/gnome/shell/extensions/dash-to-panel/

[/]
group-apps-label-font-color='#dddddd'
tray-padding=-1
enter-peek-mode-timeout=300
isolate-workspaces=true
dot-color-unfocused-different=false
app-ctrl-hotkey-1=['<Primary><Super>1']
app-ctrl-hotkey-2=['<Primary><Super>2']
app-ctrl-hotkey-3=['<Primary><Super>3']
app-ctrl-hotkey-4=['<Primary><Super>4']
app-ctrl-hotkey-5=['<Primary><Super>5']
show-showdesktop-button=true
app-ctrl-hotkey-6=['<Primary><Super>6']
app-ctrl-hotkey-8=['<Primary><Super>8']
app-ctrl-hotkey-9=['<Primary><Super>9']
app-ctrl-hotkey-7=['<Primary><Super>7']
hotkey-prefix-text='Super'
animate-window-launch=false
click-action='CYCLE-MIN'
intellihide=false
app-shift-hotkey-10=['<Shift><Super>0']
app-shift-hotkey-kp-1=['<Shift><Super>KP_1']
show-activities-button=false
app-shift-hotkey-kp-2=['<Shift><Super>KP_2']
app-shift-hotkey-kp-3=['<Shift><Super>KP_3']
app-shift-hotkey-kp-4=['<Shift><Super>KP_4']
dot-color-override=false
app-shift-hotkey-kp-7=['<Shift><Super>KP_7']
app-shift-hotkey-kp-5=['<Shift><Super>KP_5']
app-shift-hotkey-kp-8=['<Shift><Super>KP_8']
app-shift-hotkey-kp-9=['<Shift><Super>KP_9']
app-hotkey-1=['<Super>1']
app-shift-hotkey-kp-6=['<Shift><Super>KP_6']
app-hotkey-3=['<Super>3']
app-hotkey-4=['<Super>4']
app-hotkey-5=['<Super>5']
group-apps=true
app-hotkey-7=['<Super>7']
app-hotkey-8=['<Super>8']
app-hotkey-9=['<Super>9']
location-clock='STATUSLEFT'
intellihide-use-pressure=true
app-hotkey-6=['<Super>6']
app-ctrl-hotkey-10=['<Primary><Super>0']
status-icon-padding=-1
intellihide-show-in-fullscreen=false
app-hotkey-kp-1=['<Super>KP_1']
app-hotkey-2=['<Super>2']
hotkeys-overlay=false
app-hotkey-kp-3=['<Super>KP_3']
app-hotkey-kp-2=['<Super>KP_2']
app-hotkey-kp-6=['<Super>KP_6']
app-hotkey-kp-7=['<Super>KP_7']
app-hotkey-kp-8=['<Super>KP_8']
app-hotkey-kp-9=['<Super>KP_9']
app-hotkey-kp-4=['<Super>KP_4']
dot-color-1='#ffffff'
dot-color-2='#ffffff'
dot-color-3='#ffffff'
dot-color-4='#ffffff'
app-hotkey-kp-5=['<Super>KP_5']
peek-mode-opacity=200
group-apps-label-font-size=14
focus-highlight-opacity=20
dot-style-focused='SEGMENTED'
group-apps-use-fixed-width=false
tray-size=0
show-window-previews-timeout=1000
preview-middle-click-close=false
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
shift-middle-click-action='LAUNCH'
shortcut=['<Super>q']
middle-click-action='LAUNCH'
leave-timeout=100
show-window-previews=true
leftbox-padding=-1
panel-position='TOP'
showdesktop-button-width=16
show-apps-icon-file=''
intellihide-close-delay=300
focus-highlight=true
app-hotkey-10=['<Super>0']
intellihide-pressure-threshold=1
animate-show-apps=false
panel-size=30
focus-highlight-color='#ffffff'
app-shift-hotkey-kp-10=['<Shift><Super>KP_0']
appicon-margin=4
intellihide-hide-from-windows=false
group-apps-label-max-width=200
app-ctrl-hotkey-kp-1=['<Primary><Super>KP_1']
app-ctrl-hotkey-kp-2=['<Primary><Super>KP_2']
app-ctrl-hotkey-kp-3=['<Primary><Super>KP_3']
app-ctrl-hotkey-kp-4=['<Primary><Super>KP_4']
app-ctrl-hotkey-kp-5=['<Primary><Super>KP_5']
app-ctrl-hotkey-kp-6=['<Primary><Super>KP_6']
app-ctrl-hotkey-kp-7=['<Primary><Super>KP_7']
group-apps-use-launchers=false
app-ctrl-hotkey-kp-8=['<Primary><Super>KP_8']
app-ctrl-hotkey-kp-9=['<Primary><Super>KP_9']
secondarymenu-contains-showdetails=false
app-shift-hotkey-2=['<Shift><Super>2']
shift-click-action='MINIMIZE'
dot-size=2
app-shift-hotkey-3=['<Shift><Super>3']
app-shift-hotkey-1=['<Shift><Super>1']
dot-position='BOTTOM'
app-shift-hotkey-6=['<Shift><Super>6']
app-shift-hotkey-4=['<Shift><Super>4']
show-appmenu=false
app-shift-hotkey-9=['<Shift><Super>9']
dot-style-unfocused='SEGMENTED'
app-shift-hotkey-8=['<Shift><Super>8']
peek-mode=true
animate-app-switch=false
app-shift-hotkey-5=['<Shift><Super>5']
app-shift-hotkey-7=['<Shift><Super>7']
app-ctrl-hotkey-kp-10=['<Primary><Super>KP_0']
group-apps-underline-unfocused=false
leftbox-size=0
taskbar-position='LEFTPANEL'
intellihide-animation-time=120
hot-keys=false
app-hotkey-kp-10=['<Super>KP_0']

**Comment by fthx** [comment] 2018-03-31 16:43
Thanks for your work Charles !

**Comment by charlesg99** [comment] 2018-03-31 18:34
Ha ok, there is a no setting (dash-to-panel or otherwise) to keep the panel visible while a window is in fullscreen mode, you only meant that you disabled intellihide, am I correct?. If so, there must be something different between our two systems since I can't reproduce what you're seeing. On my end, when intellihide is disabled, the panel always is hidden when a window is in fullscreen (focused or not), so the panel transparency simply can't be observed.

Could you please try it with a single monitor? What other extensions do you have installed? Thanks

**Comment by fthx** [comment] 2018-03-31 18:50
I was not clear, I fear!
I meant 'maximized window', not 'fullscreen window". I forgot that's not the same thing...
So the panel is not hidden with a maximized window when not in intellihide mode.

**Comment by charlesg99** [comment] 2018-03-31 19:27
Riiiiiight, now I see what you're saying :)
Sorry, I should've connected the dots and deduced what you meant. I can reproduce it now, I'll fix it. Thank you for your patience!

**Comment by fthx** [comment] 2018-03-31 19:30
And yours !!

**Comment by fthx** [comment] 2018-03-31 19:32
In this loooong thread, don't forget that I do not experience this bug with Ubuntu's version, i.e. release 13.

**Comment by charlesg99** [comment] 2018-03-31 20:56
Yeah, this is a side effect of the resolution of the crash reported in #352, this isn't related to the new intellihide feature. Now the dynamic transparency fix is globally applied when exiting the overview, so even if the intellihide is disabled, it should work correctly. Thanks

**Comment by charlesg99** [comment] 2018-04-02 19:05
Hey fthx, would you mind pulling the latest master and see if the merged fix resolves the issue? Thanks!

**Comment by fthx** [comment] 2018-04-02 19:41
Ok I tried hard to trick your commits but I did not succeed (intellihide or always-hide).
;-)
Seems good now, except the sticky edge (only with barrier pressure : if I activate and deactivate pressure during the GNOME session, the bug happens too, even in no-pressure mode). However the no-pressure-to-show mode is (maybe ?) buggy : open a maximized window, play around with the dock, experience sudden hides after show (tested on Wayland, don't know running X).

Thanks !

**Comment by charlesg99** [comment] 2018-04-02 22:13
Great thanks for the the tests! As for the behaviour of the panel, when you say "sudden hides" I would think this is normal? The panel should delay its hiding animation only when it has been revealed completely. If you rapidly hover out of the panel while it is revealing, the delay doesn't apply and it hides back immediately. This behaviour is supposed to be the same for the pressure or non pressure reveal. Is this what you're seeing? 

As for the sticky edge, since this is an expected gnome-shell behaviour, I think we should wait and see after the release on gnome extensions. I looked a bit and I believe it would be possible to implement the pressure sensing without using the native barriers, so I'll keep that in mind if there are some complaints about that.

Thanks

**Closed** 2018-04-20 23:06 UTC
