### ISSUE TITLE
mouse stuck on task bar panel

### ISSUE THREAD

**Issue by dave-bouchillon** [home-sweet-gnome/dash-to-panel#917] opened 2020-03-29 01:48 UTC
**Describe the bug**
i just installed the latest update and now the taskbar panel is grabbing my mouse and i cannot move it back to the desktop.  most of my settings are default.  i am on a lenovo laptop with a touchpad.  if you need more info, let me know

**Linux distribution and version**
Ubuntu 18.04

**GNOME Shell version**
3.28.4

**Dash-to-Panel version**
31

settings:
[/]
intellihide-hide-from-windows=true
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
panel-position='BOTTOM'
intellihide=false
panel-size=32
click-action='CYCLE-MIN'
hotkeys-overlay-combo='TEMPORARILY'
appicon-margin=4
middle-click-action='LAUNCH'

**Where was Dash-to-Panel installed from?**
i don't remember exactly.  it was probably through the package manager

**Comment by charlesg99** [comment] 2020-03-31 14:59
Hello, I can't reproduce this on 3.28 and I've never seen this. Can you reproduce this reliably? Did you try it without any other extensions on a fresh boot? Thanks!

**Comment by charlesg99** [comment] 2020-04-06 13:16
I'm going to close this for now... If you find a way to reproduce this reliably with the latest version, please let us know. Thanks!

**Closed by charlesg99** 2020-04-06 13:16 UTC
Labels: bug
