### ISSUE TITLE
dash-to-panel v37 always quit automatically a few hour after enable it in gnome-tweak.

### ISSUE THREAD

**Issue by kevinyuan** [home-sweet-gnome/dash-to-panel#1030] opened 2020-05-30 04:40 UTC
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
[kevin] Tried and doesn't work.

- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
[kevin]
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension popthemetoggle@kylecorry31.github.io already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io. /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension horizontal-workspaces@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension desktop-icons@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension dash-to-dock@micxgx.gmail.com already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com. /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension dash-to-panel@jderose9.github.com already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com. /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension popthemetoggle@kylecorry31.github.io already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io. /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension horizontal-workspaces@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension desktop-icons@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:55 acx-sha journal[27793]: JS LOG: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[1860]: loading user theme: /home/kevinyuan/.themes/Canta-blue-light-compact/gnome-shell/gnome-shell.css
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension dash-to-dock@micxgx.gmail.com already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com. /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension dash-to-panel@jderose9.github.com already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com. /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension popthemetoggle@kylecorry31.github.io already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io. /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension horizontal-workspaces@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension desktop-icons@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:57 acx-sha journal[27793]: JS LOG: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension dash-to-dock@micxgx.gmail.com already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com. /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension dash-to-panel@jderose9.github.com already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com. /home/kevinyuan/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension popthemetoggle@kylecorry31.github.io already installed in /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io. /home/kevinyuan/.local/share/gnome-shell/extensions/popthemetoggle@kylecorry31.github.io will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension horizontal-workspaces@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/horizontal-workspaces@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension desktop-icons@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/desktop-icons@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 09:27:58 acx-sha journal[27793]: JS LOG: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
May 30 11:53:38 acx-sha dbus-daemon[7249]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.47131' (uid=1001 pid=1860 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
May 30 11:53:40 acx-sha dbus-daemon[1755]: [session uid=1001 pid=1753] Activating service name='org.gnome.Nautilus' requested by ':1.1011' (uid=1001 pid=1860 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
May 30 11:53:40 acx-sha dbus-daemon[1755]: [session uid=1001 pid=1753] Activating service name='org.freedesktop.FileManager1' requested by ':1.1011' (uid=1001 pid=1860 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
May 30 11:53:40 acx-sha dbus-daemon[7249]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.47131' (uid=1001 pid=1860 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")

- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
[kevin]  dash-to-panel v37 always quit automatically a few hour after enable it in gnome-tweak.

**Linux distribution and version**
Linux acx-sha 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 8.1.1911 (Core) 

**GNOME Shell version**
GNOME Shell 3.32.2

**Dash-to-Panel version**
v37
 

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
Unable to predict the exact time it quit, so it's hard to do video capture for the event.

**Additional Info**

**Comment by charlesg99** [comment] 2020-05-31 14:44
Hello Kevin, I've never seen this happened so we'll have to try and find the cause on your system. If dash to panel is the cause of this, there will be an error in your logs. Could you post the output of the following command `journalctl /usr/bin/gnome-shell --since='5 days ago' | grep -C10 -E 'dash-to-panel|JS ERROR:'`. You can adjust the "5 days ago" part to a period where know for sure that the problem occurred. Thanks!

**Comment by kevinyuan** [comment] 2020-05-31 15:17
May 30 09:26:34 acx-sha gnome-shell[1860]: JS ERROR: TypeError: this._fullGeometry is undefined
                                           _updateWorkspaceActors@resource:///org/gnome/shell/ui/workspacesView.js:186:17
                                           _scrollToActive@resource:///org/gnome/shell/ui/workspacesView.js:167:9
                                           endTouchGesture@resource:///org/gnome/shell/ui/workspacesView.js:319:9
                                           _endTouchGesture@resource:///org/gnome/shell/ui/workspacesView.js:556:13
                                           vfunc_gesture_cancel@resource:///org/gnome/shell/ui/windowManager.js:571:13
                                           _init/<@resource:///org/gnome/shell/ui/windowManager.js:549:13
                                           pushModal@resource:///org/gnome/shell/ui/main.js:428:14
                                           pushModal@resource:///org/gnome/shell/ui/modalDialog.js:204:14
                                           open@resource:///org/gnome/shell/ui/modalDialog.js:143:14
                                           open@resource:///org/gnome/shell/ui/runDialog.js:283:9
                                           openRunDialog@resource:///org/gnome/shell/ui/main.js:546:5
May 30 09:26:46 acx-sha gnome-shell[1860]: JS ERROR: TypeError: this._fullGeometry is undefined
                                           _updateWorkspaceActors@resource:///org/gnome/shell/ui/workspacesView.js:186:17
                                           _scrollToActive@resource:///org/gnome/shell/ui/workspacesView.js:167:9
                                           endTouchGesture@resource:///org/gnome/shell/ui/workspacesView.js:319:9
                                           _endTouchGesture@resource:///org/gnome/shell/ui/workspacesView.js:556:13
                                           vfunc_gesture_cancel@resource:///org/gnome/shell/ui/windowManager.js:571:13
                                           _init/<@resource:///org/gnome/shell/ui/windowManager.js:549:13
                                           pushModal@resource:///org/gnome/shell/ui/main.js:428:14
                                           pushModal@resource:///org/gnome/shell/ui/modalDialog.js:204:14
                                           open@resource:///org/gnome/shell/ui/modalDialog.js:143:14
                                           showRestartMessage@resource:///org/gnome/shell/ui/main.js:715:5

**Comment by charlesg99** [comment] 2020-05-31 17:34
If you ran the command as I provided ("5 days ago") and you're sure the issue happened in the last 5 days, unfortunately that log tells us this isn't a dash to panel issue. Keep an eye opened for a way to reproduce it... does it happen on screen lock, when you're working on something?

**Comment by kevinyuan** [comment] 2020-06-02 01:18
Yes I enabled the screen lock.

I tried to turn off it from Settings -> Privacy -> Screen lock.

But it doesn't work, the screen lock is still show some time after inactivity.

**Comment by charlesg99** [comment] 2020-07-03 00:34
Gonna close this for now, I suppose this was the same issue as #1026. If not and you find a way to reliably reproduce the issue on a vanilla gnome-shell install, please let us know. Thanks!

**Closed by charlesg99** 2020-07-03 00:34 UTC
Labels: bug
