### ISSUE TITLE
Scrolling animation choppy in some applications

### ISSUE THREAD

**Issue by oboroqoru** [home-sweet-gnome/dash-to-panel#453] opened 2018-08-29 07:20 UTC
Hello, using GNOME 3 with Dash to Panel for the first time, I noticed that when I enable the Dash to Panel extension the scrolling in some applications (namely, web browsers, such as Firefox or Opera, can't say if this is specific to web browsers exclusively or other applications also get affected) gets choppy and laggy. The effect becomes even more noticeable when the browser application is opened in full screen and the panel is visible (that is, not auto-hidden). Disabling the extension removes the lag completely, everything is smooth as it used to be. 

Debian 9.5
GNOME Shell version 3.22
Dash to Panel version 15 (tried some older versions and versions for older GNOME, no difference)

Otherwise, lovely extension so far, definitely going to use it more if this issue gets fixed. Thank you for your efforts and work on Dash to Panel.

**Comment by jderose9** [comment] 2018-08-29 13:42
Thanks for reporting this @oboroqoru . Does disabling _Show window previews on hover_ in the Behavior tab of the settings make the lag go away?

**Comment by bios-ben** [comment] 2018-10-18 07:32
I'm having this exact problem, and yes removing the window previews on hover makes the lag go away. I don't know if this issue is unique or just #310 or #317 duplicated. Watching the resource monitor I see gnome shell building up to 10% CPU constantly just using the hover feature until almost unuseable UI, but a quick removeable of the hover option and/or a reboot of the dash-to-panel removes all the lag. This feels very much like apps behave when there's a memory leak.

Note I am on Ubuntu 18.04 if that matters.

**Comment by charlesg99** [comment] 2019-06-23 13:01
Hello, gonna close this for now since the issue is related to the (now old) window previews. Please install master and reopen or create a new issue if you encounter this problem with the new version of the previews! Thanks!

**Closed by charlesg99** 2019-06-23 13:01 UTC
