### ISSUE TITLE
Multi Monitor app icons not correctly displayed on first screen 

### ISSUE THREAD

**Issue by alumni** [home-sweet-gnome/dash-to-panel#640] opened 2019-05-06 18:58 UTC
Hi, I have a multi-monitor setup on Wayland: left (primary) is 1080p with scale 125% and right is 4K with scale 150%. I'm not sure scaling is important, just mentioning it.

The application menu displays correctly if I open it on the second screen (app icons on the second screen, window overview for the first screen on the first screen). 

However, if I open the application menu from the first screen (or the window overview) it will be chopped and split on the second screen as well.

Dash to dock seems to be working fine with my setup, that's why I reported it here.

**Comment by charlesg99** [comment] 2019-05-07 00:37
Hello alumni, haven't seen this issue yet, might be some wayland/fractional scaling weirdness. Could you please provide a screenshot of the issue? What distro/dash to panel version are you on? Thanks

**Comment by alumni** [comment] 2019-05-09 17:05
Hi Charles, I'm using Antergos with Gnome 3.32.1 and Dash to panel v19.

![Screenshot from 2019-05-09 18-52-45](https://user-images.githubusercontent.com/611745/57471911-8bec0700-728c-11e9-9b1a-a9f485fe2edc.jpg)
![Screenshot from 2019-05-09 19-03-08](https://user-images.githubusercontent.com/611745/57472212-33693980-728d-11e9-95d3-9e799f174eef.jpg)

Everything is fine if I disable the extension.

**Comment by charlesg99** [comment] 2019-05-10 01:40
Interesting... Looks like the overview on the first monitor is using the width of the second monitor, but uses the correct height. I can't reproduce it so far unfortunately (I don't have a HiDPI monitor). Does it also happen if you set both monitor with a scaling of 100%? Does it happen on Xorg? Thanks

**Comment by alumni** [comment] 2019-05-14 17:49
The issue is still present if scaling is 100% or if I switch to Xorg.

**Comment by Durlyn** [comment] 2019-06-30 13:20
If use two monitors and make the right monitor the main, then the extension applications menu  does not open.

**Comment by charlesg99** [comment] 2019-09-29 14:28
Is this still happening using the current master? There were recent changes that might have fixed that, but I couldn't reproduce the issue then so I can't verify. Thanks!

**Comment by alumni** [comment] 2019-10-06 21:58
I can't reproduce it in v23 or with the current master anymore, but now I switched to Manjaro with Gnome 3.34.

However, there are other behaviors that I am noticing:
1. if the menu is opened from the left (primary) monitor, now the menu is on the left screen and there is nothing on the right screen. If the menu is opened from the right (secondary) monitor, the menu is opened on the right screen and the activity overview on the left screen.
2. If the menu is on multiple pages, clicking in a column just under the last row will open the app from the first row and same column on the next page.

**Comment by charlesg99** [comment] 2019-10-07 17:39
Hi Lucian, does the issue mentioned in your second point also happens when dash to panel is disabled? I can't reproduce this so far. Thanks!

**Comment by alumni** [comment] 2019-10-07 19:47
yes, it happens without dash to panel too!

**Comment by charlesg99** [comment] 2019-10-07 23:04
Let's close this as the original issue seems to be resolved. I would suggest that you open an issue on [gnome-shell's gitlab](https://gitlab.gnome.org/GNOME/gnome-shell/issues) for the app grid click issue. Thanks for the feedback!

**Closed by charlesg99** 2019-10-07 23:04 UTC
