### ISSUE TITLE
Quit multiple programs not working on Gnome 41

### ISSUE THREAD

**Issue by ShrirajHegde** [home-sweet-gnome/dash-to-panel#1513] opened 2021-11-10 16:42 UTC
**Describe the bug**
Quit **N** programs atonce not working in gnome 41

**Linux distribution and version**
Fedora 35

**GNOME Shell version**
41.1

**Dash-to-Panel version**
Version 45

**Where was Dash-to-Panel installed from?**
[extensions.gnome.org](extensions.gnome.org)

**Screenshots / Video captures**

Gnome 40: 
![image](https://user-images.githubusercontent.com/66936172/141154989-436048f5-f9aa-445e-b383-27fe1d14c8e5.png)

Gnome 41:
![image](https://user-images.githubusercontent.com/66936172/141155083-4095867b-8112-41d4-9275-c9503f1b8aaa.png)

**Additional Info**

**Comment by ShrirajHegde** [comment] 2021-11-10 18:20
Okay, weird issue, it says quit but closes all windows (sometimes)

 It seems intermittent and also program dependent. For ex: Quit doesn't close all the windows for gnome terminal ever

**Comment by philippun1** [comment] 2021-11-13 18:55
Can confirm this on Manjaro testing with gnome-shell 41 and dtp v45.

**Comment by linuxd3v** [comment] 2021-11-22 12:29
Gnome 41 + Fedora 35 + Xorg.  applications ungrouped.
For me when I right click on application tab + "quit" button ->this closes all instances of that program now instead of just the one  I wanted to close.

**Comment by chidniu** [comment] 2021-11-23 13:55
> Gnome 41 + Fedora 35 + Xorg. applications ungrouped. For me when I right click on application tab + "quit" button ->this closes all instances of that program now instead of just the one I wanted to close.

Can confirm this on Manjaro using Gnome 41.1-1 with xorg-server 21.1.1-3.1.

**Comment by chidniu** [comment] 2021-12-03 13:46
> > Gnome 41 + Fedora 35 + Xorg. applications ungrouped. For me when I right click on application tab + "quit" button ->this closes all instances of that program now instead of just the one I wanted to close.
> 
> Can confirm this on Manjaro using Gnome 41.1-1 with xorg-server 21.1.1-3.1 and DtP 45.

Sorry for spamming this issue, but is there anything new on that bug? This behaviour is extremely explosive. I have to restore some work every second day because I absent-mindedly clicked close on a window in the bottom panel...

**Comment by nlpsuge** [comment] 2021-12-15 17:21
Similar issue here.

The name of 'Quit' is not right at all, it should be changed to 'Close all windows' or 'Close N windows'. 

The actual behaviour of that Quit button is close all windows one by one.

I tested on Firefox. 
- Open multiple windows in Firefox first
- Test 1: Quit Firefox via ![image](https://user-images.githubusercontent.com/2271720/146232994-82afab42-8cea-4015-a676-9a54c45f6b5e.png) -> Quit and reopen Firefox will bring **all previous open windows** back.
- Test 2: Quit Firefox via ![image](https://user-images.githubusercontent.com/66936172/141155083-4095867b-8112-41d4-9275-c9503f1b8aaa.png) and reopen Firefox will bring **only one of previous open windows** back.

I'm not sure if this is the issue of dash-to-panel.

**Comment by charlesg99** [comment] 2022-04-03 15:33
Duplicate of #1569

**Closed by charlesg99** 2022-04-03 15:33 UTC
Labels: bug

**Comment by gcvl** [comment] 2022-10-06 20:26
It's still happening with the (grouped) gnome-terminal: "Quit [n] windows" closes just one window instead of all of them.
Ubuntu 22.04 GNOME 42.4 Xorg.

**Comment by charlesg99** [comment] 2022-10-07 12:31
@gcvl Thanks for the report, should now be fixed on the master branch.

**Comment by gcvl** [comment] 2022-10-07 18:02
I installed it from source and it works, thank you for this great extension!
