### ISSUE TITLE
Windows do not get moved to the correct location

### ISSUE THREAD

**Issue by road2react** [home-sweet-gnome/dash-to-panel#1758] opened 2022-09-28 02:10 UTC
**Describe the bug**
After unlocking the screen, maximized native-Wayland windows become moved to the position as if the top panel was present, instead of the bottom panel created by Dash to Panel. This only occurs for some windows, and occurs randomly. 

XWayland windows are not affected.

**Linux distribution and version**
Arch

**GNOME Shell version**
43

**Dash-to-Panel version**
52

**Where was Dash-to-Panel installed from?**
GNOME Extensions website

**Comment by vbnmvhnhjk** [comment] 2023-01-17 11:43
This has been happening to me. For example, with Gnome Files, the window will seemingly be moved down the screen as though it's flush with the top panel but in fact there is a gap there. And I can confirm it randomly happens with other apps too.

**Comment by charlesg99** [comment] 2023-03-12 13:34
Duplicate of #1600

**Closed by charlesg99** 2023-03-12 13:34 UTC
Labels: bug
