### ISSUE TITLE
Wishlist : show panel in overview option

### ISSUE THREAD

**Issue by fthx** [home-sweet-gnome/dash-to-panel#360] opened 2018-03-19 06:57 UTC
Hi,

Thanks for the great new intellihide feature.
Sometimes the panel didn't hide, but I'm unable to reproduce, so...

Well, I would find useful to see the panel during overview. Maybe that's not everybody's wish, so why not create an option for this feature ? The panel does not show in overview mode even reaching the top of the screen.

**Comment by charlesg99** [comment] 2018-03-20 03:11
Hey, I would classify this as a bug instead of a feature request. I agree that the panel should be visible while in overview and I think it would be better if it was the normal behaviour (no setting controlling it). What do you think? Thanks.

**Comment by fthx** [comment] 2018-03-20 07:26
I agree !

**Comment by charlesg99** [comment] 2018-03-21 15:29
Could you please try the latest master and see if that works out for you? Thanks

**Comment by fthx** [comment] 2018-03-21 16:01
Basically it works !

I have a doubt about : 
![image](https://user-images.githubusercontent.com/23138504/37721148-156ef230-2d29-11e8-84ad-908b8ee323b3.png)
and inside : 
![image](https://user-images.githubusercontent.com/23138504/37721200-312f4aa6-2d29-11e8-9217-f0190016c32e.png)
but I am not able to know if it's DtP-related.

Clearly this time, there is a small issue : when you go to overview, if you put your mouse cursor on the edge of the screen (panel-sided.....) then the panel hides and shows again.

**Comment by jderose9** [comment] 2018-03-21 16:35
This is a nitpick - but I'm wondering if we can start the open animation at the same time as the workspaces bar somehow, and match its speed? And same with closing the overview. I'm basically seeing a delay when opening and closing where the bar appears later in the overview and stays up briefly after the overview was closed. I tried tweaking the animation delay and duration settings without luck.

**Comment by charlesg99** [comment] 2018-03-21 20:23
@fthx Thanks, I will see to the hover issue while in overview, surprisingly I can't reproduce it when the panel is at the bottom. As for the gjs warnings, both the SHELL_KEYBINDINGS_SCHEMA and the _grabHelperStack properties are accessed from dash-to-panel and aren't declared with var in their gnome-shell modules. These warnings are fairly benign though as they only occur when starting gnome-shell. This would need to be fixed on the gnome-shell's side.

@jderose9 good idea, I'll try to have the panel's animation match the overview one. Just be sure, you would use the slide in animation duration or the workspaces box and ignore the one defined in the dash-to-panel settings when entering and exiting the overview? Thanks

**Comment by fthx** [comment] 2018-03-21 20:42
There is something fishy.
1) (Ubuntu 18.04, GS 3.28, tested only running Wayland) I set the position of the panel at the bottom (following your setup !) and the hidden panel does not show up when I reach the bottom edge of the screen. It's not the first time I get such a bug with intellihide (with top panel it happens too). Way to reproduce : run Tweaks, activate DtP with intellihide, move the cursor at the bottom.
2) (still running Wayland, don't know if it happens running Xorg) When DtP has been activated and even any deactivation, with the panel position set at the bottom, the mouse cursor seems to be sticky at the left top edge of the screen. Does not seem to happen when I forget DtP during my session. Way to reproduce : go to overview (via hot corner), move the cursor to right and slightly down, the cursor does not go down and seems to be slightly sticky for roughly 5 cm on a 15" display, and after these 5 cm the cursor is fully freed.

**Comment by jderose9** [comment] 2018-03-22 13:12
The animation looks great now. Thanks, @charlesg99 !

**Comment by charlesg99** [comment] 2018-03-22 19:26
I tried to reproduce your 2 issues without success on 3.26.2 (Wayland and Xorg). Are you experiencing the sticky edge every time you use the top left hot corner? Are you using the pressure option? Does it happen only on a multi-monitors setup? Do you see any error/warning in your logs when this occurs (run `journalctl /usr/bin/gnome-shell -f -o cat` before to see it "live")?

Maybe this is a 3.28 specific behaviour? @vivaeltopo, since you have a 3.28 installation handy, would you mind updating to the latest master and see if you can reproduce the 2 issues mentioned above?

Thanks!

**Comment by fthx** [comment] 2018-03-22 19:35
yes / yes / no / no
:-)
One thing is sure : it's DtP-related. I *never* experience this issue without DtP. The odd stuff is that once DtP is turned off, the sticky edge remains in GS session. I do use a touchpad & libinput.

**Comment by fthx** [comment] 2018-03-22 20:54
It does not happen when intellihide is turned off.

**Comment by charlesg99** [comment] 2018-03-23 02:09
I'll install Ubuntu 18.04 and see if I can reproduce it. Could you please provide your dash-to-panel settings using `dconf dump /org/gnome/shell/extensions/dash-to-panel/` Thanks

**Comment by fthx** [comment] 2018-03-23 19:03
```
dconf dump /org/gnome/shell/extensions/dash-to-panel/
[/]
group-apps-label-font-color='#dddddd'
tray-padding=-1
enter-peek-mode-timeout=300
isolate-workspaces=true
dot-color-unfocused-different=false
app-ctrl-hotkey-1=['<Primary><Super>1']
app-ctrl-hotkey-2=['<Primary><Super>2']
app-ctrl-hotkey-3=['<Primary><Super>3']
app-ctrl-hotkey-4=['<Primary><Super>4']
app-ctrl-hotkey-5=['<Primary><Super>5']
show-showdesktop-button=true
app-ctrl-hotkey-6=['<Primary><Super>6']
app-ctrl-hotkey-8=['<Primary><Super>8']
app-ctrl-hotkey-9=['<Primary><Super>9']
app-ctrl-hotkey-7=['<Primary><Super>7']
hotkey-prefix-text='Super'
animate-window-launch=false
click-action='CYCLE-MIN'
intellihide=true
app-shift-hotkey-10=['<Shift><Super>0']
app-shift-hotkey-kp-1=['<Shift><Super>KP_1']
show-activities-button=false
app-shift-hotkey-kp-2=['<Shift><Super>KP_2']
app-shift-hotkey-kp-3=['<Shift><Super>KP_3']
app-shift-hotkey-kp-4=['<Shift><Super>KP_4']
dot-color-override=false
app-shift-hotkey-kp-7=['<Shift><Super>KP_7']
app-shift-hotkey-kp-5=['<Shift><Super>KP_5']
app-shift-hotkey-kp-8=['<Shift><Super>KP_8']
app-shift-hotkey-kp-9=['<Shift><Super>KP_9']
app-hotkey-1=['<Super>1']
app-shift-hotkey-kp-6=['<Shift><Super>KP_6']
app-hotkey-3=['<Super>3']
app-hotkey-4=['<Super>4']
app-hotkey-5=['<Super>5']
group-apps=true
app-hotkey-7=['<Super>7']
app-hotkey-8=['<Super>8']
app-hotkey-9=['<Super>9']
location-clock='STATUSLEFT'
intellihide-use-pressure=true
app-hotkey-6=['<Super>6']
app-ctrl-hotkey-10=['<Primary><Super>0']
status-icon-padding=-1
intellihide-show-in-fullscreen=false
app-hotkey-kp-1=['<Super>KP_1']
app-hotkey-2=['<Super>2']
hotkeys-overlay=false
app-hotkey-kp-3=['<Super>KP_3']
app-hotkey-kp-2=['<Super>KP_2']
app-hotkey-kp-6=['<Super>KP_6']
app-hotkey-kp-7=['<Super>KP_7']
app-hotkey-kp-8=['<Super>KP_8']
app-hotkey-kp-9=['<Super>KP_9']
app-hotkey-kp-4=['<Super>KP_4']
dot-color-1='#ffffff'
dot-color-2='#ffffff'
dot-color-3='#ffffff'
dot-color-4='#ffffff'
app-hotkey-kp-5=['<Super>KP_5']
peek-mode-opacity=200
group-apps-label-font-size=14
focus-highlight-opacity=20
dot-style-focused='SEGMENTED'
group-apps-use-fixed-width=false
tray-size=0
show-window-previews-timeout=1000
preview-middle-click-close=false
dot-color-unfocused-1='#5294e2'
dot-color-unfocused-2='#5294e2'
dot-color-unfocused-3='#5294e2'
dot-color-unfocused-4='#5294e2'
shift-middle-click-action='LAUNCH'
shortcut=['<Super>q']
middle-click-action='LAUNCH'
leave-timeout=100
show-window-previews=true
leftbox-padding=-1
panel-position='TOP'
showdesktop-button-width=16
show-apps-icon-file=''
intellihide-close-delay=300
focus-highlight=true
app-hotkey-10=['<Super>0']
intellihide-pressure-threshold=100
animate-show-apps=false
panel-size=30
focus-highlight-color='#ffffff'
app-shift-hotkey-kp-10=['<Shift><Super>KP_0']
appicon-margin=4
intellihide-hide-from-windows=false
group-apps-label-max-width=200
app-ctrl-hotkey-kp-1=['<Primary><Super>KP_1']
app-ctrl-hotkey-kp-2=['<Primary><Super>KP_2']
app-ctrl-hotkey-kp-3=['<Primary><Super>KP_3']
app-ctrl-hotkey-kp-4=['<Primary><Super>KP_4']
app-ctrl-hotkey-kp-5=['<Primary><Super>KP_5']
app-ctrl-hotkey-kp-6=['<Primary><Super>KP_6']
app-ctrl-hotkey-kp-7=['<Primary><Super>KP_7']
group-apps-use-launchers=false
app-ctrl-hotkey-kp-8=['<Primary><Super>KP_8']
app-ctrl-hotkey-kp-9=['<Primary><Super>KP_9']
secondarymenu-contains-showdetails=false
app-shift-hotkey-2=['<Shift><Super>2']
shift-click-action='MINIMIZE'
dot-size=2
app-shift-hotkey-3=['<Shift><Super>3']
app-shift-hotkey-1=['<Shift><Super>1']
dot-position='BOTTOM'
app-shift-hotkey-6=['<Shift><Super>6']
app-shift-hotkey-4=['<Shift><Super>4']
show-appmenu=false
app-shift-hotkey-9=['<Shift><Super>9']
dot-style-unfocused='SEGMENTED'
app-shift-hotkey-8=['<Shift><Super>8']
peek-mode=true
animate-app-switch=false
app-shift-hotkey-5=['<Shift><Super>5']
app-shift-hotkey-7=['<Shift><Super>7']
app-ctrl-hotkey-kp-10=['<Primary><Super>KP_0']
group-apps-underline-unfocused=false
leftbox-size=0
taskbar-position='LEFTPANEL'
intellihide-animation-time=120
hot-keys=false
app-hotkey-kp-10=['<Super>KP_0']

```

**Comment by charlesg99** [comment] 2018-03-24 14:50
Is your Ubuntu installation on bare metal or in a VM? I'm seeing a lot of cursor error on Wayland in Virtualbox and I also see a lot of ubuntu-dock errors while disabling it (given, it isn't supposed to be disabled). Thanks.

**Comment by charlesg99** [comment] 2018-03-24 19:56
Well, I could reproduce the "sticky edge", but it happens with every pressure barrier that I tried (even with the default ubuntu-dock). Could you confirm this? With the default ubuntu-dock (or dash-to-dock with "push to show"), if the intellihide is activated, the edge of the screen where the dock is "sticks" if you start at the top corner and run your mouse alongside this edge. Also this only seems to happen on GS 3.28 on Walyand (I tried GS 3.26.2 on Wayland and GS 3.28 on Xorg, but couldn't reproduce it). It might also be an Ubuntu thing, not sure. Thanks.

**Comment by fthx** [comment] 2018-03-28 14:55
Well, I tested intellihide without pressure and it displays/hides the dock when I move the cursor anywhere in the screen... Is that intended ?

**Comment by charlesg99** [comment] 2018-04-20 23:11
Closing as the panel does now show in overview. Please open a new issue if you find something else with the intellihide. Thanks!

**Closed by charlesg99** 2018-04-20 23:11 UTC
