### ISSUE TITLE
panel-element-positions-monitors-sync seems to have no effect

### ISSUE THREAD

**Issue by dseomn** [home-sweet-gnome/dash-to-panel#1173] opened 2020-09-16 04:23 UTC
I have `Position` -> `Order and positions on monitor` -> `Apply changes to all monitors` checked (corresponding to `/org/gnome/shell/extensions/dash-to-panel/panel-element-positions-monitors-sync` I think), but the the orders and positions of the elements seem to still only apply to the (grayed out) selected monitor. `/org/gnome/shell/extensions/dash-to-panel/panel-element-positions` seems to be a mapping from monitor to positions, and the monitor index in the mapping seems to be the only one affected, even when `panel-element-positions-monitors-sync` is true.

**Comment by charlesg99** [comment] 2020-12-31 02:00
Hello, I can't reproduce this, any more information? Here all monitors are affected by a change when "Apply changes to all monitors" is checked. Thanks!

**Comment by dseomn** [comment] 2021-01-03 22:14
I'm on Wayland, in case that's relevant. Here's a screenshot, notice how the date is only in the center on the primary (lower) monitor:

![Schermafdruk van 2021-01-03 17-09-26](https://user-images.githubusercontent.com/15314936/103489985-b4702f80-4de6-11eb-84c5-23ada3aef743.png)

Btw, a little while after filing this bug, I decided to have the panel only on one monitor, so this bug doesn't really bother me anymore. Happy to help diagnose it though if you want to get it fixed anyway.

**Comment by dseomn** [comment] 2021-01-03 22:22
Also, the other extensions I have enabled are listed at https://github.com/dseomn/dotfiles/blob/ae68df4a512a57b311703eabdb6495f6bc870e23/.config/dconf-load-yaml/conf.d/gnome-shell-00.yaml#L27-L32 and my other settings for dash-to-panel are lower in the same file.

**Comment by charlesg99** [comment] 2021-01-04 15:54
Just curious, but did you even make a change to the date menu after ticking the "Apply changes to all monitors" checkbox? I can't reproduce this. Thanks!

**Comment by dseomn** [comment] 2021-01-05 00:11
Interesting, changing the position of the date menu fixed it. It also changed `/org/gnome/shell/extensions/dash-to-panel/panel-element-positions` from the first block below to the second. Were you trying to reproduce this bug on a system that always has more than one monitor? I first set up dash-to-panel with a single monitor, then added a second monitor, then changed it to show a panel on all monitors.

```json
{ "0":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"centerMonitor"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}
```

```json
{"0":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"centerMonitor"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}],"1":[{"element":"showAppsButton","visible":true,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"centerBox","visible":true,"position":"centerMonitor"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}
```

**Comment by charlesg99** [comment] 2021-01-05 14:37
Good, what you're seeing is fine. As the label says, after ticking the checkbox the following changes are applied to all monitors. This is mostly a safeguard to preserve multi-monitor configurations if people accidentally tick this checkbox. There already is an issue with adding/removing monitors (see #1215), so I'll close this one for now. Thanks!

**Closed by charlesg99** 2021-01-05 14:37 UTC
