### ISSUE TITLE
SUPER+N opens sometimes new instance instead of existing window and icons get mixed up

### ISSUE THREAD

**Issue by b-hayes** [home-sweet-gnome/dash-to-panel#855] opened 2020-01-23 04:58 UTC
I recently updated the extension and now I get 3 weird problems intermittently:

- often hitting SUPER+N eg WIN+1 for my terminal windows will now open a new instance of the application instead of focusing the current window.
- with the intelligent hide on mousing hover to the bottom will only show the panel on one screen. disconnecting and reconnecting screens sometimes fixes it.
- sometimes the application icons get mixed up with an adjacent application on the dock eg. I open chrome and it has a phpstorm icon instead of a chrome icon

I really wish there was a way to rollback to the version I had before updating when everything worked.

Can someone let me know how to troll back to a previous version? (installed via firefox https://extensions.gnome.org/extension/1160/dash-to-panel//)

**Comment by jderose9** [comment] 2020-01-23 15:32
Hi @b-hayes ! Sorry to hear that you are having issues.

To roll back via firefox you can simply select the previous version from the dropdown after choosing your shell version at the link you referenced:

![image](https://user-images.githubusercontent.com/2118702/72997711-a76f5180-3dca-11ea-9240-7e898d79e31f.png)

I'm not sure specifically about the issues you describe. Which distro and GNOME version are you on? 

If you are feeling adventurous, you could try the latest development version and see if your experience is improved.
https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github

**Comment by b-hayes** [comment] 2020-01-24 07:43
I am running GNOME Shell 3.28.4
in Ubuntu 18.
Cheers for showing me how to get the old versions :)

**Comment by charlesg99** [comment] 2020-03-07 19:21
Hi, I would have preferred to fix the current version, but let's close this as the issue is pretty vague and "resolved". Thanks!

**Closed by charlesg99** 2020-03-07 19:21 UTC
