### ISSUE TITLE
Latest update "broke" the panel icons

### ISSUE THREAD

**Issue by georgyorgy1** [home-sweet-gnome/dash-to-panel#608] opened 2019-03-23 05:53 UTC
I recently updated Dash to Panel and it seems that it "broke" the panel icons
![after](https://user-images.githubusercontent.com/26897186/54862233-9c92fd00-4d72-11e9-8bac-4990e827ed19.png)

This is what it used to look like:
![before](https://user-images.githubusercontent.com/26897186/54862243-b46a8100-4d72-11e9-8915-a582cb4ae400.png)

Here are my settings:
![settings](https://user-images.githubusercontent.com/26897186/54862245-bcc2bc00-4d72-11e9-88f8-7a4028d60de6.png)

I want to rollback the update but I don't exactly know how to do that.

**Comment by alex285** [comment] 2019-03-23 10:10
i believe your issue is fixed on master, just do
```
git clone https://github.com/home-sweet-gnome/dash-to-panel.git
cd dash-to-panel
make
make install
```
it installs on
```
$HOME/.local/share/gnome-shell/extensions
```
restart Shell and re try
```
Alt+F2 + "lg" (log out/in on wayland)
```

and since you have it from Git, you can revert back on any commit you want
```
git checkout d43ddec7b2da572dddc39d372e9a5e13bc80af0e
make 
make install
```
or any tag/version
```
git checkout tags/v18   
make
make install
```
or switch back in master
```
git checkout master   
git pull (to update)
make
make install
```

sorry for the long instructions ..but to my experience it is actually better to use Dash to Panel directly from master, b/c you get instant updates and fixes, while EGO is very slow!

**Comment by alex285** [comment] 2019-03-23 10:12
oops! basically your issue is fixed if you are in GNOME 3.32! no idea for older GNOME versions :)

**Comment by georgyorgy1** [comment] 2019-03-23 12:38
oof, I'm running 3.28. I could update it to 3.32 but I don't want to break my other extensions. 
Anyways, thanks for the fix :D 

I don't think I should close this yet since lots of people are still on 3.28 (Ubuntu 18.04), but the maintainers can close this if they want to.

**Comment by charlesg99** [comment] 2019-03-23 13:33
Hello georgyorgy1, thank you for the report! I've not seen this issue yet and I would like to reproduce it if I can. My work computer is running Ubuntu 18.04 and I tried v19 - HEAD (xorg and wayland) with your settings:

![Screenshot from 2019-03-23 09-06-01](https://user-images.githubusercontent.com/33044886/54866631-abff4f80-4d4c-11e9-9e8f-b6c9cc38d9f5.png)
 
Same result on my home computer which is running Arch - gnome-shell 3.30.2.

Could you please give us more detail on your system? Other extensions? Are those Pop icons? Can you see errors in your logs? Thanks!

**Comment by georgyorgy1** [comment] 2019-03-24 14:26
I'm running Ubuntu 18.04 with GNOME 3.28. The only extensions that I have are Dash to Panel and Arc Menu. The icons that I'm using are Papirus Icons. 

As for the errors, I think these two may say something:
```
Mar 23  1:49:27 PM: #0 0x55de79383810 i   /home/meatwad/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:516 (0x7f1bf8ce06f8 @ 32)
Mar 23  1:49:27 PM: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3a00d26 (Dash to Pa)
Mar 23  1:53:59 PM: failed to create an app for user/*/extensions-web/shell-extension/dash-to-panel_jderose9.github.com/*
```

**Comment by charlesg99** [comment] 2019-03-24 16:42
Still can't reproduce with you settings, theme/icons and your extensions... Could you please expand the log you posted? Would be more helpful if we could see more entries before the first line you posted. Thanks!

**Comment by georgyorgy1** [comment] 2019-03-26 13:46
Unfortunately, there's nothing else in the logs that I can find. I'll try finding more but it's uncertain.

**Comment by flawiddsouza** [comment] 2019-03-27 04:52
I just got this issue when I updated the extension but restarting the gnome shell fixed it for me.

**Comment by kiernann** [comment] 2019-04-19 16:34
After updating from Ubuntu 18.10 to 19.04, I had a similar problem. Following @alex285's instructions to build from the master branch fixed my problem!

**Closed** 2019-04-27 11:57 UTC
