### ISSUE TITLE
"Terminate" on right click popup menu should close the window, not the application

### ISSUE THREAD

**Issue by makkarpov** [home-sweet-gnome/dash-to-panel#1569] opened 2022-02-05 21:20 UTC
**Describe the bug**

When you right-click a window, there is "Terminate" option in the popup menu (among the others). Currently it terminates whole application when clicked, not the window.

Example use case is a web browser with two opened windows. In any other DE (including Windows, MATE, KDE, ...) Right Click -> Close will close only relevant window. In Dash to Panel it will shutdown whole browser, leading to a very confusing experience.

**Linux distribution and version**
Fedora 35

**GNOME Shell version**
41.3

**Dash-to-Panel version**
45

**Where was Dash-to-Panel installed from?**
ZIP from GitHub releases

**Comment by tekstryder** [comment] 2022-02-07 00:23
This issue is a duplicate of https://github.com/home-sweet-gnome/dash-to-panel/issues/1513 and https://github.com/home-sweet-gnome/dash-to-panel/issues/1548 

FIxed by https://github.com/home-sweet-gnome/dash-to-panel/pull/1556

I installed the git master branch and can confirm this issue is resolved.

**Comment by tekstryder** [comment] 2022-02-07 00:35
Duplicate of #1513

**Closed** 2022-04-03 14:19 UTC
Labels: bug
