### ISSUE TITLE
Having the cursor over window preview blocks all keyboard input

### ISSUE THREAD

**Issue by prasannavl** [home-sweet-gnome/dash-to-panel#480] opened 2018-10-15 22:58 UTC
When the mouse cursor is over any of the window previews, none of the keyboard input seem to be getting through to the underlying applications, or the shell itself - This include the `Meta` key to open activities, switching work-spaces etc.

This is rather odd, because none of the global shortcuts would work either when you have the mouse accidentally sitting over an open preview. 

**Edit:** Okay, looks like this is a problem with gnome-shell itself. The usual top bar seems to have the same behavior. So, I'm curious to understand if this can be workaround in dash-to-panel, or this has to be filed against gnome-shell.

**Comment by charlesg99** [comment] 2018-10-27 13:46
Hello prasannavl, I don't think gnome-shell will acknowledge this as a bug since this is intended behavior.

When opened, the popup menu (our window previews, clock menu, status menu, etc.) "grabs" focus and suppresses all user input triggered outside of its pane, until it is closed. I think this is meant to direct the user's attention on the popup menu's content. Here is an excerpt of gnome-shell describing it:
```
    // The general effect of a "grab" is to ensure that the passed in actor
    // and all actors inside the grab get exclusive control of the mouse and
    // keyboard, with the grab automatically being dropped if the user tries
    // to dismiss it.
    //
    // Grabs can be automatically dropped if the user tries to dismiss it
    // in one of two ways: the user clicking outside the currently grabbed
    // actor, or the user typing the Escape key.
```
 
Anyway, there's probably a way to prevent this, but I wouldn't touch that as it is a stock gnome-shell behavior. Thanks!

**Comment by prasannavl** [comment] 2018-10-27 13:54
Hi @charlesg99 - That's what I thought. Thanks for pointing to the gnome-shell comment. That solidifies the fact that gnome-shell is probably not going to want this configurable anytime soon. 

I'm not sure where exactly the input grab is implemented. If there is a straight-forward to prevent this -  would be great if this can be worked around as an optional config in dash to panel.

I find myself pressing the Meta key atleast 1 few dozen times a day where nothing happens, and my pointer is over a window preview or notification.

**Comment by jderose9** [comment] 2019-01-13 18:36
Thanks for reporting, but I'm going to close this one. I found it frustrating when I started using gnome too, but that's just sort of inherent behavior for Gnome. Their popups are essentially dialogs and all keystrokes are fair game for the content inside of the popup to respond to.

**Closed by jderose9** 2019-01-13 18:36 UTC
