### ISSUE TITLE
Dash to panel is outdated in the new gnome version 40.0. Will there be a matching version of dash-to-panel for this?

### ISSUE THREAD

**Issue by Steps65** [home-sweet-gnome/dash-to-panel#1307] opened 2021-04-14 08:47 UTC
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
A clear and concise description of what the problem is, any steps to reproduce, and what you expected to happen instead.

**Linux distribution and version**
Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by Water261** [comment] 2021-04-14 09:58
This is a blank issue...

**Comment by work-chausat** [comment] 2021-04-14 10:53
@Steps65 https://github.com/philippun1/dash-to-panel

**Comment by jfk88** [comment] 2021-04-15 15:57
Not working on gnome 40 for me as well (Arch). The logs:

```
Gtk.BuilderError: /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/Settings.ui:26:39 Invalid property: GtkFrame.shadow_type

Stack trace:
  _init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:168:23
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
  newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2199:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by enigma131** [comment] 2021-04-21 09:18
Thanks. Compilation done for ArchLinux. Extension enabled via:
 gnome-extensions enable dash-to-panel@jderose9.github.com

**Comment by nekohayo** [comment] 2021-06-09 12:25
@Steps65, please close this ticket as a duplicate of issue #1265.

**Closed** 2021-06-09 12:28 UTC
Labels: bug
