### ISSUE TITLE
Menus not shown when too high

### ISSUE THREAD

**Issue by zagortenay333** [home-sweet-gnome/dash-to-panel#200] opened 2017-06-21 09:49 UTC
On gnome-shell `3.24`.

When the dash-to-panel is on the bottom of the screen, and a popup menu is higher than the monitor, the menu will not be shown. From what I understand, the menu gets drawn below the dash-to-panel (i.e., "below the monitor") and is thus not visible.

To replicate, make a bunch of notifications and try to open the calendar menu. 

Use default theme since some themes might make the max-height smaller on the calendar popup. By default it's roughly equal to the monitor height.

**Comment by travisfalk** [comment] 2017-06-24 07:47
Yes! this does happen. If the extension is turned off and the panel is at the top again then all notifications are visible again.

**Comment by jderose9** [comment] 2017-06-27 13:41
I'm having trouble reproducing this (I can't seem to make enough notifications to push the calendar larger than the screen).

What happens when the panel is on the top? Do the notifications scroll?

This is an issue in gnome in general.. If an element doesn't fit on the screen then it just isn't displayed. It's up to each container to properly size itself and provide a scrollable panel if it's too large.

I did make some changes to improve this recently though. Have you tried the latest code from master by chance? 9e89bf624408a051b1deb0b90ffb852048de1e11

**Comment by travisfalk** [comment] 2017-06-30 00:28
I tried a couple of other extensions which move the top panel to the bottom of screen. They also fail to open the calender/notifications window if there are too many notifications.

If the panel is at the top with lots of notifications then a scroll bar appears and the notifications are scrollable.

**Comment by zagortenay333** [comment] 2017-06-30 07:46
I tried that version from master and it still doesn't work.

What do you mean you can't make enough notifications?

**Comment by travisfalk** [comment] 2017-07-03 05:48
For your info I tried ZorinOS which also puts the panel at the bottom of screen. It also fails to open the calender/notifications if there are too many!

**Comment by jderose9** [comment] 2017-07-03 13:42
@zagortenay333 What I mean is that I am not sure how I can generate so many notifications that it fills the entire screen.

**Comment by zagortenay333** [comment] 2017-07-03 14:17
Use `notify-send` ?

**Comment by alex285** [comment] 2017-07-23 10:10
@jderose9 here's a video reproducing it and comparing with default behavior
https://www.youtube.com/watch?v=GFfGB41D2l8

it is not common to fill the notifications box, but if you do, you can even open it so it is kinda serious bug

to reproduce you can use something like that
```
#!/bin/bash

while true; 
do
  sleep 1;
  notify-send "xa";
done
```

**Comment by jderose9** [comment] 2017-07-25 13:54
Thanks, I wasn't familiar with `notify-send`. I was able to reproduce this.

**Comment by nekohayo** [comment] 2017-10-10 13:44
Just for the record: another way to trigger this is to use dash-to-panel in combination with https://extensions.gnome.org/extension/858/volume-mixer/ and to have an application (such as Firefox or Epiphany) that generates a bunch of sound sources (happens especially with webrtc videoconferencing or web apps like rocketchat)

**Comment by jderose9** [comment] 2017-10-25 01:33
I think there's basically some property somewhere that still thinks the panel is in the top position and doesn't want to draw the popup over it, but I haven't figured out what it is. The gnome-shell code itself correctly think the popup can fit and doesn't draw it as scrollable. I think it's a different symptom of the issue in #25.

**Comment by zagortenay333** [comment] 2017-10-25 11:33
It's gotta have something to do with the boxpointer code. E.g., if you do:
```js
this._boxPointer.actor.set_position(-200, -200);
```
you'll see the menu.

**Comment by ardarandir** [comment] 2017-11-09 14:15
zagortenay, where and how do I have to "do" your code to in order to see the menu?

i'd like to fix/workaround that issue on my system for the time being.

**Comment by zagortenay333** [comment] 2017-11-09 18:02
@ardarandir, that's not a workaround; it was just meant as a help during debugging.

**Comment by johannesgunnar** [comment] 2018-03-02 09:15
I have this happening also to me with the todo.txt gnome shell extension when dash-to-panel is set to bottom and the todo.txt window becomes taller than the screen.
_([the original bug report](https://bitbucket.org/bartl/todo.txt-bart.libert.gmail.com/issues/106/window-disappears-on-large-amount-of) -  a video demonstrating the problem can be seen attached to that bug report)_

**Comment by zagortenay333** [comment] 2018-06-17 16:01
I just looked into this briefly and sort of figured out what the issues is.

When you call the `setPosition` it calls `updateFlip` which in turn calls `_calculateArrowSide`.

The `_calculateArrowSide` func is given the `_userArrowSide` as argument and for some reason it returns the fliped side based on whether or not the menu is higher than the monitor:
https://gitlab.gnome.org/GNOME/gnome-shell/blob/f9dec475a1b4f06899b9f0573cb2cc9c8f2a5a47/js/ui/boxpointer.js#L587

One way to fix this is to keep the `_arrowSide` and `_userArrowSide` vars in sync. So replace:
https://github.com/home-sweet-gnome/dash-to-panel/blob/b6e6ab6efde75ce754c5d7a2b592360709290e3f/panel.js#L727-L730

with:
```js

            if(actor == Main.panel.actor) {
                this._boxPointer._arrowSide = panelPosition;
                this._boxPointer._userArrowSide = panelPosition; // keep these in sync
                break;
            }
```

I really have no clue what the point of `_calculateArrowSide` and `_userArrowSide` is.

**Comment by zagortenay333** [comment] 2018-06-17 16:02
This particular way of fixing it is a little annoying since any extension that has to patch the `menu.open` func will not benefit from this..

It might be worth asking the gnome-shell devs what `_calculateArrowSide` is used for.

**Comment by simonbcn** [comment] 2018-09-25 15:37
Same problem on Arch Linux and Gnome Shell 3.30

**Comment by charlesg99** [comment] 2018-10-16 04:29
@zagortenay333 Thanks for the investigation, seems like `_userArrowSide` is the "preferred/declared" arrow side for the boxbointer, while `_arrowSide` is the current arrow side.

A fix for this issue was added on branch "feature-multimon". If anyone could confirm that it resolves the issue, that would be great. Thanks!

**Comment by charlesg99** [comment] 2018-10-16 12:52
Hey @simonbcn, thank you for the feedback. Are you testing using the notifications in the calendar menu? Can you provide more information on why it doesn't solve the problem? Did you pull the latest branch feature-multimon (I pushed the fix late yesterday), installed it and restarted gnome-shell? 

I'm also on Arch (gnome-shell 3.30) and the calendar menu appears normally even when I add many notifications. I also tested on ubuntu 18.04 (gnome-shell 3.28) :

![image](https://user-images.githubusercontent.com/33044886/47016845-c5a5c680-d11e-11e8-8641-927e2135c8ce.png)

and ubuntu gnome 16.04 (gnome-shell 3.18) :
![image](https://user-images.githubusercontent.com/33044886/47017354-081bd300-d120-11e8-83e8-dc3d1703c8cf.png)

Thanks!

**Comment by simonbcn** [comment] 2018-10-16 13:03
No, I mean the same as the first message in this issue: 

> ...When the dash-to-panel is on the bottom of the screen, and a popup menu is higher than the monitor, the menu will not be shown. 

In my case, dash-to-panel is on the top but the problem is the same:
![captura_20181016_145957](https://user-images.githubusercontent.com/428231/47018213-914cfd00-d154-11e8-83da-af0bbfd2e55c.png)

The menu is below the panel, it should be on top.

**Comment by charlesg99** [comment] 2018-10-16 14:37
Thank you Simon, but what you're referring to is kind of unrelated :)

> No, I mean the same as the first message in this issue:
> 
>>...When the dash-to-panel is on the _bottom_ **[1]** of the screen, and a _popup menu_ **[2]** is higher than the monitor, the menu will _not be shown_ **[3]**.

[1] Your panel is on top
[2] Your screenshot doesn't contain a popup menu, this is a combo box
[3] Your combo box _is_ shown

As per your issue, the only way I can reproduce it is if intellihide is enabled, the combo box gets opened while near the top of the screen, then the panel is revealed by putting your cursor at the top edge of the screen. Is this what you're seeing? This is a "normal" behavior as the panel is removed from the limiting layout when intellihide is enabled. 

With intellihide disabled:
![image](https://user-images.githubusercontent.com/33044886/47022115-c80e1d80-d12a-11e8-8ddb-2d4b3a445802.png)

Whit intellihide enabled:
![image](https://user-images.githubusercontent.com/33044886/47022806-4919e480-d12c-11e8-9cbd-3527510f6936.png)




 Please feel free to open a new issue regarding your specific problem. Thanks!

**Comment by travisfalk** [comment] 2018-10-16 21:15
It appears to work for me. Can now scroll though notifications and delete individual as required.
![dash_to_panel_notifications](https://user-images.githubusercontent.com/29672274/47047908-7a53ec80-d1e0-11e8-90f8-e49778858ae7.jpg)

**Comment by charlesg99** [comment] 2018-10-17 00:44
Thank you for checking it out! I realized there was a problem with the height adjustment of the calendar menu when intellihide was enabled. Since the panel isn't affecting the layout while in intellihide mode, the calendar menu was a bit too tall and was overflowing past the top edge of the monitor. Anyway, I just pushed a fix for this, could you please pull again and see it everything is still good? Thanks!

**Comment by travisfalk** [comment] 2018-10-17 01:18
Here is the difference between old (top image) and new with intellihide enabled on my system. 1920x1080 monitor. New version calendar fits properly now.
![dash_to_panel_intellihide_original](https://user-images.githubusercontent.com/29672274/47056051-13472f80-d202-11e8-8c39-52ade345f435.jpg)
![dash_to_panel_intellihide_newversion](https://user-images.githubusercontent.com/29672274/47056050-13472f80-d202-11e8-93e7-791476e75df3.jpg)

**Comment by charlesg99** [comment] 2018-10-19 18:16
Hi, the fix was merged to master. Thanks!

**Closed by charlesg99** 2018-10-19 18:16 UTC
Labels: bug, high priority
