### ISSUE TITLE
Apps launched in specific ways don't show up in the tray

### ISSUE THREAD

**Issue by Aberrantfox** [home-sweet-gnome/dash-to-panel#845] opened 2020-01-05 19:23 UTC
I noticed if I use webstorm to launch chromium that it would not show up as running  (the little orange bar under the app that indicates that there is a running instance of the app). 

To replicate this, simply open a terminal and type `chromium` to launch an instance. Is this expected behavior or something that's documented elsewhere? 

**Using:** Latest dash-to-panel + pop!_os 19.10 (Both installed fresh today from latest stable). 
**Chromium:** 78.0.3904.97 from the pop!_shop. 

Sorry if this is documented somewhere as something that won't be fixed, just close the issue if that's the case.

**Comment by charlesg99** [comment] 2020-01-05 21:42
Hello, is chromium launching on the same workspace? I tried to reproduce the issue as you mentioned (on Ubuntu 19.10), but it works correctly:

![Peek 2020-01-05 16-33](https://user-images.githubusercontent.com/33044886/71786498-00bd3f80-2fda-11ea-86d5-0045e925489a.gif)

Anything special with your installation? Do you have other extensions installed? Thanks!

**Comment by jderose9** [comment] 2020-01-26 05:11
I installed a fresh installation of PopOS 19.10 in Boxes and Chromium 78.0.3904.97 from the pop shop and was unable to reproduce this using the latest dash-to-panel from master and also the latest e.g.o release.

**Comment by jderose9** [comment] 2020-01-26 05:31
Ok, I was able to reproduce after all. This is only in Wayland. I don't see it when launching from terminal but do when launching from "Show Apps"/overview. I believe this is the same issue as #851.

**Comment by jderose9** [comment] 2020-03-08 03:35
This should be fixed on master.

**Closed** 2020-03-08 15:22 UTC
