### ISSUE TITLE
Running indicators not showing after switching desktops

### ISSUE THREAD

**Issue by mapleroyal** [home-sweet-gnome/dash-to-panel#1851] opened 2023-03-09 04:11 UTC
EDIT: Possibly related - the 'Running indicator style (focused app)' and 'Running indicator style (unfocused app)' dropdowns in the settings do not drop down and can't be be cycled using up/down arrow keys. For me they're both stuck on "dots". Furthermore, when the indicators are not showing per the bug described below, a way to get them to show is to change the "Running indicator position" setting.

---

Similar to https://github.com/home-sweet-gnome/dash-to-panel/discussions/1841 and https://github.com/home-sweet-gnome/dash-to-panel/issues/1843, not sure if same bug so I didn't want to derail the discussion there.

**Describe the bug**
STEPS TO REPRODUCE:
- disalbe all extensions except dash to panel then log out and log in (wayland)
- open some apps (indicators show regularly)
- switch desktops using built in wayland swipe gesture or ctrl+meta+left/right
- switch back to desktop with apps open
- running app indicators (e.g. dots) not showing
- all running app indicators reappear upon switching an app (alt+tab or click an app in the panel or trigger overview and click a window)

**Linux distribution and version**
Vanilla Arch

**GNOME Shell version**
43.3

**Dash-to-Panel version**
54 (there was a similar bug in 53 but I didn't test how to reproduce it)

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
https://i.imgur.com/mZojrSm.png

**Additional Info**
FIRST LOG IMMEDIATELY AFTER LOGGING IN:
```
>>>journalctl /usr/bin/gnome-shell -f -o cat &
[1] 14396
st_widget_get_theme_node called on the widget [0x55f27a31b6f0 Gjs_ui_panel_AppMenuButton.panel-button:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55f279895040 StBin:insensitive "appMenu" ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55f27a1b7920 StBoxLayout.panel-status-menu-box:insensitive ("")] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55f27a1ccb30 Gjs_ui_animation_Spinner:insensitive] which is not in the stage.
Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Failed to create color profile from colord profile: Error opening file /var/lib/gdm/.local/share/icc/edid-e82bae0f031dfb0a025a86b9454ba4d6.icc: Permission denied
GNOME Shell started at Thu Mar 09 2023 06:51:58 GMT+0300 (Arabian Standard Time)
Registering session with GDM
Connection to xwayland lost
```

Most recent log right before posting this can be seen in the screenshot.

**Comment by charlesg99** [comment] 2023-03-09 15:39
Thanks for the report, indeed it wasn't working correctly on wayland (always on wayland :angry:). Should now be fixed on the master branch. I'll re release soon!

**Comment by charlesg99** [comment] 2023-03-09 15:42
I can't reproduce the "running indicator style" dropdown issue though, they're opening fine for me on wayland.

**Comment by charlesg99** [comment] 2023-03-12 13:35
Fix was released

**Closed by charlesg99** 2023-03-12 13:35 UTC
Labels: bug
