### ISSUE TITLE
Issolate doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by JohnGalt1717** [home-sweet-gnome/dash-to-panel#966] opened 2020-04-24 18:38 UTC
**Describe the bug**
On previous versions issolate would only show active applications on a given screen. In 20.04 it does nothing.

**Linux distribution and version**
Ubuntu 20.04 final

**GNOME Shell version**
3.36.1

**Dash-to-Panel version**
35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, 

**Screenshots / Video captures**

**Comment by charlesg99** [comment] 2020-04-24 19:53
Hello JohnGalt1717, I can't reproduce the issue... my tests on xorg and wayland both yield the same result:

![Peek 2020-04-24 15-47](https://user-images.githubusercontent.com/33044886/80251297-672aa400-8643-11ea-8f7d-f575e798410d.gif)

Anything else going on? Did you restart gnome-shell following the extension installation? Thanks!

**Comment by JohnGalt1717** [comment] 2020-04-24 19:59
Maybe I just chose the wrong Issolate? There's 2 of them. One in the behavior section, and one on the screen you're showing? What's the other one for?

**Comment by charlesg99** [comment] 2020-04-24 22:21
The one under "behavior" is to isolate applications between workspaces, not monitors. Do I understand that it now works as you expect? Thanks!

**Comment by JohnGalt1717** [comment] 2020-04-25 14:21
It works based on the options but it's very not obvious which is which and what they do. I'd suggest that it's made more explicit what the difference is.

**Comment by charlesg99** [comment] 2020-04-25 14:38
Any suggestions? I mean, we have 2 labels: 
- Isolate monitors
- Isolate Workspaces

Aside from explaining what workspaces and monitors are, I don't see how this could be made more explicit. Thanks!

**Comment by JohnGalt1717** [comment] 2020-04-25 14:39
I'd suggest flattening out the multiple monitor options so that they aren't burried in a popup and have the same visual importance as the work spaces options. Perhaps have tabs for both.

**Comment by charlesg99** [comment] 2020-04-25 15:09
The "Isolate monitors" doesn't make sense unless panels are displayed on all monitors, that's why it currently is in the "Multi-monitors options" dialog. Anyway, it's no secret that our settings UI could use a facelift, but I'm going to close this as there is no issue with the isolate functionality. Thanks!

**Closed by charlesg99** 2020-04-25 15:09 UTC
Labels: bug
