### ISSUE TITLE
Intellihide is not working correct with ArchMenu

### ISSUE THREAD

**Issue by Crestanzio** [home-sweet-gnome/dash-to-panel#1991] opened 2023-11-17 22:57 UTC
**Log errors**

```text
cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
cogl_framebuffer_set_viewport: assertion 'width > 0 && height > 0' failed
clutter_actor_set_child_below_sibling: assertion 'sibling->priv->parent == self' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Invalid window geometry for xdg_surface@45. Ignoring for now, but this will result in client termination in the future.
```

**Describe the bug**
When i press the <Super> key  ArchMenu is shows up, that's fine. But when i press the <Super> key again,  to close ArchMenu, the dash-to-panel is still there, only when move my cursor panel disappeared. That's not supposed to happened, instead, the panel should be hidden again. Is there a way to fix this?

**System Info**
CachyOS Linux x86_64
Kernel: 6.6.1-1-cachyos
CPU: AMD Ryzen 5 5500U (12) @ 4,z
GPU: AMD Lucienne
GNOME Shell: 45.1
Dash To Panel: 59

**Where was Dash-to-Panel installed from?**
From distribution's package manager, but this problem also exist from GNOME extensions website.

**Screenshots / Video captures**
[intellihide-bug.webm](https://github.com/home-sweet-gnome/dash-to-panel/assets/57988055/bd80e0f0-e837-468e-a67a-8e0e222c4db4)

**Comment by Crestanzio** [comment] 2024-01-18 10:58
Is anyone looking at this problem? or atleast can someone guide me to solve by myself?

**Comment by charlesg99** [comment] 2024-04-11 03:56
I've looked at this and ArcMenu sets a hold on the panel when it shows its menu, but it only releases it when the mouse pointer moves (this is caused by PointerWatcher, a gnome-shell functionality used by ArcMenu) after closing it. In any case, this isn't an issue with dash-to-panel

**Closed by charlesg99** 2024-04-11 03:56 UTC
Labels: bug
