### ISSUE TITLE
Main panel on all displays

### ISSUE THREAD

**Issue by Lenald** [home-sweet-gnome/dash-to-panel#2007] opened 2023-12-24 15:29 UTC
I want to ask you, guys, for the next feature:
Here we can choose where to put the main panel (with the language and trailed applications like ToolBox, Telegram, Discord and etc
![image](https://github.com/home-sweet-gnome/dash-to-panel/assets/16639804/6204f187-cda7-4f9f-b3c7-1ab24564a6c2)
But we can choose only one of monitors. Could you make an extra option "all monitors" pls?

Why:
Now we can see the selected language on the only one monitor. Which is causing situations like "what is the language... Where is it... Dang, not here... Oh, there...." and so on.

I tried to clone the repo and try to find out how to implement it, but im dumbb in gnome extensions, and couldn't find the corresponding setting and it's implementation :(

**Comment by charlesg99** [comment] 2024-04-09 19:06
duplicate of #1951

**Closed by charlesg99** 2024-04-09 19:06 UTC
Labels: enhancement
