### ISSUE TITLE
support gnome-shell 40 

### ISSUE THREAD

**Issue by llegolas** [home-sweet-gnome/dash-to-panel#1297] opened 2021-03-19 21:00 UTC
Any plans of supporting gnome 40 ?

The extension stopped working on my Fedora34 (beta) which comes with gnome-shell 40

**Comment by Nonononoki** [comment] 2021-03-20 09:28
Duplicate: https://github.com/home-sweet-gnome/dash-to-panel/issues/1265

**Comment by nekohayo** [comment] 2021-06-09 12:27
@llegolas, please close this ticket as it is a duplicate of issue #1265.

**Closed** 2021-06-09 12:27 UTC
Labels: enhancement
