### ISSUE TITLE
[Feature Request] Alt menu 

### ISSUE THREAD

**Issue by akhilsukh01** [home-sweet-gnome/dash-to-panel#1068] opened 2020-07-06 23:50 UTC
Just a feature request, no issues or anything like that on my end.

Integrating the alt menu options for programs like Firefox to appear in the panel. I understand this would mean that they would have drop down menus, so it may clash with other tabs. Similar to the way MacOS does their taskbar.

**Comment by jderose9** [comment] 2020-07-10 10:52
@akhilsukh01 what do you mean by “alt menu”?

**Comment by akhilsukh01** [comment] 2020-07-10 15:27
Sorry what I meant was something like this.
![Screenshot from 2020-07-10 08-21-21-cropped](https://user-images.githubusercontent.com/30419699/87171086-18c29400-c287-11ea-8dea-86ffc7b63b55.jpg)

Maybe it's called something else but I've always called it an alt menu.

**Comment by boyfer** [comment] 2020-08-01 10:54
You want to integrate the application's menu into the taskbar. Normaly you would need two different panels. For the case of MacOS, they have two bars. A top bar for only this function and the application slider at the bottom.Probably you can find this functionality in a different extension. I remember the Ubuntu Unity had that functionality.

**Comment by jderose9** [comment] 2020-08-02 14:16
The feature you are looking for I have generally seen called a "global menu". This isn't really reasonable to implement because there is a lack of consistency in linux desktop applications for how their menus are implemented. Native GNOME applications generally have no "alt menu" at all. Implementing something that works for GTK applications would still leave many other non-GTK applications without a solution, and I can't imagine many would be happy with the inconsistency. I'm also skeptical we could rip the menu out of the application window without some applications having unexpected behavior. For those reasons, I don't think we will be interested in adding this feature to dash-to-panel anytime soon.

You can look at this reddit thread I found and perhaps it will provide some more information on problems with implementing this or possibly something closer to a solution that works for you:

https://www.reddit.com/r/gnome/comments/bibyi1/global_menu_in_gnome_332/

**Closed** 2020-08-02 14:16 UTC
Labels: enhancement
