### ISSUE TITLE
Touch input bricks GNOME Shell

### ISSUE THREAD

**Issue by HonbraDev** [home-sweet-gnome/dash-to-panel#1484] opened 2021-10-13 23:23 UTC
**Describe the bug**
When I touch the panel using my touchscreen (HP Spectre 14 x360), the panel and rest of GNOME Shell refuses to take mouse input. I have to search "Reboot" in the app menu to reboot my machine cleanly. Multitouch guestures on the touchscreen stop working too. I can use the individual programs just fine, but GNOME Shell refuses to cooperate.

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
40.4

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**
I am using Wayland. The stylus breaks it too.

Logs:
    Ignoring length property that isn't a number at line 1853, col 24
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Ignoring excess values in shadow definition
    Window manager warning: last_user_time (353408) is greater than comparison timestamp (353406).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
    Window manager warning: W0 appears to be one of the offending windows with a timestamp of 353408.  Working around...

**Comment by HonbraDev** [comment] 2021-10-13 23:28
https://user-images.githubusercontent.com/54026315/137226342-8fa04103-c7e9-4fba-b6ea-6405f59ddf30.mp4

**Comment by StormyIceLeopard** [comment] 2021-11-09 14:01
Same issue here.
HP ENVY x360 15-ee100
Ryzen 7 5700U
Manjaro, GNOME 40.4.0, Wayland

**Comment by TechnicallyComputers** [comment] 2021-11-11 20:25
Lenovo Thinkpad Yoga L390
Fedora 35 - Workstation - Gnome 41.1
Unusable with touchscreen, bricks almost instantly when used with touch.

**Comment by 9Lukas5** [comment] 2022-02-10 12:37
I have the same with Lenovo Ideapad Flex 5
Ubuntu 20.04, Gnome 41.1, Wayland

Anything touch related works, until I try to tap onto one of the application icons in the panel, then no touch or mouse input in any gnome item works anymore. Up until this, not dash-to-panel parts can be used with touch just fine.

AND: it's only in wayland sessions. Xorg sessions are fine.

**Comment by 9Lukas5** [comment] 2022-02-11 16:50
I made another observation: If I right click the panel and lock it, I can touch it without breaking the whole gnome-shell. It still won't work with my touches, but at least it doesn't crash the rest anymore.

**Comment by arpringle** [comment] 2022-04-02 04:37
I'm currently experiencing this same issue. I can usually poke the panel a few times before having issues, but eventually it simply freezes up and takes everything in GNOME with it.

The extension is unusable with touch in its current state.

**Comment by charlesg99** [comment] 2022-04-11 02:33
Duplicate of #689

**Closed by charlesg99** 2022-04-11 02:33 UTC
Labels: bug
