### ISSUE TITLE
Taskbar position

### ISSUE THREAD

**Issue by Alzemand** [home-sweet-gnome/dash-to-panel#841] opened 2019-12-25 19:02 UTC
It's possible to centralize the programs but keep the application menu on the left? I'm using the arc menu for this, but I would like to keep the original, like this: 

![image](https://user-images.githubusercontent.com/10548468/71449647-e8266d00-272f-11ea-8d63-c4e617357b95.png)

**Comment by charlesg99** [comment] 2019-12-27 15:30
Hello Alzemand, thanks for the suggestion, but I'll close it since it's a duplicate of #841 and #150. Please contribute further in one of those.

**Closed by charlesg99** 2019-12-27 15:30 UTC
