### ISSUE TITLE
Background not restored after maximizing when using dynamic opacity 

### ISSUE THREAD

**Issue by AlexKF98** [home-sweet-gnome/dash-to-panel#997] opened 2020-05-08 14:27 UTC
**Describe the bug**
1. Enable dynamic opacity for the panel background
2. Open a maximized window
3. Open another window without maximizing it
4. Click the right edge of the panel to minimize all windows
5. Click on the icon of the maximized window to reopen it
The panel will still be transparent

**Linux distribution and version**
Fedora 32

**GNOME Shell version**
3.36.2

**Dash-to-Panel version**
37

**Where was Dash-to-Panel installed from?**
GNOME extensions website,

**Screenshots / Video captures**
Example: https://i.imgur.com/L7Vy97O.mp4

**Comment by charlesg99** [comment] 2020-05-12 17:37
Hi AlexKF98, thank you for reporting this! I can't reproduce it so far, on my end when I restore the maximized Firefox window, the panel goes back to its opaque color. Is this on Wayland or Xorg? Thanks!

**Comment by AlexKF98** [comment] 2020-05-12 22:05
> Hi AlexKF98, thank you for reporting this! I can't reproduce it so far, on my end when I restore the maximized Firefox window, the panel goes back to its opaque color. Is this on Wayland or Xorg? Thanks!

I'm using Xorg.

**Comment by charlesg99** [comment] 2020-07-03 00:54
I'm going to close this now as I can't reproduce it on my end. Please let us know if you find the incompatibility, thanks!

![Peek 2020-07-02 20-52](https://user-images.githubusercontent.com/33044886/86420975-3d76a480-bca6-11ea-924f-a2530d07a52a.gif)

**Closed by charlesg99** 2020-07-03 00:54 UTC
Labels: bug
