### ISSUE TITLE
It does not work after GNOME Shell 40.0

### ISSUE THREAD

**Issue by erickwill** [home-sweet-gnome/dash-to-panel#1302] opened 2021-04-06 21:47 UTC
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
After upgrade to GNOME Shell 40.0 it gives a message into gnome shell extension: "OUTDATED" and does not work.

**Linux distribution and version**
Arch Linux with testing repositories enabled.

**GNOME Shell version**
GNOME Shell 40.0

**Dash-to-Panel version**
Current in GIT

**Where was Dash-to-Panel installed from?**
Directly from github.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by Turbine1991** [comment] 2021-04-06 22:16
There's already two other issues reporting this.

#1265
#1297

By the way, there's a experimental fork which works with Gnome 40. Check comments in the first issue I've listed.

![proof](https://user-images.githubusercontent.com/7228980/113784829-2bbcb300-978a-11eb-83bf-b1984c0d70eb.jpg)

**Comment by erickwill** [comment] 2021-04-06 23:24
Thanks, the experimental did the trick. I wonder if Show Applications Button is working for you.

**Comment by Turbine1991** [comment] 2021-04-07 00:24
> Thanks, the experimental did the trick. I wonder if Show Applications Button is working for you.

I'm using Arc launcher for Gnome 40. Perhaps give that a go.

**Comment by korvinko** [comment] 2021-04-10 15:40
I've created PKGBUILD for ArchLinux
https://gist.github.com/korvinko/7138925d71ce89d822e20998e1c63e42

**Comment by archont00** [comment] 2021-04-10 17:23
As an alternative, there is already an PKGBUILD in AUR, you just need to download it and change the url of GitHub:
```
trizen -G gnome-shell-extens~dash-to-panel-git
cd gnome-shell-extens~dash-to-panel-git
# Now edit the PKGBUILD and update the following line to read:
# _githubowner=philippun1
# Then build and install
makepkg -s
trizen -U gnome-shell-extension-dash-to-panel*.pkg.tar.xz
```

**Comment by work-chausat** [comment] 2021-04-12 05:23
@philippun1 In philippun1's fork version, "override panel theme background color" doesn't work!!!!! The color always becomes black from the override color.

**Comment by Turbine1991** [comment] 2021-04-13 12:01
> @philippun1 In philippun1's fork version, "override panel theme background color" doesn't work!!!!! The color always becomes black from the override color.

At least it works. Anything's better than default Gnome.

**Comment by promach** [comment] 2021-04-26 02:34
@archont00 I tried the PKGBUILD and modified the `_github_owner` field and then rebuild everything, however the extension is still blocked in gnome 40. Why ?

**Comment by AlexGluck** [comment] 2021-05-02 08:26
Install fork, found a bug when scroll on panel volume doesn't change.

**Comment by promach** [comment] 2021-05-02 10:21
The following are the PKGBUILD and the corresponding error log:

```
# $Id$
# Maintainer: Mohammadreza Abdollahzadeh < morealaz at gmail dot com >
# Contributor: Carl George < arch at cgtx dot us >

pkgname=gnome-shell-extension-dash-to-panel-git
pkgver=40.r8.ge4a71fa
pkgrel=1
pkgdesc='Extension for GNOME shell to combine the dash and main panel'
arch=(any)
_githubname=dash-to-panel
#_githubowner=home-sweet-gnome
_githubowner=philippun1
url="https://github.com/${_githubowner}/${_githubname}"
license=(GPL2)
depends=('gnome-shell>=3.22')
makedepends=('git' 'gnome-common' 'intltool')
provides=("${pkgname%-git}")
conflicts=("${pkgname%-git}")
install='gnome-shell-extension.install'
source=("git+${url}.git")
sha256sums=('SKIP')

pkgver() {
  cd "${srcdir}/${_githubname}"
  git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "${srcdir}/${_githubname}"
  make _build
}

package() {
  cd "${srcdir}/${_githubname}"
  make DESTDIR="$pkgdir" install
}
# vim:set ts=2 sw=2 et:
```

```
The settings of extension dash-to-panel@jderose9.github.com had an error:

Gtk.BuilderError: /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/Settings.ui:26:39 Invalid property: GtkFrame.shadow_type
```

Stack trace:
```
_init@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:168:23
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:19:10
newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:115:21
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2199:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by philippun1** [comment] 2021-05-02 15:42
@promach This seems to be an older version of the branch, because there is no more shadow_type in the ui file.
@AlexGluck If you scroll directly over the volume icon it should work.

**Comment by erickwill** [comment] 2021-05-04 16:26
> @promach This seems to be an older version of the branch, because there is no more shadow_type in the ui file.
> @AlexGluck If you scroll directly over the volume icon it should work.

Dear @philippun1 I'm currently using your fork beautifully, but yesterday the main git source was updated probably with a version higher than your branch what resulted in unwanted updates from the official branch which is still broke. Can you increase, probably, the version number in order that extension manager ignore the official branch version preventing the undesired update? Thanks!

**Comment by AlexGluck** [comment] 2021-05-05 11:48
@philippun1 Yep, thx on volume icon scroll work. But i thinked scroll will be work on panel.

**Comment by nekohayo** [comment] 2021-06-09 12:26
@erickwill, please close this ticket as it is a duplicate of issue #1265.

**Closed** 2021-06-09 12:53 UTC
Labels: bug
