### ISSUE TITLE
Two column of icons?

### ISSUE THREAD

**Issue by vlskrbek** [home-sweet-gnome/dash-to-panel#861] opened 2020-02-06 13:27 UTC
Hi I look for this long time and now I find it. 
Would it be possible to get the icons have in two or more columns?
I have notebook with full HD display and there is not so much space on top or down so I use bar have in the left. Then when I size the bar so the time is in one row (hh:mm:ss) the icons are so big there are shown a little of them. 

I would like to have possibility to change the size of icon so it can be displayed in one or more colums instead of in one row.
See the picture.
Thanks

![image](https://user-images.githubusercontent.com/44057715/73941047-d4ecec80-48ec-11ea-95bd-01bdec09740a.png)

**Comment by charlesg99** [comment] 2020-02-11 19:49
Hello vlskrbek! Thanks for your input, this looks like a duplicate of #268. As for the icon size, you could make them smaller using the different settings, but unfortunately it won't change the space they occupy, which is always a square at the moment.

**Closed** 2020-02-15 19:08 UTC
