### ISSUE TITLE
100% CPU usage on panel hover

### ISSUE THREAD

**Issue by wmute** [home-sweet-gnome/dash-to-panel#530] opened 2018-12-15 21:27 UTC
Hi, When mouse hovering over icons on the panel gnome-shell quickly gobbles up all of my cpu usage, it persists for a few seconds after moving the mouse off the panel. Added a gif for illustration. 

![peek 2018-12-15 22-24](https://user-images.githubusercontent.com/35043713/50047580-49951400-00b8-11e9-888b-4224b33276a1.gif)

An issue from 2017 suggested top icons as a culprit for CPU issues, but it occurs with top icons turned off as well. OS is Fedora 29 64bit, gnome shell version: 3.30.2

**Comment by catb0t** [comment] 2018-12-16 04:36
Using integrated graphics card / software rendering? My guess is the live previews take a lot of CPU time by themselves

**Comment by wmute** [comment] 2018-12-16 18:57
Can confirm, not a problem on xorg. Doesn't seem to be a graphics card issue.

**Comment by jderose9** [comment] 2018-12-17 15:31
Does this happen with the Alternate-tab extension enabled, when you Alt-tab through the previews?

**Comment by charlesg99** [comment] 2018-12-17 15:48
I did more testing and removed the window clones from the window preview popup menus. Even with the empty popup menus, the cpu usage was the same (high). So, surprisingly, it would seem that the problem is with the popupmenu itself (on wayland), not with the window clones. 

The same high cpu usage can be observed when opening the default clock menu and system menu, so I don't think it is a dash-to-panel specific problem... These all seem related: #62 #515 #453.

**Comment by antonvalletas** [comment] 2019-04-06 16:05
Yes, I can also confirm this is only a problem on wayland on my XPS 15 9570. It works with absolutely 0 lag on X.org so I will be switching to X.org for now.

**Comment by charlesg99** [comment] 2019-06-23 00:23
The new version of the window previews is available on master. Going to close this for now as the popupmenu have been completely removed and my tests showed that they were the source of the high cpu usage. Please try it out and open a new issue if the cpu usage is still too high on Wayland. Thanks!

**Closed by charlesg99** 2019-06-23 00:23 UTC
