### ISSUE TITLE
Tray Icon padding is off after monitor scale changes

### ISSUE THREAD

**Issue by Oschowa** [home-sweet-gnome/dash-to-panel#889] opened 2020-03-10 14:36 UTC
After changing the scale of a monitor (i.e. from 1x to 2x) the padding of the Tray Icons/Clock is wrong and is only correctly updated after you mouse-over them.
Tested with gnome-shell/mutter 3.36 and dash-to-panel git.

GIF demonstration:

![Screencast from 10 03 2020 15:30:27_000](https://user-images.githubusercontent.com/8129300/76323344-e27b0500-62e4-11ea-99d8-934a45aa258a.gif)

**Comment by charlesg99** [comment] 2020-03-11 17:11
Hello Oschowa! I can't reproduce this so far on 3.36 (xorg or wayland) using the latest master. Could you try disabling your other extensions, restart gnome-shell and see if the issue persists? Thanks!

**Comment by Oschowa** [comment] 2020-03-11 19:42
Thanks for looking into this.
It still happens for me 100% of the time with all extensions but Dash-to-Panel disabled on Xorg when i for example change the scaling of my 1920x1080 monitor for 2x to 1x.

My dash to panel config
[dash_to_panel.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/4320443/dash_to_panel.txt)

**Comment by moriony** [comment] 2020-03-12 15:01
I have the same behavior with enabled dash-to-panel and without it. Tried to disable all extensions, same story. So I suppose this is a gnome-shell problem.

I have Arch, Gnome 3.36 + Xorg.

**Comment by charlesg99** [comment] 2020-03-12 17:30
Looks like #739, although a workaround for this was added for this. Also see https://gitlab.gnome.org/GNOME/gnome-shell/issues/1708. Going to close this for now as it doesn't seem to be a dash to panel issue and I can't reproduce it. Thanks!

**Closed by charlesg99** 2020-03-12 17:30 UTC
