### ISSUE TITLE
Move to current Workspace

### ISSUE THREAD

**Issue by ddnexus** [home-sweet-gnome/dash-to-panel#654] opened 2019-05-25 04:10 UTC
Something that is notably missing from the system is a way to "Move to current Workspace" and it would be a very useful addition to DtP.

It may work exactly like the standard "Move to Workspace Up/Down/Left/Right", just adding it the option of the current workspace.

It could be an addition to the context menu of the peeked window or a small button on the window frame... whatever is simpler.

**Comment by charlesg99** [comment] 2019-05-26 01:36
Hello ddnexus, please pull/install the `custom-window-preview` branch again, the context menu was restored and the option to move the window to the current Workspace was added. Thanks!

**Comment by ddnexus** [comment] 2019-05-26 02:22
WOW! That's GENIUS!!! Thank you!

The glitch of the disappearing bar when hovering on a menu is still too annoying to switch though. Could you reproduce it?

**Comment by charlesg99** [comment] 2019-05-26 12:47
Sorry I couldn't reproduce the disappearing issue you mentioned, but I changed the way the preview menu interacts with the intellihide. Could you please try again? Maybe this will solve it on your end. Thanks!

**Comment by ddnexus** [comment] 2019-05-26 13:19
No luck. Still the same. When I just reinstall it, and restart the shell, it is quite unstable... something randomly doesn't work. And even a full system restart doesn't help. I even tried to disable all the other extensions but no luck.
It looks like it is not aware that there is a menu out and hovered... it just hides it as it was not hovering... after a couple of second that it disappeared, the menu moves down to the border of the screen and the panel doesn't reappear until you click on something else to make the menu disappear.

**Comment by ddnexus** [comment] 2019-05-26 13:38
I mean the system/extensions menus, not the application menus.

**Comment by charlesg99** [comment] 2019-05-26 14:01
My bad, I mistakenly committed something specific to newer gnome-shell versions. Just fixed it after testing on Debian 9 and I guess it was the source of the instability you encountered.

Intellihide now works as intented for me on gnome-shell `3.18.5`, `3.22.3`, `3.28.3` and `3.32.2`. Could you provide more information on your setup? Do you see errors in your logs? Thanks!

**Comment by ddnexus** [comment] 2019-05-26 14:13
GNOME Shell 3.32.0
LookingGlass: "... has not emitted any errors"
and still doesn't work :/

**Comment by ddnexus** [comment] 2019-05-26 14:26
I did a bisect on the branch and the commit that breaks it is a3c8da82d418265ba255db1c3a217fb26303bb91

HTH

**Closed** 2019-05-29 03:27 UTC
