### ISSUE TITLE
IntelliHide issue: the bar goes back to windows that don't use "native title bar style"

### ISSUE THREAD

**Issue by nicolasmol** [home-sweet-gnome/dash-to-panel#1666] opened 2022-05-14 16:15 UTC
### Hi
- Manjaro,
- DashtoPanel Extension alone + restart session, done.

### How to reproduce

- Hide the gnome top bar 
- Open an application, like VsCode but set window.titleBarStyle to "Custom"
-  Set the animation delay quite long enough to see what happens
- make this aplication window maximasized or even full screen.
- move the mouse cursor at the bottom
- The bar reveals, and once totaly up, flips behind the application's window

### Brief analysis

- This bug occurs whatever the "Intellihide settings". I mean I tried to turn on/off all subsettings or change delais without any success
- In previous Gnome 41.5, this bug did not concern **Google Chrome** or **Brave**. I noticed this bug only with VsCode + "custom title bar" and OnlyOffice with the same option.
- If a "native window" (e.g. Nautilus) is coming over theses "maximasized applications", the panel behaves as expected.
- Or if you let the top panel, the bar behaves normally

**Comment by zevlee** [comment] 2022-05-14 20:42
I have similar issues with panel intellihide when Chromium is maximized or full screen, where the bar reveals, then flips behind the window. The problem exists when the top bar not shown, but goes away if the top bar is forced to appear. I should note that the items function as though they are visible. If you click on the space that an icon would occupy if it were still visible, it still works.

I'm using GNOME 42.1 on Fedora 36.

**Comment by augusto-gtns** [comment] 2022-05-16 15:56
i noticed this only happens with wayland window system, after change to x11 it worked perfectly

**Comment by nicolasmol** [comment] 2022-05-16 16:17
I tried x11 here with Manjaro, without your  luck...
Please take mostly into account that this bug did not concerne Google Chrome with Gnome 41.5 but with 42, yes...
That will maybe help your by tracking your recent changes to make your assumptions what could be the cause.

**Comment by billyc** [comment] 2022-05-25 18:54
Can confirm this on my setup as well:

- VS Code with custom titlebar enabled 
- Fedora 36 with Gnome 42
- Wayland 

Panel "Intellihide" enabled; tried all combinations of intellihide settings. The bar flashes visibly and uncontrollably during the show/hide animations.

**Comment by nicolasmol** [comment] 2022-05-26 17:12
Apparently it's an old known bug that concerns also Dash-to-dock. Since we know the only workaround is to keep the original gnome-shell top bar, would not be possible to "hide it" when windows are maximized, but still moving its components (time, tray icons, etc...) inside the panel ?

**Comment by charlesg99** [comment] 2023-02-10 12:50
I could reproduce on a wayland machine (finally). This should be fixed on the master branch.

**Comment by miraklesource** [comment] 2023-02-15 02:50
I'm experiencing the exact same bug on Nobara 37. Intellihide only works as intended with GTK apps. Otherwise, the panel appears and disappears almost instantly.

**Comment by charlesg99** [comment] 2023-03-12 14:34
Fixed in the latest version

**Closed by charlesg99** 2023-03-12 14:34 UTC
Labels: bug

**Comment by LethalManBoob** [comment] 2023-03-17 09:37
> Fixed in the latest version

it isnt.
