### ISSUE TITLE
Panel position cause this bug in using workspace.

### ISSUE THREAD

**Issue by wastee** [home-sweet-gnome/dash-to-panel#766] opened 2019-10-10 03:33 UTC
## what i want

- drag windows from workspace 1 to workspace 2
- drag windows from workspace 2 to workspace 1

## what happend

When the panel position is on bottom (by default), it works.

When the panel postion is on top, it failed. I can not drag windows from workspace 1 to workspace 2, etc..

![Peek 2019-10-10 11-00](https://user-images.githubusercontent.com/22229962/66537069-c1559300-eb51-11e9-8225-428f516a7e8c.gif)

## version

| apps          | version         |
| ------------- | --------------- |
| dash-to-panel | 23.r76.g7e7c5eb |
| mutter        | 3.34.1          |
| gnome-shell   | 3.34.1          |

**Comment by charlesg99** [comment] 2019-10-10 12:24
Hello wastee, Thanks for bringing this up! This is indeed a regression due to some 3.34 workarounds and it should now be fixed on master.

**Closed** 2019-10-10 12:33 UTC
