### ISSUE TITLE
Dynamic transparency not functioning with autohide

### ISSUE THREAD

**Issue by natohutch** [home-sweet-gnome/dash-to-panel#921] opened 2020-03-30 11:53 UTC
**Describe the bug**
When autohide is turned on, bringing a window towards the panel will not change its transparency. I have it currently set to 0% opacity by default, and when a window comes within 10px it should change to 45%. However moving it towards the panel which is on the bottom does nothing, moving the window towards the top of the screen applies the change.

**Linux distribution and version**
Ubuntu 18.04

**GNOME Shell version**
3.34.3

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
apt install

**Additional Info**
Using arc theme

**Comment by charlesg99** [comment] 2020-03-30 15:16
Hello natohutch, thank you for the report, I can reproduce the issue, I'll fix it later today when I get a chance. 

@jderose9. I'd like to include this fix in v32, so please hold off the release until I submit a fix (today).

**Comment by jderose9** [comment] 2020-03-30 17:33
@charlesg99 Got it. Just let me know when you are good on your end.

**Comment by natohutch** [comment] 2020-03-31 11:53
cheers guys <3

**Comment by charlesg99** [comment] 2020-03-31 14:42
Hey guys, the fix has been pushed to a branch named `permanent-clipcontainer`. Could you please pull it and test it a bit? So far it is working good for me on g-s 3.36, 3.34, 3.28 and 3.22, but the more testing the better as I touched some of my code that felt "fragile". Thanks!

**Comment by natohutch** [comment] 2020-04-01 11:42
Cheers for fixing it. It's working on my machine. One little request, would you be able to split it for each monitor? Cheers :)

**Comment by charlesg99** [comment] 2020-04-01 14:27
@natohutch Glad it's working! By "split it for each monitor", you mean that you'd like to have a different target opacity per monitor when a window gets close?

**Comment by charlesg99** [comment] 2020-04-01 19:38
@jderose9 I think we're good for v32, I've merged the clipcontainer branch and it seems stable enough on my end. At the current rate reviews are processed on e.g.o., we can always adjust later, but releasing a fix for #905 seems worthwhile for now. Thanks!

**Closed by charlesg99** 2020-04-01 19:38 UTC
Labels: bug

**Comment by jderose9** [comment] 2020-04-01 19:42
@charlesg99 Awesome! I'll run some tests on old shell versions and get it out later today.

**Comment by natohutch** [comment] 2020-04-02 00:25
Yeah exactly @charlesg99

**Comment by natohutch** [comment] 2020-08-09 12:54
Seems like we're getting this issue again :( also I have a problem with the hidden panel not staying up when I maximise a window. For example, I maximise a window, put my cursor to the bottom, the panel pops up, and immediately goes away again. Happy to make a new issue, however these seem related.

**Comment by charlesg99** [comment] 2020-08-09 13:18
Hello Nathanael, we're going to need more info as I can't reproduce those issues so far. For me the dynamic transparency works correctly with the auto-hide enabled and the panel stays up with a maximized window. Did you install new extensions lately? Thanks!
