### ISSUE TITLE
Feature request (episode 2)

### ISSUE THREAD

**Issue by PranavBhattrai** [home-sweet-gnome/dash-to-panel#613] opened 2019-03-28 03:13 UTC
1. There should a way to have transparent taskbar which doesn't make transparent to those areas where there is an icon, dates, times, etc. Only the blank area get transparent.

2.**Another** Shortkey to hide/revel panel without overriding other windows. And this shortkey should not be inside "Panel Intellhide". Because the effects are different and isolated. _(a little confusion in this one)_

3. "Panel screen position" should also have Left and Right option. Currently, we can assign the taskbar to either top or button.

**Comment by jderose9** [comment] 2019-03-28 15:01
Hi @PranavBhattrai !

1. I think this has to be done with theming. I recommend checking out [Plano](https://github.com/lassekongo83/plano-theme).
2. I believe this is a duplicate of your issue #604 so I will go ahead and close this instance.
3. This is a duplicate of #3.

In the future, it would be helpful to split your concerns/ideas out into separate issues so that their state can be tracked independently. Thank you!

**Closed by jderose9** 2019-03-28 15:01 UTC

**Comment by PranavBhattrai** [comment] 2019-03-28 15:18
> Hi @PranavBhattrai !
> 
> 1. I think this has to be done with theming. I recommend checking out [Plano](https://github.com/lassekongo83/plano-theme).
> 2. I believe this is a duplicate of your issue #604 so I will go ahead and close this instance.
> 3. This is a duplicate of #3.
> 
> In the future, it would be helpful to split your concerns/ideas out into separate issues so that their state can be tracked independently. Thank you!

Thanks about point 2 mentioned. But it would be more awesome if it was built-in.
