### ISSUE TITLE
Notification dot spacing

### ISSUE THREAD

**Issue by BentHaase** [home-sweet-gnome/dash-to-panel#670] opened 2019-06-25 10:05 UTC
When using dash to panel and having (multiple) app indicators in the status bar, the notification dot offsets all icons to the left. Once clicked on the date/time area, the dot disappears and so does the spacing.

To me this looks like an inconsistent UI design. Is this by choice or can this be fixed by adding a fixed area around the time/date that stays regardless of the notification dot's visibility?

Pre clicking:
![statusbar_notification_dot_visible](https://user-images.githubusercontent.com/5788982/60089690-4fdc0b00-9741-11e9-80b5-3972113c1cd0.png)

Post clicking:
![statusbar_notification_dot_not_visible](https://user-images.githubusercontent.com/5788982/60089692-510d3800-9741-11e9-9303-efe11ee2c41f.png)

**Comment by charlesg99** [comment] 2019-06-25 21:19
Hello BentHaase, do you have other extensions that might interfere with the spacing? I'm using Topicons plus and I can't reproduce the issue. The spacing stays the same when the dot is removed. Also, which gnome-shell version are you on? Thanks!

**Comment by BentHaase** [comment] 2019-06-26 05:29
I am using `GNOME Shell 3.32.1` and the only extensions in use are `Dash-to-Panel` (version 19 [..] `d99a`) and `Ubuntu appindicators` (does the same thing like Topicons plus).

**Comment by jderose9** [comment] 2019-07-08 19:35
Thanks @BentHaase . I have the same issue and it annoys me too :) I'm not really sure what an ideal fix would look like though. If the space was preserved when the indicator isn't present, there would be an unusually large amount of whitespace around that element. Any suggestions?

**Comment by charlesg99** [comment] 2019-09-15 14:32
Hello, that extra padding on the left was removed during the vertical panel work, so the clock padding should now be consistent. If you want to have a look, please [install the development branch](https://github.com/home-sweet-gnome/dash-to-panel/issues/3#issuecomment-529162697). Thanks!

**Comment by charlesg99** [comment] 2019-09-23 02:44
The fix to remove the padding was merged to master, please try it out. Thanks!

**Closed by charlesg99** 2019-09-23 02:44 UTC

**Comment by BentHaase** [comment] 2019-09-23 05:50
![image](https://user-images.githubusercontent.com/5788982/65403955-b15e5500-ddd6-11e9-93e7-19f176e094ba.png)

Much apprecuated @charlesg99. I will test it today and see how it works out.
