### ISSUE TITLE
function GLib.idle_add: At least 2 arguments required, but only 1 passed

### ISSUE THREAD

**Issue by gtirloni** [home-sweet-gnome/dash-to-panel#2015] opened 2024-01-10 13:38 UTC
**Describe the bug**

Error shows up in `journalctl /usr/bin/gnome-shell -f -o cat`:

```
JS ERROR: TypeError: function GLib.idle_add: At least 2 arguments required, but only 1 passed
_onScrollSizeChange@file:///home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:562:41
Taskbar/<@file:///home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:395:28
vfunc_allocate@file:///home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:143:20
vfunc_allocate/allocateGroup/<@file:///home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:803:31
allocateGroup@file:///home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:799:28
vfunc_allocate@file:///home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:845:34
@resource:///org/gnome/shell/ui/init.js:21:20
```

**Linux distribution and version**
Fedora 39

**GNOME Shell version**
45.3

**Dash-to-Panel version**
59

**Where was Dash-to-Panel installed from?**
GNOME extensions website

**Additional Info**
No issues detected, just reporting the error in case it needs attention.

Thanks for making this great extension!

**Comment by tekstryder** [comment] 2024-01-13 22:32
Duplicate of https://github.com/home-sweet-gnome/dash-to-panel/issues/1971

Fixed on master and v60 via commit https://github.com/home-sweet-gnome/dash-to-panel/commit/e9d8702d50c523f6c1bf5fae9f07c2104cd8565a

**Closed** 2024-01-14 13:26 UTC
Labels: bug
